// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define(["exports","../arcade/FunctionWrapper","../arcade/ImmutableArray","./languageUtils","../core/promiseUtils"],function(v,x,y,c,p){function w(h){function t(e,g){if(g instanceof x)return h.arcadeCustomFunctionHandler(g);if(g instanceof c.NativeFunction)return(...b)=>g.fn(e,{preparsed:!0,arguments:b});if(g instanceof c.SizzleFunction)return(...b)=>{if(b.length!==g.paramCount)throw Error("Invalid parameters");return g.fn(...b)};throw Error("Invalid Parameter");}function u(e){if(e instanceof y)return e.toArray();
if(c.isArray(e))return e;throw Error("Invalid Parameter");}h.functions.array=function(e,g){return h.standardFunction(e,g,function(b,d,a){c.pcCheck(a,1,2);b=c.toNumber(a[0]);if(isNaN(b)||!1===c.isInteger(b))throw Error("Invalid Parameter");a=c.defaultUndefined(a[1],null);b=Array(b);b.fill(a);return b})};h.functions.front=function(e,g){return h.standardFunction(e,g,function(b,d,a){c.pcCheck(a,1,1);if(c.isImmutableArray(a[0])){if(0>=a[0].length())throw Error("Array is empty");return a[0].get(0)}if(c.isArray(a[0])){if(0>=
a[0].length)throw Error("Array is empty");return a[0][0]}throw Error("Invalid Parameter");})};h.functions.back=function(e,g){return h.standardFunction(e,g,function(b,d,a){c.pcCheck(a,1,1);if(c.isImmutableArray(a[0])){if(0>=a[0].length())throw Error("Array is empty");return a[0].get(a[0].length()-1)}if(c.isArray(a[0])){if(0>=a[0].length)throw Error("Array is empty");return a[0][a[0].length-1]}throw Error("Invalid Parameter");})};h.functions.push=function(e,g){return h.standardFunction(e,g,function(b,
d,a){c.pcCheck(a,1,2);if(c.isArray(a[0]))return a[0][a[0].length]=a[1],a[0].length;throw Error("Invalid Parameter");})};h.functions.pop=function(e,g){return h.standardFunction(e,g,function(b,d,a){c.pcCheck(a,1,1);if(c.isArray(a[0])){if(0>=a[0].length)throw Error("Array is empty");b=a[0][a[0].length-1];--a[0].length;return b}throw Error("Invalid Parameter");})};h.functions.erase=function(e,g){return h.standardFunction(e,g,function(b,d,a){c.pcCheck(a,2,2);if(c.isArray(a[0])){b=c.toNumber(a[1]);if(isNaN(b)||
!1===c.isInteger(b))throw Error("Invalid Parameter");a=a[0];if(0>=a.length)throw Error("Array is empty");0>b&&(b=a.length+b);if(0>b)throw Error("Element not found");if(b>=a.length)throw Error("Index is greater than array");a.splice(b,1);return c.voidOperation}throw Error("Invalid Parameter");})};h.functions.insert=function(e,g){return h.standardFunction(e,g,function(b,d,a){c.pcCheck(a,3,3);if(c.isArray(a[0])){b=c.toNumber(a[1]);if(isNaN(b)||!1===c.isInteger(b))throw Error("Invalid Parameter");d=a[2];
a=a[0];if(b>a.length)throw Error("Index is greater than array");if(0>b&&b<-1*a.length)throw Error("Index is greater than array");if(b===a.length)return a[b]=d,c.voidOperation;a.splice(b,0,d);return c.voidOperation}throw Error("Invalid Parameter");})};h.functions.resize=function(e,g){return h.standardFunction(e,g,function(b,d,a){c.pcCheck(a,2,3);if(c.isArray(a[0])){d=c.toNumber(a[1]);if(isNaN(d)||!1===c.isInteger(d))throw Error("Invalid Parameter");if(0>d)throw Error("Size cannot be negative");b=c.defaultUndefined(a[2],
null);a=a[0];if(a.length>=d)return a.length=d,c.voidOperation;const k=a.length;a.length=d;for(d=k;d<a.length;d++)a[d]=b;return c.voidOperation}throw Error("Invalid Parameter");})};h.functions.includes=function(e,g){return h.standardFunction(e,g,function(b,d,a){c.pcCheck(a,2,2);if(c.isArray(a[0])){const k=a[1];return-1<a[0].findIndex(f=>c.equalityTest(f,k))?!0:!1}if(c.isImmutableArray(a[0])){const k=a[1];return-1<a[0].toArray().findIndex(f=>c.equalityTest(f,k))?!0:!1}throw Error("Invalid Parameter");
})};h.functions.slice=function(e,g){return h.standardFunction(e,g,function(b,d,a){c.pcCheck(a,1,3);if(c.isArray(a[0])){b=c.toNumber(c.defaultUndefined(a[1],0));d=c.toNumber(c.defaultUndefined(a[2],a[0].length));if(isNaN(b)||!1===c.isInteger(b))throw Error("Invalid Parameter");if(isNaN(d)||!1===c.isInteger(d))throw Error("Invalid Parameter");return a[0].slice(b,d)}if(c.isImmutableArray(a[0])){b=a[0];d=c.toNumber(c.defaultUndefined(a[1],0));a=c.toNumber(c.defaultUndefined(a[2],b.length()));if(isNaN(d)||
!1===c.isInteger(d))throw Error("Invalid Parameter");if(isNaN(a)||!1===c.isInteger(a))throw Error("Invalid Parameter");return b.toArray().slice(d,a)}throw Error("Invalid Parameter");})};h.functions.splice=function(e,g){return h.standardFunction(e,g,function(b,d,a){b=[];for(d=0;d<a.length;d++)c.isArray(a[d])?b.push(...a[d]):c.isImmutableArray(a[d])?b.push(...a[d].toArray()):b.push(a[d]);return b})};"sync"===h.mode&&(h.functions.any=function(e,g){return h.standardFunction(e,g,function(b,d,a){c.pcCheck(a,
2,2);b=t(e,a[1]);a=u(a[0]);for(const k of a)if(a=b(k),c.isBoolean(a)&&!0===a)return!0;return!1})},h.functions.all=function(e,g){return h.standardFunction(e,g,function(b,d,a){c.pcCheck(a,2,2);b=t(e,a[1]);a=u(a[0]);for(const k of a)if(!0!==b(k))return!1;return!0})},h.functions.none=function(e,g){return h.standardFunction(e,g,function(b,d,a){c.pcCheck(a,2,2);b=t(e,a[1]);a=u(a[0]);for(const k of a)if(!0===b(k))return!1;return!0})},h.functions.reduce=function(e,g){return h.standardFunction(e,g,function(b,
d,a){c.pcCheck(a,2,3);const k=t(e,a[1]);b=u(a[0]);return 2===a.length?0===b.length?null:b.reduce((f,l)=>{f=k(f,l);return f=void 0!==f&&f!==c.voidOperation?f:null}):b.reduce((f,l)=>{f=k(f,l);return f=void 0!==f&&f!==c.voidOperation?f:null},a[2])})},h.functions.map=function(e,g){return h.standardFunction(e,g,function(b,d,a){c.pcCheck(a,2,2);b=t(e,a[1]);d=u(a[0]);a=[];for(const k of d)d=b(k),void 0!==d&&d!==c.voidOperation?a.push(d):a.push(null);return a})},h.functions.filter=function(e,g){return h.standardFunction(e,
g,function(b,d,a){c.pcCheck(a,2,2);b=t(e,a[1]);a=u(a[0]);d=[];for(const k of a)!0===b(k)&&d.push(k);return d})});"async"===h.mode&&(h.functions.any=function(e,g){return h.standardFunctionAsync(e,g,function(b,d,a){c.pcCheck(a,2,2);const k=t(e,a[1]);var f=!1;return u(a[0]).reduce((l,m,q)=>l.then(n=>{0<q&&!0===n&&(f=!0);if(!0===f)return p.resolve(!0);n=k(m);return p.isPromiseLike(n)?n:p.resolve(n)}),Promise.resolve(!1)).then(l=>{!0===l&&(f=!0);return f})})},h.functions.all=function(e,g){return h.standardFunctionAsync(e,
g,function(b,d,a){c.pcCheck(a,2,2);const k=t(e,a[1]);var f=!0;return u(a[0]).reduce((l,m,q)=>l.then(n=>{0<q&&!0!==n&&(f=!1);if(!1===f)return p.resolve(!1);n=k(m);return p.isPromiseLike(n)?n:p.resolve(n)}),Promise.resolve(!0)).then(l=>{!0!==l&&(f=!1);return f})})},h.functions.none=function(e,g){return h.standardFunctionAsync(e,g,function(b,d,a){c.pcCheck(a,2,2);const k=t(e,a[1]);var f=!0;return u(a[0]).reduce((l,m,q)=>l.then(n=>{0<q&&!0===n&&(f=!1);if(!1===f)return p.resolve(!0);n=k(m);return p.isPromiseLike(n)?
n:p.resolve(n)}),Promise.resolve(!1)).then(l=>{!0===l&&(f=!1);return f})})},h.functions.filter=function(e,g){return h.standardFunctionAsync(e,g,function(b,d,a){c.pcCheck(a,2,2);const k=t(e,a[1]),f=u(a[0]),l=[];return f.reduce((m,q,n)=>m.then(r=>{0<n&&!0===r&&l.push(f[n-1]);r=k(q);return p.isPromiseLike(r)?r:p.resolve(r)}),Promise.resolve(!1)).then(m=>{!0===m&&0<f.length&&l.push(f[f.length-1]);return l})})},h.functions.reduce=function(e,g){return h.standardFunctionAsync(e,g,function(b,d,a){c.pcCheck(a,
2,3);const k=t(e,a[1]);b=u(a[0]);d=null;if(2<a.length)a=c.defaultUndefined(a[2],null),d=b.reduce((f,l)=>f.then(m=>{if(void 0===m||m===c.voidOperation)m=null;m=k(m,l);return p.isPromiseLike(m)?m:p.resolve(m)}),Promise.resolve(a));else{if(0===b.length)return null;d=b.reduce((f,l,m)=>1>=m?(f=k(f,l),p.isPromiseLike(f)?f:p.resolve(f)):f.then(q=>{if(void 0===q||q===c.voidOperation)q=null;q=k(q,l);return p.isPromiseLike(q)?q:p.resolve(q)}))}return d.then(f=>void 0!==f&&f!==c.voidOperation?f:null)})},h.functions.map=
function(e,g){return h.standardFunctionAsync(e,g,function(b,d,a){c.pcCheck(a,2,2);const k=t(e,a[1]),f=u(a[0]);var l=[];return f.reduce((m,q,n)=>m.then(r=>{0<n&&(void 0!==r&&r!==c.voidOperation?l.push(r):l.push(null));r=k(q);return p.isPromiseLike(r)?r:p.resolve(r)}),Promise.resolve()).then(m=>{0<f.length&&(void 0!==m&&m!==c.voidOperation?l.push(m):l.push(null));return l})})})}const z=Object.freeze({__proto__:null,registerFunctions:w});v.ArrayFunctions=z;v.registerFunctions=w});