// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../Viewpoint ../../core/Collection ../../core/Error ../../core/Evented ../../core/Logger ../../core/maybe ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/decorators/cast ../../core/accessorSupport/decorators/subclass ../../webdoc/support/Thumbnail ../../webmap/Bookmark ../support/GoTo".split(" "),function(m,f,D,e,n,E,F,y,k,M,N,G,H,I,z,J){const p=F.getLogger("esri.widgets.Bookmarks.BookmarksViewModel"),
A=e.ofType(z),K={width:128,height:128,format:"png"},q={takeScreenshot:!0,captureViewpoint:!0,captureRotation:!0,captureScale:!0,captureTimeExtent:!0},B={time:!0};e=function(C){function r(a){a=C.call(this,a)||this;a.abilities={...B};a.activeBookmark=null;return a}m._inheritsLoose(r,C);var l=r.prototype;l.destroy=function(){this.view=null;this._set("activeBookmark",null)};l.castAbilities=function(a){return{...B,...a}};l.createBookmark=function(){var a=m._asyncToGenerator(function*(b){const {view:d,
defaultCreateOptions:c,abilities:g}=this;if(!d)return b=new n("create-bookmark:invalid-view","Cannot create a bookmark without a view."),p.error(b),Promise.reject(b);const {takeScreenshot:h,screenshotSettings:u,captureViewpoint:v,captureRotation:w,captureScale:x,captureTimeExtent:t}={...c,...b};b=h?yield this._createThumbnail(u):void 0;const L=g.time&&t&&y.isSome(d.timeExtent)?d.timeExtent.clone():void 0;return new z({...b&&{thumbnail:b},...t&&{timeExtent:L},...v&&{viewpoint:this._createViewpoint({view:d,
captureScale:x,captureRotation:w})}})});return function(b){return a.apply(this,arguments)}}();l.editBookmark=function(){var a=m._asyncToGenerator(function*(b,d){const {view:c,defaultEditOptions:g}=this;if(!c)return b=new n("edit-bookmark:invalid-view","Cannot edit a bookmark without a view."),p.error(b),Promise.reject(b);const {takeScreenshot:h,screenshotSettings:u,captureViewpoint:v,captureRotation:w,captureScale:x,captureTimeExtent:t}={...g,...d};if(d=h?yield this._createThumbnail(u):void 0)b.thumbnail=
d;v&&(b.viewpoint=this._createViewpoint({view:c,captureScale:x,captureRotation:w}));t&&y.isSome(c.timeExtent)&&(b.timeExtent=c.timeExtent.clone());this.emit("bookmark-edit",{bookmark:b});return b});return function(b,d){return a.apply(this,arguments)}}();l.goTo=function(a){const {abilities:b,view:d}=this;if(!d)return a=new n("go-to:invalid-view","Cannot go to a bookmark without a view"),p.error(a),Promise.reject(a);var c=null==a?void 0:a.viewpoint;if(!c)return a=new n("go-to:invalid-bookmark","Cannot go to a bookmark that does not contain a 'viewpoint'.",
{bookmark:a}),p.error(a),Promise.reject(a);this._set("activeBookmark",a);c=this.callGoTo({target:c});const g=null==a?void 0:a.timeExtent;b.time&&g&&(d.timeExtent=g);this.emit("bookmark-select",{bookmark:a});c.catch(()=>{}).then(()=>this._set("activeBookmark",null));return c};l._createThumbnail=function(){var a=m._asyncToGenerator(function*(b){b=yield this.view.takeScreenshot({...K,...b});return new I({url:b.dataUrl})});return function(b){return a.apply(this,arguments)}}();l._createViewpoint=function({view:a,
captureRotation:b,captureScale:d}){var c,g;const h=null==(c=a.viewpoint)?void 0:c.clone();return new D({targetGeometry:null==(g=a.extent)?void 0:g.clone(),rotation:b&&(null==h?void 0:h.rotation)||0,scale:d&&(null==h?void 0:h.scale)||0})};m._createClass(r,[{key:"bookmarks",get:function(){return this.get("view.map.bookmarks")||new A},set:function(a){void 0===a?this._clearOverride("bookmarks"):this._override("bookmarks",a)}},{key:"defaultCreateOptions",get:function(){return q},set:function(a){this._set("defaultCreateOptions",
{...q,...a})}},{key:"defaultEditOptions",get:function(){return q},set:function(a){this._set("defaultEditOptions",{...q,...a})}},{key:"state",get:function(){const a=this.get("view");return a&&!a.ready?"loading":"ready"}},{key:"view",get:function(){return this._get("view")},set:function(a){a&&"2d"!==a.type&&p.error(new n("view:invalid-view","SceneView is not supported",{view:a}));this._set("view",a)}}]);return r}(J.GoToMixin(E.EventedAccessor));f.__decorate([k.property()],e.prototype,"abilities",void 0);
f.__decorate([G.cast("abilities")],e.prototype,"castAbilities",null);f.__decorate([k.property({readOnly:!0})],e.prototype,"activeBookmark",void 0);f.__decorate([k.property({type:A})],e.prototype,"bookmarks",null);f.__decorate([k.property()],e.prototype,"defaultCreateOptions",null);f.__decorate([k.property()],e.prototype,"defaultEditOptions",null);f.__decorate([k.property({readOnly:!0})],e.prototype,"state",null);f.__decorate([k.property({value:null})],e.prototype,"view",null);return e=f.__decorate([H.subclass("esri.widgets.Bookmarks.BookmarksViewModel")],
e)});