// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define(["exports","../../chunks/languageUtils","../../intl/locale","../../chunks/datetime"],function(q,c,t,m){function r(g){g=new Date(g.getTime());const h=g.getFullYear();var e=new Date(0);e.setFullYear(h+1,0,4);e.setHours(0,0,0,0);e=n(e);var f=new Date(0);f.setFullYear(h,0,4);f.setHours(0,0,0,0);f=n(f);return g.getTime()>=e.getTime()?h+1:g.getTime()>=f.getTime()?h:h-1}function n(g){g=new Date(g.getTime());var h=g.getDay();h=(1>h?7:0)+h-1;g.setDate(g.getDate()-h);g.setHours(0,0,0,0);return g}function l(g){return null===
g?g:isNaN(g.getTime())?null:g}const u=[0,31,59,90,120,151,181,212,243,273,304,334],v=[0,31,60,91,121,152,182,213,244,274,305,335];q.registerFunctions=function(g,h){g.today=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,0,0);a=new Date;a.setHours(0,0,0,0);return a})};g.now=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,0,0);return new Date})};g.timestamp=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,0,0);a=new Date;return a=new Date(a.getUTCFullYear(),a.getUTCMonth(),a.getUTCDate(),
a.getUTCHours(),a.getUTCMinutes(),a.getUTCSeconds(),a.getUTCMilliseconds())})};g.toutc=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,1);a=c.toDate(b[0]);return null===a?null:new Date(a.getUTCFullYear(),a.getUTCMonth(),a.getUTCDate(),a.getUTCHours(),a.getUTCMinutes(),a.getUTCSeconds(),a.getUTCMilliseconds())})};g.tolocal=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,1);a=c.toDate(b[0]);return null===a?null:m.DateTime.utc(a.getFullYear(),a.getMonth()+1,a.getDate(),a.getHours(),
a.getMinutes(),a.getSeconds(),a.getMilliseconds()).toJSDate()})};g.day=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,1);a=c.toDate(b[0]);return null===a?NaN:a.getDate()})};g.month=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,1);a=c.toDate(b[0]);return null===a?NaN:a.getMonth()})};g.year=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,1);a=c.toDate(b[0]);return null===a?NaN:a.getFullYear()})};g.hour=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,1);a=c.toDate(b[0]);
return null===a?NaN:a.getHours()})};g.second=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,1);a=c.toDate(b[0]);return null===a?NaN:a.getSeconds()})};g.millisecond=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,1);a=c.toDate(b[0]);return null===a?NaN:a.getMilliseconds()})};g.minute=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,1);a=c.toDate(b[0]);return null===a?NaN:a.getMinutes()})};g.week=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,2);a=c.toDate(b[0]);
if(null===a)return NaN;b=c.toNumber(c.defaultUndefined(b[1],0));if(0>b||6<b)throw Error("Invalid Parameter");d=a.getDate();var k=a.getMonth();const p=a.getFullYear();a=a.getDay();d=d+(0!==p%4||0===p%100&&0!==p%400?u:v)[k]-1;k=Math.floor(d/7);return a-b+(0>a-b?7:0)<d-7*k?k+1:k})};g.weekday=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,1);a=c.toDate(b[0]);return null===a?NaN:a.getDay()})};g.isoweekday=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,1);a=c.toDate(b[0]);if(null===
a)return NaN;a=a.getDay();0===a&&(a=7);return a})};g.isomonth=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,1);a=c.toDate(b[0]);return null===a?NaN:a.getMonth()+1})};g.isoweek=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,1);d=c.toDate(b[0]);if(null===d)return NaN;a=n(d).getTime();d=r(d);b=new Date(0);b.setFullYear(d,0,4);b.setHours(0,0,0,0);d=n(b);a-=d.getTime();return Math.round(a/6048E5)+1})};g.isoyear=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,1,1);a=c.toDate(b[0]);
return null===a?NaN:r(a)})};g.date=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,0,7);if(3===b.length)return l(new Date(c.toNumber(b[0]),c.toNumber(b[1]),c.toNumber(b[2]),0,0,0,0));if(4===b.length)return l(new Date(c.toNumber(b[0]),c.toNumber(b[1]),c.toNumber(b[2]),c.toNumber(b[3]),0,0,0));if(5===b.length)return l(new Date(c.toNumber(b[0]),c.toNumber(b[1]),c.toNumber(b[2]),c.toNumber(b[3]),c.toNumber(b[4]),0,0));if(6===b.length)return l(new Date(c.toNumber(b[0]),c.toNumber(b[1]),c.toNumber(b[2]),
c.toNumber(b[3]),c.toNumber(b[4]),c.toNumber(b[5]),0));if(7===b.length)return l(new Date(c.toNumber(b[0]),c.toNumber(b[1]),c.toNumber(b[2]),c.toNumber(b[3]),c.toNumber(b[4]),c.toNumber(b[5]),c.toNumber(b[6])));if(2===b.length){a=c.toString(b[1]);if(""===a)return null;a=c.standardiseDateFormat(a);b="X"===a?m.DateTime.fromSeconds(c.toNumber(b[0])):"x"===a?m.DateTime.fromMillis(c.toNumber(b[0])):m.DateTime.fromFormat(c.toString(b[0]),a,{locale:t.getLocale(),numberingSystem:"latn"});return b.isValid?
b.toJSDate():null}if(1===b.length){if(c.isString(b[0])){if(""===b[0].replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,""))return null;if(!0===/^[0-9][0-9][0-9][0-9]$/.test(b[0]))return c.toDate(b[0]+"-01-01")}a=c.toNumber(b[0]);return!1===isNaN(a)?l(new Date(a)):c.toDate(b[0])}if(0===b.length)return new Date})};g.datediff=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,2,3);a=c.toDateTime(b[0]);d=c.toDateTime(b[1]);if(null===a||null===d)return NaN;switch(c.toString(b[2]).toLowerCase()){case "days":case "day":case "d":return a.diff(d,
"days").days;case "months":case "month":return a.diff(d,"months").months;case "minutes":case "minute":case "m":return"M"===b[2]?a.diff(d,"months").months:a.diff(d,"minutes").minutes;case "seconds":case "second":case "s":return a.diff(d,"seconds").seconds;case "milliseconds":case "millisecond":case "ms":return a.diff(d).milliseconds;case "hours":case "hour":case "h":return a.diff(d,"hours").hours;case "years":case "year":case "y":return a.diff(d,"years").years;default:return a.diff(d).milliseconds}})};
g.dateadd=function(e,f){return h(e,f,function(a,d,b){c.pcCheck(b,2,3);a=c.toDateTime(b[0]);if(null===a)return null;d=c.toNumber(b[1]);if(isNaN(d))return a.toJSDate();let k="milliseconds";switch(c.toString(b[2]).toLowerCase()){case "days":case "day":case "d":k="days";d=c.absRound(d);break;case "months":case "month":k="months";d=c.absRound(d);break;case "minutes":case "minute":case "m":k="M"===b[2]?"months":"minutes";break;case "seconds":case "second":case "s":k="seconds";break;case "milliseconds":case "millisecond":case "ms":k=
"milliseconds";break;case "hours":case "hour":case "h":k="hours";break;case "years":case "year":case "y":k="years"}return a.plus({[k]:d}).toJSDate()})}};Object.defineProperty(q,"__esModule",{value:!0})});