// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../Graphic ../../arcade/featureset/support/FeatureSetQueryInterceptor ../../core/Accessor ../../core/Handles ../../core/Logger ../../core/maybe ../../core/promiseUtils ../../core/throttle ../../core/watchUtils ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/decorators/cast ../../core/accessorSupport/decorators/subclass ../../popup/content/TextContent ./FeatureAttachments/FeatureAttachmentsViewModel ./FeatureContent/FeatureContentViewModel ./FeatureExpression/FeatureExpressionViewModel ./FeatureFields/FeatureFieldsViewModel ./FeatureMedia/FeatureMediaViewModel ./support/arcadeFeatureUtils ./support/featureUtils ./support/relatedFeatureUtils".split(" "),
function(t,m,H,I,h,J,K,C,B,L,D,q,U,V,M,N,O,P,E,Q,R,x,S,n,w){var y;const T=K.getLogger("esri.widgets.FeatureViewModel"),F={attachmentsContent:!0,customContent:!0,expressionContent:!0,fieldsContent:!0,mediaContent:!0,textContent:!0};h=y=function(G){function z(a){var b=G.call(this,a)||this;b._handles=new J;b._error=null;b._featureAbortController=null;b.graphicChangedThrottled=L.throttle(b.graphicChanged,1,t._assertThisInitialized(b));b._expressionAttributes=null;b._graphicExpressionAttributes=null;b.abilities=
{...F};b.content=null;b.contentViewModels=[];b.defaultPopupTemplateEnabled=!1;b.formattedAttributes=null;b.lastEditInfo=null;b.relatedInfos=new Map;b.title="";b.view=null;b._isAllowedContentType=c=>{const {abilities:d}=t._assertThisInitialized(b);return"attachments"===c.type&&d.attachmentsContent||"custom"===c.type&&d.customContent||"fields"===c.type&&d.fieldsContent||"media"===c.type&&d.mediaContent||"text"===c.type&&d.textContent||"expression"===c.type&&d.expressionContent};b._handles.add(D.init(t._assertThisInitialized(b),
["graphic","_effectivePopupTemplate","abilities"],()=>b.graphicChangedThrottled()));return b}t._inheritsLoose(z,G);var f=z.prototype;f.destroy=function(){this._clear();this._cancelFeatureQuery();this._error=null;this._handles.destroy();this.graphic=this._handles=null;this._destroyContentViewModels();this.relatedInfos.clear()};f.castAbilities=function(a){return{...F,...a}};f.setActiveMedia=function(a,b){a=this.contentViewModels[a];a instanceof x&&a.setActiveMedia(b)};f.nextMedia=function(a){a=this.contentViewModels[a];
a instanceof x&&a.next()};f.previousMedia=function(a){a=this.contentViewModels[a];a instanceof x&&a.previous()};f._clear=function(){this._set("title","");this._set("content",null);this._set("formattedAttributes",null)};f.graphicChanged=function(){var a=t._asyncToGenerator(function*(){this._cancelFeatureQuery();this._error=null;this._clear();const {graphic:b}=this;if(b){var c=new AbortController;this._featureAbortController=c;try{yield this._queryFeature({signal:c.signal})}catch(d){B.isAbortError(d)||
(this._error=d,T.error("error","The popupTemplate could not be displayed for this feature.",{error:d,graphic:b,popupTemplate:this._effectivePopupTemplate}))}this._featureAbortController===c&&(this._featureAbortController=null)}});return function(){return a.apply(this,arguments)}}();f._cancelFeatureQuery=function(){const {_featureAbortController:a}=this;a&&a.abort();this._featureAbortController=null};f._compileContentElement=function(a,b){if("attachments"===a.type)return this._compileAttachments(a,
b);if("custom"===a.type)return this._compileCustom(a,b);if("fields"===a.type)return this._compileFields(a,b);if("media"===a.type)return this._compileMedia(a,b);if("text"===a.type)return this._compileText(a,b);if("expression"===a.type)return this._compileExpression(a,b)};f._compileContent=function(a){this._destroyContentViewModels();if(this.graphic)return Array.isArray(a)?a.filter(this._isAllowedContentType).map((b,c)=>this._compileContentElement(b,c)):"string"===typeof a?this._compileText(new O({text:a}),
0).text:a};f._destroyContentViewModels=function(){var a;null==(a=this._handles)?void 0:a.remove("content-view-models");this.contentViewModels.forEach(b=>b&&!b.destroyed&&b.destroy());this._set("contentViewModels",[])};f._setExpressionContentVM=function(a,b){const {formattedAttributes:c}=this,{contentElement:d,contentElementViewModel:e}=a;a=null==d?void 0:d.type;e&&a&&("fields"===a&&(this._createFieldsFormattedAttributes({contentElement:d,contentElementIndex:b,formattedAttributes:c}),e.set(this._createFieldsVMParams(d,
b))),"media"===a&&(this._createMediaFormattedAttributes({contentElement:d,contentElementIndex:b,formattedAttributes:c}),e.set(this._createMediaVMParams(d,b))),"text"===a&&e.set(this._createTextVMParams(d)))};f._compileExpression=function(a,b){const {expressionInfo:c}=a,{graphic:d,map:e,spatialReference:g,view:l}=this,k=new Q({expressionInfo:c,graphic:d,interceptor:y.interceptor,map:e,spatialReference:g,view:l});this.contentViewModels[b]=k;this._handles.add(D.init(k,"contentElementViewModel",()=>this._setExpressionContentVM(k,
b)),"content-view-models");return a};f._compileAttachments=function(a,b){const {graphic:c}=this,{description:d,title:e}=a;this.contentViewModels[b]=new P({graphic:c,...this._compileTitleAndDesc({title:e,description:d})});return a};f._compileCustom=function(a,b){const {graphic:c}=this,{creator:d,destroyer:e}=a;this.contentViewModels[b]=new E({graphic:c,creator:d,destroyer:e});return a};f._compileTitleAndDesc=function({title:a,description:b}){const {_fieldInfoMap:c,_sourceLayer:d,graphic:e,formattedAttributes:g,
_expressionAttributes:l}=this,{attributes:k}=e,p=g.global;return{title:n.substituteFieldsInLinksAndAttributes({attributes:k,fieldInfoMap:c,globalAttributes:p,expressionAttributes:l,layer:d,text:a}),description:n.substituteFieldsInLinksAndAttributes({attributes:k,fieldInfoMap:c,globalAttributes:p,expressionAttributes:l,layer:d,text:b})}};f._createFieldsVMParams=function(a,b){const {_effectivePopupTemplate:c,formattedAttributes:d}=this,e={...d.global,...d.content[b]};b=(null==a?void 0:a.fieldInfos)||
(null==c?void 0:c.fieldInfos);b=null==b?void 0:b.filter(({fieldName:p})=>n.isExpressionField(p)||n.isRelatedField(p)||e.hasOwnProperty(p));const g=null==c?void 0:c.expressionInfos,{description:l,title:k}=a;return{attributes:e,expressionInfos:g,fieldInfos:b,...this._compileTitleAndDesc({title:k,description:l})}};f._compileFields=function(a,b){const c=a.clone();a=new R(this._createFieldsVMParams(a,b));this.contentViewModels[b]=a;c.fieldInfos=a.formattedFieldInfos.slice(0);return c};f._createMediaVMParams=
function(a,b){const {graphic:c,_fieldInfoMap:d,formattedAttributes:e,_effectivePopupTemplate:g,relatedInfos:l,_sourceLayer:k,_expressionAttributes:p}=this,{attributes:u}=c,{description:r,mediaInfos:v,title:A}=a;return{activeMediaInfoIndex:a.activeMediaInfoIndex||0,attributes:u,layer:k,fieldInfoMap:d,formattedAttributes:{...e.global,...e.content[b]},expressionAttributes:p,mediaInfos:v,popupTemplate:g,relatedInfos:l,...this._compileTitleAndDesc({title:A,description:r})}};f._compileMedia=function(a,
b){const c=a.clone();a=new x(this._createMediaVMParams(a,b));c.mediaInfos=a.formattedMediaInfos.slice(0);this.contentViewModels[b]=a;return c};f._createTextVMParams=function(a){const {graphic:b,_fieldInfoMap:c,_sourceLayer:d,_expressionAttributes:e}=this;if(a&&a.text){const {attributes:g}=b;a.text=n.substituteFieldsInLinksAndAttributes({attributes:g,fieldInfoMap:c,globalAttributes:this.formattedAttributes.global,expressionAttributes:e,layer:d,text:a.text})}return{graphic:b,creator:a.text}};f._compileText=
function(a,b){a=a.clone();this.contentViewModels[b]=new E(this._createTextVMParams(a));return a};f._compileLastEditInfo=function(){const {_effectivePopupTemplate:a,_sourceLayer:b,graphic:c}=this;if(a){var {lastEditInfoEnabled:d}=a,e=null==b?void 0:b.editFieldsInfo;if(d&&e)return n.formatEditInfo(e,c.attributes)}};f._compileTitle=function(a){const {_fieldInfoMap:b,_sourceLayer:c,graphic:d,_expressionAttributes:e}=this,{attributes:g}=d;return n.substituteFieldsInLinksAndAttributes({attributes:g,fieldInfoMap:b,
globalAttributes:this.formattedAttributes.global,expressionAttributes:e,layer:c,text:a})};f._getTitle=function(){var a=t._asyncToGenerator(function*(){const {_effectivePopupTemplate:b,graphic:c}=this;return n.graphicCallback(null==b?void 0:b.title,{graphic:c})});return function(){return a.apply(this,arguments)}}();f._getContent=function(){var a=t._asyncToGenerator(function*(){const {_effectivePopupTemplate:b,graphic:c}=this;return n.graphicCallback(null==b?void 0:b.content,{graphic:c})});return function(){return a.apply(this,
arguments)}}();f._queryFeature=function(){var a=t._asyncToGenerator(function*(b){const {_featureAbortController:c,_sourceLayer:d,graphic:e,_effectivePopupTemplate:g,spatialReference:l,map:k,view:p}=this,{content:{value:u},title:{value:r}}=yield B.eachAlways({content:this._getContent(),title:this._getTitle()});c===this._featureAbortController&&e&&(yield n.queryUpdatedFeature({graphic:e,popupTemplate:g,layer:d,spatialReference:l},b),{expressionAttributes:{value:b}}=yield B.eachAlways({checkForRelatedFeatures:this._checkForRelatedFeatures(b),
expressionAttributes:S.createCompiledExpressions({expressionInfos:null==g?void 0:g.expressionInfos,spatialReference:l,graphic:e,map:k,interceptor:y.interceptor,view:p})}),c===this._featureAbortController&&e&&(this._expressionAttributes=b,this._graphicExpressionAttributes={...e.attributes,...b},this._set("formattedAttributes",this._createFormattedAttributes(u)),this._set("title",this._compileTitle(r)),this._set("lastEditInfo",this._compileLastEditInfo()||null),this._set("content",this._compileContent(u)||
null)))});return function(b){return a.apply(this,arguments)}}();f._createMediaFormattedAttributes=function({contentElement:a,contentElementIndex:b,formattedAttributes:c}){const {_effectivePopupTemplate:d,graphic:e,relatedInfos:g,_sourceLayer:l,_fieldInfoMap:k,_graphicExpressionAttributes:p}=this;c.content[b]=n.formatAttributes({fieldInfos:null==d?void 0:d.fieldInfos,graphic:e,attributes:{...p,...a.attributes},layer:l,fieldInfoMap:k,relatedInfos:g})};f._createFieldsFormattedAttributes=function({contentElement:a,
contentElementIndex:b,formattedAttributes:c}){if(a.fieldInfos){const {graphic:d,relatedInfos:e,_sourceLayer:g,_fieldInfoMap:l,_graphicExpressionAttributes:k}=this;c.content[b]=n.formatAttributes({fieldInfos:a.fieldInfos,graphic:d,attributes:{...k,...a.attributes},layer:g,fieldInfoMap:l,relatedInfos:e})}};f._createFormattedAttributes=function(a){const {_effectivePopupTemplate:b,graphic:c,relatedInfos:d,_sourceLayer:e,_fieldInfoMap:g,_graphicExpressionAttributes:l}=this,k={global:n.formatAttributes({fieldInfos:null==
b?void 0:b.fieldInfos,graphic:c,attributes:l,layer:e,fieldInfoMap:g,relatedInfos:d}),content:[]};Array.isArray(a)&&a.forEach((p,u)=>{"fields"===p.type&&this._createFieldsFormattedAttributes({contentElement:p,contentElementIndex:u,formattedAttributes:k});"media"===p.type&&this._createMediaFormattedAttributes({contentElement:p,contentElementIndex:u,formattedAttributes:k})});return k};f._checkForRelatedFeatures=function(a){const {graphic:b,_effectivePopupTemplate:c}=this;return this._queryRelatedInfos(b,
n.getAllFieldInfos(c),a)};f._queryRelatedInfos=function(){var a=t._asyncToGenerator(function*(b,c,d){const {relatedInfos:e,_sourceLayer:g}=this;e.clear();const l=C.isSome(g.associatedLayer)?yield g.associatedLayer.load(d):g;if(l){var k=c.filter(r=>r&&n.isRelatedField(r.fieldName));if(k&&k.length){c.forEach(r=>this._configureRelatedInfo(r,l));var p=yield w.queryLayerInfos({relatedInfos:e,layer:l},d);Object.keys(p).forEach(r=>{var v;const A=e.get(r.toString());r=null==(v=p[r])?void 0:v.value;A&&r&&
(A.layerInfo=r.data)});var u=yield w.queryRelatedFeatures({graphic:b,relatedInfos:e,layer:l},d);Object.keys(u).forEach(r=>{var v;w.setRelatedFeatures(null==(v=u[r])?void 0:v.value,e.get(r.toString()))})}}});return function(b,c,d){return a.apply(this,arguments)}}();f._configureRelatedInfo=function(a,b){const {relatedInfos:c}=this,d=w.getRelatedFieldInfo(a.fieldName);if(d){var {layerId:e,fieldName:g}=d;e&&(b=c.get(e.toString())||w.createRelatedInfo(e,b))&&(w.updateRelatedInfo({relatedInfo:b,fieldName:g,
fieldInfo:a}),this.relatedInfos.set(e,b))}};t._createClass(z,[{key:"_effectivePopupTemplate",get:function(){return C.isSome(this.graphic)?this.graphic.getEffectivePopupTemplate(this.defaultPopupTemplateEnabled):null}},{key:"_fieldInfoMap",get:function(){return n.createfieldInfoMap(n.getAllFieldInfos(this._effectivePopupTemplate),this._sourceLayer)}},{key:"_sourceLayer",get:function(){return n.getSourceLayer(this.graphic)}},{key:"state",get:function(){return this.graphic?this._error?"error":this.waitingForContent?
"loading":"ready":"disabled"}},{key:"graphic",set:function(a){this._set("graphic",a?a.clone():null)}},{key:"spatialReference",get:function(){return this.get("view.spatialReference")||null},set:function(a){void 0===a?this._clearOverride("spatialReference"):this._override("spatialReference",a)}},{key:"map",get:function(){return this.get("view.map")||null},set:function(a){void 0===a?this._clearOverride("map"):this._override("map",a)}},{key:"waitingForContent",get:function(){return!!this._featureAbortController}}]);
return z}(h);h.interceptor=new I.FeatureSetQueryInterceptor(n.preLayerQueryCallback,n.preRequestCallback);m.__decorate([q.property()],h.prototype,"_error",void 0);m.__decorate([q.property()],h.prototype,"_featureAbortController",void 0);m.__decorate([q.property({readOnly:!0})],h.prototype,"_effectivePopupTemplate",null);m.__decorate([q.property({readOnly:!0})],h.prototype,"_fieldInfoMap",null);m.__decorate([q.property({readOnly:!0})],h.prototype,"_sourceLayer",null);m.__decorate([q.property()],h.prototype,
"abilities",void 0);m.__decorate([M.cast("abilities")],h.prototype,"castAbilities",null);m.__decorate([q.property({readOnly:!0})],h.prototype,"content",void 0);m.__decorate([q.property({readOnly:!0})],h.prototype,"contentViewModels",void 0);m.__decorate([q.property({type:Boolean})],h.prototype,"defaultPopupTemplateEnabled",void 0);m.__decorate([q.property({readOnly:!0})],h.prototype,"state",null);m.__decorate([q.property({readOnly:!0})],h.prototype,"formattedAttributes",void 0);m.__decorate([q.property({type:H,
value:null})],h.prototype,"graphic",null);m.__decorate([q.property({readOnly:!0})],h.prototype,"lastEditInfo",void 0);m.__decorate([q.property({readOnly:!0})],h.prototype,"relatedInfos",void 0);m.__decorate([q.property()],h.prototype,"spatialReference",null);m.__decorate([q.property({readOnly:!0})],h.prototype,"title",void 0);m.__decorate([q.property()],h.prototype,"map",null);m.__decorate([q.property({readOnly:!0})],h.prototype,"waitingForContent",null);m.__decorate([q.property()],h.prototype,"view",
void 0);return h=y=m.__decorate([N.subclass("esri.widgets.FeatureViewModel")],h)});