// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../kernel ../kernel ../../chunks/languageUtils ./centroid ../../core/promiseUtils ../../geometry/Extent ../../geometry/Geometry ../../geometry/geometryEngineAsync ../../geometry/Multipoint ../../geometry/Point ../../geometry/Polygon ../../geometry/Polyline ../../geometry/support/jsonUtils ../../core/unitUtils".split(" "),function(z,E,k,b,t,F,x,l,h,A,y,u,v,B,G){function C(d){return 0===E.version.indexOf("4.")?u.fromExtent(d):new u({spatialReference:d.spatialReference,rings:[[[d.xmin,
d.ymin],[d.xmin,d.ymax],[d.xmax,d.ymax],[d.xmax,d.ymin],[d.xmin,d.ymin]]]})}function r(d){b.pcCheck(d,2,2);if(!(d[0]instanceof l&&d[1]instanceof l||d[0]instanceof l&&null===d[1]||d[1]instanceof l&&null===d[0]||null===d[0]&&null===d[1]))throw Error("Illegal Argument");}function D(d,e){if("polygon"!==d.type&&"polyline"!==d.type&&"extent"!==d.type)return F.resolve(0);var f=1;if(d.spatialReference.vcsWkid||d.spatialReference.latestVcsWkid){f=t.getMetersPerVerticalUnitForSR(d.spatialReference);var c=G.getMetersPerUnitForSR(d.spatialReference);
f/=c}c=0;if("polyline"===d.type)for(var g of d.paths)for(var a=1;a<g.length;a++)c+=t.segmentLength3d(g[a],g[a-1],f);else if("polygon"===d.type)for(a of d.rings){for(g=1;g<a.length;g++)c+=t.segmentLength3d(a[g],a[g-1],f);if(a[0][0]!==a[a.length-1][0]||a[0][1]!==a[a.length-1][1]||void 0!==a[0][2]&&a[0][2]!==a[a.length-1][2])c+=t.segmentLength3d(a[0],a[a.length-1],f)}else"extent"===d.type&&(c+=2*t.segmentLength3d([d.xmin,d.ymin,0],[d.xmax,d.ymin,0],f),c+=2*t.segmentLength3d([d.xmin,d.ymin,0],[d.xmin,
d.ymax,0],f),c=2*c+4*Math.abs(b.defaultUndefined(d.zmax,0)*f-b.defaultUndefined(d.zmin,0)*f));d=new v({hasZ:!1,hasM:!1,spatialReference:d.spatialReference,paths:[[0,0],[0,c]]});return h.planarLength(d,e)}z.registerFunctions=function(d){"async"===d.mode&&(d.functions.disjoint=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);r(a);return null===a[0]||null===a[1]?!0:h.disjoint(a[0],a[1])})},d.functions.intersects=function(e,f){return d.standardFunctionAsync(e,
f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);r(a);return null===a[0]||null===a[1]?!1:h.intersects(a[0],a[1])})},d.functions.touches=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);r(a);return null===a[0]||null===a[1]?!1:h.touches(a[0],a[1])})},d.functions.crosses=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);r(a);return null===a[0]||null===a[1]?!1:h.crosses(a[0],a[1])})},d.functions.within=
function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);r(a);return null===a[0]||null===a[1]?!1:h.within(a[0],a[1])})},d.functions.contains=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);r(a);return null===a[0]||null===a[1]?!1:h.contains(a[0],a[1])})},d.functions.overlaps=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);r(a);return null===a[0]||null===a[1]?
!1:h.overlaps(a[0],a[1])})},d.functions.equals=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){b.pcCheck(a,2,2);return a[0]===a[1]?!0:a[0]instanceof l&&a[1]instanceof l?h.equals(a[0],a[1]):b.isDate(a[0])&&b.isDate(a[1])?a[0].getTime()===a[1].getTime():!1})},d.functions.relate=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,3,3);if(a[0]instanceof l&&a[1]instanceof l)return h.relate(a[0],a[1],b.toString(a[2]));if(a[0]instanceof
l&&null===a[1]||a[1]instanceof l&&null===a[0]||null===a[0]&&null===a[1])return!1;throw Error("Illegal Argument");})},d.functions.intersection=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);r(a);return null===a[0]||null===a[1]?null:h.intersect(a[0],a[1])})},d.functions.union=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);c=[];if(0===a.length)throw Error("Function called with wrong number of Parameters");
if(1===a.length)if(b.isArray(a[0]))for(a=b.autoCastFeatureToGeometry(a[0]),g=0;g<a.length;g++){if(null!==a[g]){if(!(a[g]instanceof l))throw Error("Illegal Argument");c.push(a[g])}}else if(b.isImmutableArray(a[0]))for(a=b.autoCastFeatureToGeometry(a[0].toArray()),g=0;g<a.length;g++){if(null!==a[g]){if(!(a[g]instanceof l))throw Error("Illegal Argument");c.push(a[g])}}else{if(a[0]instanceof l)return b.fixSpatialReference(k.cloneGeometry(a[0]),e.spatialReference);if(null===a[0])return null;throw Error("Illegal Argument");
}else for(g=0;g<a.length;g++)if(null!==a[g]){if(!(a[g]instanceof l))throw Error("Illegal Argument");c.push(a[g])}return 0===c.length?null:h.union(c)})},d.functions.difference=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);r(a);return null!==a[0]&&null===a[1]?k.cloneGeometry(a[0]):null===a[0]?null:h.difference(a[0],a[1])})},d.functions.symmetricdifference=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);
r(a);return null===a[0]&&null===a[1]?null:null===a[0]?k.cloneGeometry(a[1]):null===a[1]?k.cloneGeometry(a[0]):h.symmetricDifference(a[0],a[1])})},d.functions.clip=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,2,2);if(!(a[1]instanceof x)&&null!==a[1])throw Error("Illegal Argument");if(null===a[0])return null;if(!(a[0]instanceof l))throw Error("Illegal Argument");return null===a[1]?null:h.clip(a[0],a[1])})},d.functions.cut=function(e,f){return d.standardFunctionAsync(e,
f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,2,2);if(!(a[1]instanceof v)&&null!==a[1])throw Error("Illegal Argument");if(null===a[0])return[];if(!(a[0]instanceof l))throw Error("Illegal Argument");return null===a[1]?[k.cloneGeometry(a[0])]:h.cut(a[0],a[1])})},d.functions.area=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){b.pcCheck(a,1,2);a=b.autoCastFeatureToGeometry(a);if(null===a[0])return 0;if(b.isFeatureSet(a[0]))return a[0].sumArea(k.convertSquareUnitsToCode(b.defaultUndefined(a[1],
-1)),!1,e.abortSignal).then(n=>{if(e.abortSignal.aborted)throw Error("Operation has been cancelled.");return n});if(b.isArray(a[0])||b.isImmutableArray(a[0]))return c=b.autoCastArrayOfPointsToPolygon(a[0],e.spatialReference),null===c?0:h.planarArea(c,k.convertSquareUnitsToCode(b.defaultUndefined(a[1],-1)));if(!(a[0]instanceof l))throw Error("Illegal Argument");return h.planarArea(a[0],k.convertSquareUnitsToCode(b.defaultUndefined(a[1],-1)))})},d.functions.areageodetic=function(e,f){return d.standardFunctionAsync(e,
f,function(c,g,a){b.pcCheck(a,1,2);a=b.autoCastFeatureToGeometry(a);if(null===a[0])return 0;if(b.isFeatureSet(a[0]))return a[0].sumArea(k.convertSquareUnitsToCode(b.defaultUndefined(a[1],-1)),!0,e.abortSignal).then(n=>{if(e.abortSignal.aborted)throw Error("Operation has been cancelled.");return n});if(b.isArray(a[0])||b.isImmutableArray(a[0]))return c=b.autoCastArrayOfPointsToPolygon(a[0],e.spatialReference),null===c?0:h.geodesicArea(c,k.convertSquareUnitsToCode(b.defaultUndefined(a[1],-1)));if(!(a[0]instanceof
l))throw Error("Illegal Argument");return h.geodesicArea(a[0],k.convertSquareUnitsToCode(b.defaultUndefined(a[1],-1)))})},d.functions.length=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){b.pcCheck(a,1,2);a=b.autoCastFeatureToGeometry(a);if(null===a[0])return 0;if(b.isFeatureSet(a[0]))return a[0].sumLength(k.convertLinearUnitsToCode(b.defaultUndefined(a[1],-1)),!1,e.abortSignal).then(n=>{if(e.abortSignal.aborted)throw Error("Operation has been cancelled.");return n});if(b.isArray(a[0])||
b.isImmutableArray(a[0]))return c=b.autoCastArrayOfPointsToPolyline(a[0],e.spatialReference),null===c?0:h.planarLength(c,k.convertLinearUnitsToCode(b.defaultUndefined(a[1],-1)));if(!(a[0]instanceof l))throw Error("Illegal Argument");return h.planarLength(a[0],k.convertLinearUnitsToCode(b.defaultUndefined(a[1],-1)))})},d.functions.length3d=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){b.pcCheck(a,1,2);a=b.autoCastFeatureToGeometry(a);if(null===a[0])return 0;if(b.isArray(a[0])||b.isImmutableArray(a[0]))return c=
b.autoCastArrayOfPointsToPolyline(a[0],e.spatialReference),null===c?0:!0===c.hasZ?D(c,k.convertLinearUnitsToCode(b.defaultUndefined(a[1],-1))):h.planarLength(c,k.convertLinearUnitsToCode(b.defaultUndefined(a[1],-1)));if(!(a[0]instanceof l))throw Error("Illegal Argument");return!0===a[0].hasZ?D(a[0],k.convertLinearUnitsToCode(b.defaultUndefined(a[1],-1))):h.planarLength(a[0],k.convertLinearUnitsToCode(b.defaultUndefined(a[1],-1)))})},d.functions.lengthgeodetic=function(e,f){return d.standardFunctionAsync(e,
f,function(c,g,a){b.pcCheck(a,1,2);a=b.autoCastFeatureToGeometry(a);if(null===a[0])return 0;if(b.isFeatureSet(a[0]))return a[0].sumLength(k.convertLinearUnitsToCode(b.defaultUndefined(a[1],-1)),!0,e.abortSignal).then(n=>{if(e.abortSignal.aborted)throw Error("Operation has been cancelled.");return n});if(b.isArray(a[0])||b.isImmutableArray(a[0]))return c=b.autoCastArrayOfPointsToPolyline(a[0],e.spatialReference),null===c?0:h.geodesicLength(c,k.convertLinearUnitsToCode(b.defaultUndefined(a[1],-1)));
if(!(a[0]instanceof l))throw Error("Illegal Argument");return h.geodesicLength(a[0],k.convertLinearUnitsToCode(b.defaultUndefined(a[1],-1)))})},d.functions.distance=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,2,3);c=a[0];if(b.isArray(a[0])||b.isImmutableArray(a[0]))c=b.autoCastArrayOfPointsToMultiPoint(a[0],e.spatialReference);g=a[1];if(b.isArray(a[1])||b.isImmutableArray(a[1]))g=b.autoCastArrayOfPointsToMultiPoint(a[1],e.spatialReference);
if(!(c instanceof l))throw Error("Illegal Argument");if(!(g instanceof l))throw Error("Illegal Argument");return h.distance(c,g,k.convertLinearUnitsToCode(b.defaultUndefined(a[2],-1)))})},d.functions.distancegeodetic=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,2,3);c=a[0];g=a[1];if(!(c instanceof y))throw Error("Illegal Argument");if(!(g instanceof y))throw Error("Illegal Argument");const n=new v({paths:[],spatialReference:c.spatialReference});
n.addPath([c,g]);return h.geodesicLength(n,k.convertLinearUnitsToCode(b.defaultUndefined(a[2],-1)))})},d.functions.densify=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,2,3);if(null===a[0])return null;if(!(a[0]instanceof l))throw Error("Illegal Argument");c=b.toNumber(a[1]);if(isNaN(c))throw Error("Illegal Argument");if(0>=c)throw Error("Illegal Argument");return a[0]instanceof u||a[0]instanceof v?h.densify(a[0],c,k.convertLinearUnitsToCode(b.defaultUndefined(a[2],
-1))):a[0]instanceof x?h.densify(C(a[0]),c,k.convertLinearUnitsToCode(b.defaultUndefined(a[2],-1))):a[0]})},d.functions.densifygeodetic=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,2,3);if(null===a[0])return null;if(!(a[0]instanceof l))throw Error("Illegal Argument");c=b.toNumber(a[1]);if(isNaN(c))throw Error("Illegal Argument");if(0>=c)throw Error("Illegal Argument");return a[0]instanceof u||a[0]instanceof v?h.geodesicDensify(a[0],
c,k.convertLinearUnitsToCode(b.defaultUndefined(a[2],-1))):a[0]instanceof x?h.geodesicDensify(C(a[0]),c,k.convertLinearUnitsToCode(b.defaultUndefined(a[2],-1))):a[0]})},d.functions.generalize=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,2,4);if(null===a[0])return null;if(!(a[0]instanceof l))throw Error("Illegal Argument");c=b.toNumber(a[1]);if(isNaN(c))throw Error("Illegal Argument");return h.generalize(a[0],c,b.toBoolean(b.defaultUndefined(a[2],
!0)),k.convertLinearUnitsToCode(b.defaultUndefined(a[3],-1)))})},d.functions.buffer=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,2,3);if(null===a[0])return null;if(!(a[0]instanceof l))throw Error("Illegal Argument");c=b.toNumber(a[1]);if(isNaN(c))throw Error("Illegal Argument");return 0===c?k.cloneGeometry(a[0]):h.buffer(a[0],c,k.convertLinearUnitsToCode(b.defaultUndefined(a[2],-1)))})},d.functions.buffergeodetic=function(e,f){return d.standardFunctionAsync(e,
f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,2,3);if(null===a[0])return null;if(!(a[0]instanceof l))throw Error("Illegal Argument");c=b.toNumber(a[1]);if(isNaN(c))throw Error("Illegal Argument");return 0===c?k.cloneGeometry(a[0]):h.geodesicBuffer(a[0],c,k.convertLinearUnitsToCode(b.defaultUndefined(a[2],-1)))})},d.functions.offset=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,2,6);if(null===a[0])return null;if(!(a[0]instanceof
u||a[0]instanceof v))throw Error("Illegal Argument");c=b.toNumber(a[1]);if(isNaN(c))throw Error("Illegal Argument");g=b.toNumber(b.defaultUndefined(a[4],10));if(isNaN(g))throw Error("Illegal Argument");const n=b.toNumber(b.defaultUndefined(a[5],0));if(isNaN(n))throw Error("Illegal Argument");return h.offset(a[0],c,k.convertLinearUnitsToCode(b.defaultUndefined(a[2],-1)),b.toString(b.defaultUndefined(a[3],"round")).toLowerCase(),g,n)})},d.functions.rotate=function(e,f){return d.standardFunctionAsync(e,
f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,2,3);c=a[0];if(null===c)return null;if(!(c instanceof l))throw Error("Illegal Argument");c instanceof x&&(c=u.fromExtent(c));g=b.toNumber(a[1]);if(isNaN(g))throw Error("Illegal Argument");a=b.defaultUndefined(a[2],null);if(null===a)return h.rotate(c,g);if(a instanceof y)return h.rotate(c,g,a);throw Error("Illegal Argument");})},d.functions.centroid=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);
b.pcCheck(a,1,1);if(null===a[0])return null;c=a[0];if(b.isArray(a[0])||b.isImmutableArray(a[0]))c=b.autoCastArrayOfPointsToMultiPoint(a[0],e.spatialReference);if(null===c)return null;if(!(c instanceof l))throw Error("Illegal Argument");return c instanceof y?b.fixSpatialReference(k.cloneGeometry(a[0]),e.spatialReference):c instanceof u?c.centroid:c instanceof v?t.centroidPolyline(c):c instanceof A?t.centroidMultiPoint(c):c instanceof x?c.center:null})},d.functions.multiparttosinglepart=function(e,
f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,1,1);const n=[];if(null===a[0])return null;if(!(a[0]instanceof l))throw Error("Illegal Argument");return a[0]instanceof y||a[0]instanceof x?[b.fixSpatialReference(k.cloneGeometry(a[0]),e.spatialReference)]:h.simplify(a[0]).then(m=>{if(m instanceof u){var q=[],w=[];for(var p=0;p<m.rings.length;p++)if(m.isClockwise(m.rings[p])){const H=B.fromJSON({rings:[m.rings[p]],hasZ:!0===m.hasZ,hazM:!0===m.hasM,spatialReference:m.spatialReference.toJSON()});
q.push(H)}else w.push({ring:m.rings[p],pt:m.getPoint(p,0)});for(m=0;m<w.length;m++)for(p=0;p<q.length;p++)if(q[p].contains(w[m].pt)){q[p].addRing(w[m].ring);break}return q}if(m instanceof v){q=[];for(w=0;w<m.paths.length;w++)p=B.fromJSON({paths:[m.paths[w]],hasZ:!0===m.hasZ,hazM:!0===m.hasM,spatialReference:m.spatialReference.toJSON()}),q.push(p);return q}if(a[0]instanceof A){m=b.fixSpatialReference(k.cloneGeometry(a[0]),e.spatialReference);for(q=0;q<m.points.length;q++)n.push(m.getPoint(q));return n}return null})})},
d.functions.issimple=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,1,1);if(null===a[0])return!0;if(!(a[0]instanceof l))throw Error("Illegal Argument");return h.isSimple(a[0])})},d.functions.simplify=function(e,f){return d.standardFunctionAsync(e,f,function(c,g,a){a=b.autoCastFeatureToGeometry(a);b.pcCheck(a,1,1);if(null===a[0])return null;if(!(a[0]instanceof l))throw Error("Illegal Argument");return h.simplify(a[0])})})};Object.defineProperty(z,
"__esModule",{value:!0})});