// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define(["exports"],function(ma){var G={exports:{}};(function(A){(function(h){h=h();void 0!==h&&(A.exports=h)})(function(){return{load:function(h){function H(a){return b.locateFile?b.locateFile(a,n):n+a}function q(a,c,d){var e=c+d;for(d=c;a[d]&&!(d>=e);)++d;if(16<d-c&&a.subarray&&Y)return Y.decode(a.subarray(c,d));for(e="";c<d;){var f=a[c++];if(f&128){var g=a[c++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var k=a[c++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[c++]&
63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}function t(a,c){0<a%c&&(a+=c-a%c);return a}function B(a){Z=a;b.HEAP8=new Int8Array(a);b.HEAP16=new Int16Array(a);b.HEAP32=I=new Int32Array(a);b.HEAPU8=J=new Uint8Array(a);b.HEAPU16=new Uint16Array(a);b.HEAPU32=new Uint32Array(a);b.HEAPF32=new Float32Array(a);b.HEAPF64=new Float64Array(a)}function K(a){if(b.onAbort)b.onAbort(a);a+="";C(a);aa=!0;throw new WebAssembly.RuntimeError("abort("+
a+"). Build with -s ASSERTIONS\x3d1 for more info.");}function ba(a){try{if(a==l&&L)return new Uint8Array(L);if(S)return S(a);throw"both async and sync fetching of the wasm failed";}catch(c){K(c)}}function na(){if(!L&&(ca||M)){if("function"===typeof fetch&&!l.startsWith("file://"))return fetch(l,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+l+"'";return a.arrayBuffer()}).catch(function(){return ba(l)});if(T)return new Promise(function(a,c){T(l,
function(d){a(new Uint8Array(d))},c)})}return Promise.resolve().then(function(){return ba(l)})}function U(a){for(;0<a.length;){var c=a.shift();if("function"==typeof c)c(b);else{var d=c.func;"number"===typeof d?void 0===c.arg?p.get(d)():p.get(d)(c.arg):d(void 0===c.arg?null:c.arg)}}}function V(a){function c(){if(!P&&(P=!0,b.calledRun=!0,!aa)){U(da);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;)ea.unshift(b.postRun.shift());
U(ea)}}if(!(0<u)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)fa.unshift(b.preRun.shift());U(fa);0<u||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);c()},1)):c())}}h=h.locateFile;const D={};var b="undefined"!==typeof b?b:{};const ha=(()=>{let a;return{resolve:c=>a(c),promise:new Promise(c=>a=c)}})();b.locateFile=h;b.onRuntimeInitialized=()=>{ha.resolve(D)};D.Module=b;D.whenLoaded=()=>ha.promise;h={};for(var v in b)b.hasOwnProperty(v)&&
(h[v]=b[v]);var ca="object"===typeof window,M="function"===typeof importScripts,n="",E,F;if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node){n=M?require("path").dirname(n)+"/":__dirname+"/";var ia=function(a,c){E||(E=require("fs"));F||(F=require("path"));a=F.normalize(a);return E.readFileSync(a,c?null:"utf8")};var S=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||K("Assertion failed: undefined");return a};var T=function(a,c,d){E||
(E=require("fs"));F||(F=require("path"));a=F.normalize(a);E.readFile(a,function(e,f){e?d(e):c(f.buffer)})};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);A.exports=b;process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",K);b.inspect=function(){return"[Emscripten Module object]"}}else if(ca||M)M?n=self.location.href:"undefined"!==typeof document&&document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?n.substr(0,
n.lastIndexOf("/")+1):"",ia=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},M&&(S=function(a){var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),T=function(a,c,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?c(e.response):d()};e.onerror=d;e.send(null)};var oa=b.print||console.log.bind(console),C=b.printErr||
console.warn.bind(console);for(v in h)h.hasOwnProperty(v)&&(b[v]=h[v]);h=null;var ja=0,L;b.wasmBinary&&(L=b.wasmBinary);b.noExitRuntime||!0;"object"!==typeof WebAssembly&&K("no native wasm support detected");var Q,aa=!1,Y="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0,Z,J,I;b.INITIAL_MEMORY||16777216;var p,fa=[],da=[],ea=[],u=0,N=null;b.preloadedImages={};b.preloadedAudios={};var l="libtess.wasm";l.startsWith("data:application/octet-stream;base64,")||(l=H(l));var O={mappings:{},buffers:[null,
[],[]],printChar:function(a,c){var d=O.buffers[a];0===c||10===c?((1===a?oa:C)(q(d,0)),d.length=0):d.push(c)},varargs:void 0,get:function(){O.varargs+=4;return I[O.varargs-4>>2]},getStr:function(a){return a?q(J,a,void 0):""},get64:function(a,c){return a}},pa={h:function(){throw"longjmp";},l:function(a,c,d){J.copyWithin(a,c,c+d)},g:function(a){var c=J.length;a>>>=0;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var e=c*(1+.2/d);e=Math.min(e,a+100663296);e=Math.min(2147483648,t(Math.max(a,e),65536));
a:{try{Q.grow(e-Z.byteLength+65535>>>16);B(Q.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},f:function(a,c,d,e){for(var f=0,g=0;g<d;g++){for(var k=I[c+8*g>>2],ka=I[c+(8*g+4)>>2],W=0;W<ka;W++)O.printChar(a,J[k+W]);f+=ka}I[e>>2]=f;return 0},b:function(){return ja},k:function(a){var c=w();try{return p.get(a)()}catch(d){x(c);if(d!==d+0&&"longjmp"!==d)throw d;y(1,0)}},d:function(a,c){var d=w();try{return p.get(a)(c)}catch(e){x(d);if(e!==e+0&&"longjmp"!==e)throw e;y(1,0)}},j:function(a,
c,d){var e=w();try{return p.get(a)(c,d)}catch(f){x(e);if(f!==f+0&&"longjmp"!==f)throw f;y(1,0)}},i:function(a,c,d,e){var f=w();try{return p.get(a)(c,d,e)}catch(g){x(f);if(g!==g+0&&"longjmp"!==g)throw g;y(1,0)}},e:function(a,c){var d=w();try{p.get(a)(c)}catch(e){x(d);if(e!==e+0&&"longjmp"!==e)throw e;y(1,0)}},c:function(a,c,d){var e=w();try{p.get(a)(c,d)}catch(f){x(e);if(f!==f+0&&"longjmp"!==f)throw f;y(1,0)}},a:function(a){ja=a}};(function(){function a(f,g){b.asm=f.exports;Q=b.asm.m;B(Q.buffer);p=
b.asm.q;da.unshift(b.asm.n);u--;b.monitorRunDependencies&&b.monitorRunDependencies(u);0==u&&N&&(f=N,N=null,f())}function c(f){a(f.instance)}function d(f){return na().then(function(g){return WebAssembly.instantiate(g,e)}).then(f,function(g){C("failed to asynchronously prepare wasm: "+g);K(g)})}var e={a:pa};u++;b.monitorRunDependencies&&b.monitorRunDependencies(u);if(b.instantiateWasm)try{return b.instantiateWasm(e,a)}catch(f){return C("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return L||
"function"!==typeof WebAssembly.instantiateStreaming||l.startsWith("data:application/octet-stream;base64,")||l.startsWith("file://")||"function"!==typeof fetch?d(c):fetch(l,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(c,function(g){C("wasm streaming compile failed: "+g);C("falling back to ArrayBuffer instantiation");return d(c)})})})();return{}})();b.___wasm_call_ctors=function(){return(b.___wasm_call_ctors=b.asm.n).apply(null,arguments)};b._malloc=
function(){return(b._malloc=b.asm.o).apply(null,arguments)};b._free=function(){return(b._free=b.asm.p).apply(null,arguments)};b._triangulate=function(){return(b._triangulate=b.asm.r).apply(null,arguments)};var w=b.stackSave=function(){return(w=b.stackSave=b.asm.s).apply(null,arguments)},x=b.stackRestore=function(){return(x=b.stackRestore=b.asm.t).apply(null,arguments)},y=b._setThrew=function(){return(y=b._setThrew=b.asm.u).apply(null,arguments)},P;N=function c(){P||V();P||(N=c)};b.run=V;if(b.preInit)for("function"==
typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();V();let X=null,r=null,z=null,R=null;const m=D.Module;let la=0;D.triangulate=(c,d,e)=>{X||(X=m._triangulate);var f=m.HEAPF32;const g=m.HEAP32.BYTES_PER_ELEMENT;var k=f.BYTES_PER_ELEMENT;e>la&&(la=e,z&&(m._free(z),z=0),r&&(m._free(r),r=0));z||(z=m._malloc(e*k));R||(R=m._malloc(1E3*g));r||(r=m._malloc(e*k));f=m.HEAPF32;f.set(c,z/k);m.HEAP32.set(d,R/g);c=X(z,R,d.length,2,r);f=m.HEAPF32;f=f.slice(r/k,r/k+2*c);k={};k.buffer=
f;k.vertexCount=c;return k};return D.whenLoaded()}}})})(G);G=Object.freeze(function(A,h){for(var H=0;H<h.length;H++){const q=h[H];if("string"!==typeof q&&!Array.isArray(q))for(const t in q)if("default"!==t&&!(t in A)){const B=Object.getOwnPropertyDescriptor(q,t);B&&Object.defineProperty(A,t,B.get?B:{enumerable:!0,get:()=>q[t]})}}return Object.freeze(A)}({__proto__:null,default:G.exports},[G.exports]));ma.libtess=G});