// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/arrayUtils ../../../core/Error ../../../core/maybe ../../../core/watchUtils ../../../core/Logger ../../../core/accessorSupport/ensureType ../../../core/has ../../../core/accessorSupport/set ../../../core/accessorSupport/decorators/subclass ../../../layers/support/fieldUtils ../../statistics/support/predominanceUtils ../../statistics/support/utils ../../statistics/support/WorkerClient ./FeatureLayerAdapter ./support/utils ../../../statistics/utils".split(" "),
function(l,x,y,h,u,p,r,G,H,I,z,A,B,C,D,E,q,v){r=function(w){function t(b){return w.call(this,b)||this}l._inheritsLoose(t,w);var g=t.prototype;g._waitForLayerViewUpdate=function(){var b=l._asyncToGenerator(function*(a){if(!a)throw new h("ogc-feature-layer-adapter:insufficient-data","layerView is required to fetch the features");yield p.whenFalseOnce(a,"updating")});return function(a){return b.apply(this,arguments)}}();g._summaryStatsFromClientQuery=function(){var b=l._asyncToGenerator(function*(a,
c){const {signal:e,view:d}=a;if(!d)throw new h("ogc-feature-layer-adapter:insufficient-data","view is required to fetch the features from layerView");a=this._getSummaryStatsQuery(a,c);const f=yield d.whenLayerView(this.layer);yield p.whenFalseOnce(f,"updating");a=yield f.queryFeatures(a,{signal:e});c=q.getSummaryStatisticsFromFeatureSet(a,c);return v.processSummaryStatisticsResult(c)});return function(a,c){return b.apply(this,arguments)}}();g._uvFromClientQuery=function(){var b=l._asyncToGenerator(function*(a,
c){const {signal:e,view:d}=a;if(!d)throw new h("ogc-feature-layer-adapter:insufficient-data","view is required to fetch the features from layerView");var f=this._getUVQuery(a);const k=yield d.whenLayerView(this.layer);yield p.whenFalseOnce(k,"updating");f=yield k.queryFeatures(f,{signal:e});f=yield q.getUniqueValuesFromFeatureSet(f,this,a.field,a.view,null,e);return v.createUVResult(f,c,a.returnAllCodedValues)});return function(a,c){return b.apply(this,arguments)}}();g.summaryStatistics=function(b){const {field:a,
valueExpression:c,sqlExpression:e,features:d,view:f}=b,k=a?this.getField(a):null,n=A.isDateField(k),m=!!c,F="3d"===(null==f?void 0:f.type);if(e&&!this.supportsSQLExpression)throw new h("ogc-feature-layer-adapter:not-supported","Layer does not support standardized SQL expression for queries");return m||d||F?this._summaryStatsFromMemory(b,k):this._summaryStatsFromClientQuery(b,n)};g.uniqueValues=function(b){const {field:a,valueExpression:c,sqlExpression:e,features:d,view:f}=b,k=(a?this.getField(a):
null)&&this.getFieldDomain(a),n=!!c,m="3d"===(null==f?void 0:f.type);if(e&&!this.supportsSQLExpression)throw new h("ogc-feature-layer-adapter:not-supported","Layer does not support standardized SQL expression for queries");return n||d||m?this._uvFromMemory(b,k):this._uvFromClientQuery(b,k)};g.histogram=function(b){const {features:a,valueExpression:c,normalizationType:e,sqlExpression:d}=b,f=a||!!c;if(d&&!this.supportsSQLExpression)throw new h("ogc-feature-layer-adapter:not-supported","Layer does not support standardized SQL expression for queries");
return f||e?this._histogramFromMemory(b):this._histogramForField(b)};g.classBreaks=function(b){return!1!==b.analyzeData?this._classBreaksFromMemory(b):this._classBreaksFromInterpolation(b)};g.queryFeatureCount=function(){var b=l._asyncToGenerator(function*(a){const {whereClause:c,view:e,signal:d}=a;if(!e)throw new h("ogc-feature-layer-adapter:insufficient-data","view is required to fetch the features from layerView");a=this.layer.createQuery();a.where=C.mergeWhereClauses(a.where,c);const f=yield e.whenLayerView(this.layer);
yield p.whenFalseOnce(f,"updating");return f.queryFeatureCount(a,{signal:d})});return function(a){return b.apply(this,arguments)}}();g.generateRenderer=function(b,a){throw new h("ogc-feature-layer-adapter:not-supported","OGCFeatureLayer does not support generateRenderer operation");};g.predominantCategories=function(){var b=l._asyncToGenerator(function*(a){const {fields:c,view:e,signal:d}=a;a=B.getArcadeForPredominantCategory(c);a=yield this._uvFromMemory({valueExpression:a,view:e,signal:d});return q.getPredominantCategoriesFromUVInfos(a.uniqueValueInfos,
c)});return function(a){return b.apply(this,arguments)}}();g.getSampleFeatures=function(){var b=l._asyncToGenerator(function*(a,c){const {view:e,sampleSize:d,requiredFields:f,returnGeometry:k,signal:n}=a,m=this.layer.createQuery();m.outSpatialReference=a.spatialReference||e&&e.spatialReference;m.returnGeometry=!!k;m.outFields=f;if(!e)throw new h("ogc-feature-layer-adapter:not-supported","view is required to get sample features for OGCFeatureLayer");a=yield e.whenLayerView(this.layer);if((yield q.getMissingFields(this,
f,a)).length)throw new h("ogc-feature-layer-adapter:not-supported","Required fields need to be passed in the outFields for OGCFeatureLayer");c=yield this._fetchFeaturesFromMemory(a,m,n,c);return y.pickRandom(c,0<d&&d<=c.length?d:c.length,1)});return function(a,c){return b.apply(this,arguments)}}();g.load=function(b){var a=this;const c=this.layer.load(b).then(function(){var e=l._asyncToGenerator(function*(d){a.geometryType=d.geometryType;a.objectIdField=d.objectIdField;a.supportsSQLExpression=d.get("capabilities.query.supportsSqlExpression");
a.minScale=d.minScale;a.maxScale=d.maxScale;a.fullExtent=d.fullExtent;a.workerClient=D.WorkerClient.getInstance();yield a.workerClient.open(u.unwrap(u.unwrap(b).signal))});return function(d){return e.apply(this,arguments)}}());this.addResolvingPromise(c);return Promise.resolve(this)};return t}(E);return r=x.__decorate([z.subclass("esri.smartMapping.support.adapters.OGCFeatureLayerAdapter")],r)});