// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ./assert ./error-handler ./messages ./nodes ./scanner ./syntax ./token".split(" "),function(q,p,u,k,f,v,r,w){let y=function(){function t(a,b={},c){this.config={range:"boolean"===typeof b.range&&b.range,loc:"boolean"===typeof b.loc&&b.loc,source:null,tokens:"boolean"===typeof b.tokens&&b.tokens,comment:"boolean"===typeof b.comment&&b.comment,tolerant:"boolean"===typeof b.tolerant&&b.tolerant,globalReturn:!!b.globalReturn};this.config.loc&&b.source&&null!==b.source&&(this.config.source=
String(b.source));this.delegate=c;this.errorHandler=new u.ErrorHandler;this.errorHandler.tolerant=this.config.tolerant;this.scanner=new v.Scanner(a,this.errorHandler);this.scanner.trackComment=this.config.comment;this.operatorPrecedence={")":0,";":0,",":0,"\x3d":0,"]":0,"||":1,"\x26\x26":2,"|":3,"^":4,"\x26":5,"\x3d\x3d":6,"!\x3d":6,"\x3d\x3d\x3d":6,"!\x3d\x3d":6,"\x3c":7,"\x3e":7,"\x3c\x3d":7,"\x3e\x3d":7,"\x3c\x3c":8,"\x3e\x3e":8,"\x3e\x3e\x3e":8,"+":9,"-":9,"*":11,"/":11,"%":11};this.lookahead=
{type:2,value:"",lineNumber:this.scanner.lineNumber,lineStart:0,start:0,end:0};this.hasLineTerminator=!1;this.context={allowIn:!0,firstCoverInitializedNameError:null,isAssignmentTarget:!1,isBindingElement:!1,inFunctionBody:!1,inIteration:!1,curlyParsing:"asObject"};this.tokens=[];this.startMarker={index:0,line:this.scanner.lineNumber,column:0};this.lastMarker={index:0,line:this.scanner.lineNumber,column:0};this.nextToken();this.lastMarker={index:this.scanner.index,line:this.scanner.lineNumber,column:this.scanner.index-
this.scanner.lineStart}}var d=t.prototype;d.tolerateError=function(a,...b){const c=b.slice();a=a.replace(/%(\d)/g,(e,g)=>{p.assert(g<c.length,"Message reference must be in range");return c[g]});this.errorHandler.tolerateError(this.lastMarker.index,this.scanner.lineNumber,this.lastMarker.column+1,a)};d.unexpectedTokenError=function(a,b){let c=b||k.Messages.UnexpectedToken;a?(b||(c=2===a.type?k.Messages.UnexpectedEOS:3===a.type?k.Messages.UnexpectedIdentifier:6===a.type?k.Messages.UnexpectedNumber:
8===a.type?k.Messages.UnexpectedString:10===a.type?k.Messages.UnexpectedTemplate:k.Messages.UnexpectedToken),b=a.value.toString()):b="ILLEGAL";c=c.replace("%0",b);return a&&"number"===typeof a.lineNumber?this.errorHandler.createError(a.start,a.lineNumber,a.start-(this.lastMarker.index-this.lastMarker.column)+1,c):this.errorHandler.createError(this.lastMarker.index,this.lastMarker.line,this.lastMarker.column+1,c)};d.throwUnexpectedToken=function(a,b){throw this.unexpectedTokenError(a,b);};d.tolerateUnexpectedToken=
function(a,b){this.errorHandler.tolerate(this.unexpectedTokenError(a,b))};d.collectComments=function(){if(this.config.comment){const a=this.scanner.scanComments();if(a&&0<a.length&&this.delegate)for(let b=0;b<a.length;++b){const c=a[b],e=new f.Comment(c.multiLine?"Block":"Line",this.scanner.source.slice(c.slice[0],c.slice[1]));this.config.range&&(e.range=c.range);this.config.loc&&(e.loc=c.loc);this.delegate(e,{start:{line:c.loc.start.line,column:c.loc.start.column,offset:c.range[0]},end:{line:c.loc.end.line,
column:c.loc.end.column,offset:c.range[1]}})}}else this.scanner.scanComments()};d.peekAhead=function(a){const b=this.scanner.saveState();a.call(this,()=>{this.scanner.scanComments();return this.scanner.lex()});this.scanner.restoreState(b)};d.getTokenRaw=function(a){return this.scanner.source.slice(a.start,a.end)};d.convertToken=function(a){const b={type:w.TokenName[a.type],value:this.getTokenRaw(a)};this.config.range&&(b.range=[a.start,a.end]);this.config.loc&&(b.loc={start:{line:this.startMarker.line,
column:this.startMarker.column},end:{line:this.scanner.lineNumber,column:this.scanner.index-this.scanner.lineStart}});9===a.type&&(b.regex={pattern:a.pattern,flags:a.flags});return b};d.nextToken=function(){const a=this.lookahead;this.lastMarker.index=this.scanner.index;this.lastMarker.line=this.scanner.lineNumber;this.lastMarker.column=this.scanner.index-this.scanner.lineStart;this.collectComments();this.scanner.index!==this.startMarker.index&&(this.startMarker.index=this.scanner.index,this.startMarker.line=
this.scanner.lineNumber,this.startMarker.column=this.scanner.index-this.scanner.lineStart);const b=this.scanner.lex();this.hasLineTerminator=a.lineNumber!==b.lineNumber;this.lookahead=b;this.config.tokens&&2!==b.type&&this.tokens.push(this.convertToken(b));return a};d.createNode=function(){return{index:this.startMarker.index,line:this.startMarker.line,column:this.startMarker.column}};d.startNode=function(a,b=0){let c=a.start-a.lineStart,e=a.lineNumber;0>c&&(c+=b,e--);return{index:a.start,line:e,column:c}};
d.finalize=function(a,b){this.config.range&&(b.range=[a.index,this.lastMarker.index]);this.config.loc&&(b.loc={start:{line:a.line,column:a.column},end:{line:this.lastMarker.line,column:this.lastMarker.column}},this.config.source&&(b.loc.source=this.config.source));this.delegate&&this.delegate(b,{start:{line:a.line,column:a.column,offset:a.index},end:{line:this.lastMarker.line,column:this.lastMarker.column,offset:this.lastMarker.index}});return b};d.expect=function(a){const b=this.nextToken();7===
b.type&&b.value===a||this.throwUnexpectedToken(b)};d.expectCommaSeparator=function(){if(this.config.tolerant){const a=this.lookahead;7===a.type&&","===a.value?this.nextToken():7===a.type&&";"===a.value?(this.nextToken(),this.tolerateUnexpectedToken(a)):this.tolerateUnexpectedToken(a,k.Messages.UnexpectedToken)}else this.expect(",")};d.expectKeyword=function(a){const b=this.nextToken();4===b.type&&b.value.toString().toLowerCase()===a.toLowerCase()||this.throwUnexpectedToken(b)};d.match=function(a){return 7===
this.lookahead.type&&this.lookahead.value===a};d.matchKeyword=function(a){return 4===this.lookahead.type&&this.lookahead.value.toLowerCase()===a.toLowerCase()};d.matchContextualKeyword=function(a){return 3===this.lookahead.type&&this.lookahead.value===a};d.matchAssign=function(){return 7!==this.lookahead.type?!1:f.AssignmentOperators.includes(this.lookahead.value)};d.isolateCoverGrammar=function(a){const b=this.context.isBindingElement,c=this.context.isAssignmentTarget,e=this.context.firstCoverInitializedNameError;
this.context.isBindingElement=!0;this.context.isAssignmentTarget=!0;this.context.firstCoverInitializedNameError=null;a=a.call(this);null!==this.context.firstCoverInitializedNameError&&this.throwUnexpectedToken(this.context.firstCoverInitializedNameError);this.context.isBindingElement=b;this.context.isAssignmentTarget=c;this.context.firstCoverInitializedNameError=e;return a};d.inheritCoverGrammar=function(a){const b=this.context.isBindingElement,c=this.context.isAssignmentTarget,e=this.context.firstCoverInitializedNameError;
this.context.isBindingElement=!0;this.context.isAssignmentTarget=!0;this.context.firstCoverInitializedNameError=null;a=a.call(this);this.context.isBindingElement=this.context.isBindingElement&&b;this.context.isAssignmentTarget=this.context.isAssignmentTarget&&c;this.context.firstCoverInitializedNameError=e||this.context.firstCoverInitializedNameError;return a};d.consumeSemicolon=function(){this.match(";")?this.nextToken():this.hasLineTerminator||(2===this.lookahead.type||this.match("}")||this.throwUnexpectedToken(this.lookahead),
this.lastMarker.index=this.startMarker.index,this.lastMarker.line=this.startMarker.line,this.lastMarker.column=this.startMarker.column)};d.parsePrimaryExpression=function(){var a=this.createNode();let b,c;switch(this.lookahead.type){case 3:a=this.finalize(a,new f.Identifier(this.nextToken().value));break;case 6:case 8:this.context.isAssignmentTarget=!1;this.context.isBindingElement=!1;b=this.nextToken();c=this.getTokenRaw(b);a=this.finalize(a,new f.Literal(b.value,c));break;case 1:this.context.isAssignmentTarget=
!1;this.context.isBindingElement=!1;b=this.nextToken();c=this.getTokenRaw(b);a=this.finalize(a,new f.Literal("true"===b.value.toString().toLowerCase(),c));break;case 5:this.context.isAssignmentTarget=!1;this.context.isBindingElement=!1;b=this.nextToken();c=this.getTokenRaw(b);a=this.finalize(a,new f.Literal(null,c));break;case 10:a=this.parseTemplateLiteral();break;case 7:switch(this.lookahead.value){case "(":this.context.isBindingElement=!1;a=this.inheritCoverGrammar(this.parseGroupExpression);break;
case "[":a=this.inheritCoverGrammar(this.parseArrayInitializer);break;case "{":a=this.inheritCoverGrammar(this.parseObjectInitializer);break;default:a=this.throwUnexpectedToken(this.nextToken())}break;case 4:this.context.isAssignmentTarget=!1;this.context.isBindingElement=!1;a=this.throwUnexpectedToken(this.nextToken());break;default:a=this.throwUnexpectedToken(this.nextToken())}return a};d.parseArrayInitializer=function(){const a=this.createNode(),b=[];for(this.expect("[");!this.match("]");)this.match(",")?
(this.nextToken(),b.push(null)):(b.push(this.inheritCoverGrammar(this.parseAssignmentExpression)),this.match("]")||this.expect(","));this.expect("]");return this.finalize(a,new f.ArrayExpression(b))};d.parseObjectPropertyKey=function(){var a=this.createNode();const b=this.nextToken();switch(b.type){case 8:case 6:a=this.finalize(a,new f.Literal(b.value,this.getTokenRaw(b)));break;case 3:case 1:case 5:case 4:a=this.finalize(a,new f.Identifier(b.value));break;default:a=this.throwUnexpectedToken(b)}return a};
d.parseObjectProperty=function(){const a=this.createNode();var b=this.lookahead;let c=!1,e=!1;var g=null;3===b.type?(g=b.value,this.nextToken(),c=this.match("["),g=this.finalize(a,new f.Identifier(g))):this.match("*")?this.nextToken():(c=this.match("["),g=this.parseObjectPropertyKey());g||this.throwUnexpectedToken(this.lookahead);let h=null;this.match(":")?(this.nextToken(),h=this.inheritCoverGrammar(this.parseAssignmentExpression)):3===b.type?(b=this.finalize(a,new f.Identifier(b.value)),e=!0,h=
b):this.throwUnexpectedToken(this.nextToken());return this.finalize(a,new f.Property("init",g,c,h,!1,e))};d.parseObjectInitializer=function(){const a=this.createNode();this.expect("{");const b=[];for(;!this.match("}");)b.push(this.parseObjectProperty()),this.match("}")||this.expectCommaSeparator();this.expect("}");return this.finalize(a,new f.ObjectExpression(b))};d.parseTemplateHead=function(){p.assert(this.lookahead.head,"Template literal must start with a template head");const a=this.createNode(),
b=this.nextToken();return this.finalize(a,new f.TemplateElement({raw:b.value,cooked:b.cooked},b.tail))};d.parseTemplateElement=function(){10!==this.lookahead.type&&this.throwUnexpectedToken();const a=this.createNode(),b=this.nextToken();return this.finalize(a,new f.TemplateElement({raw:b.value,cooked:b.cooked},b.tail))};d.parseTemplateLiteral=function(){const a=this.createNode(),b=[],c=[];let e=this.parseTemplateHead();for(c.push(e);!e.tail;)b.push(this.parseExpression()),e=this.parseTemplateElement(),
c.push(e);return this.finalize(a,new f.TemplateLiteral(c,b))};d.parseGroupExpression=function(){this.expect("(");this.context.isBindingElement=!0;const a=this.inheritCoverGrammar(this.parseAssignmentExpression);this.expect(")");this.context.isBindingElement=!1;return a};d.parseArguments=function(){this.expect("(");const a=[];if(!this.match(")"))for(;;){const b=this.isolateCoverGrammar(this.parseAssignmentExpression);a.push(b);if(this.match(")"))break;this.expectCommaSeparator();if(this.match(")"))break}this.expect(")");
return a};d.isIdentifierName=function(a){return 3===a.type||4===a.type||1===a.type||5===a.type};d.parseIdentifierName=function(){const a=this.createNode(),b=this.nextToken();this.isIdentifierName(b)||this.throwUnexpectedToken(b);return this.finalize(a,new f.Identifier(b.value))};d.parseLeftHandSideExpressionAllowCall=function(){const a=this.lookahead,b=this.context.allowIn;this.context.allowIn=!0;let c=this.inheritCoverGrammar(this.parsePrimaryExpression);for(;;)if(this.match("(")){this.context.isBindingElement=
!1;this.context.isAssignmentTarget=!1;var e=this.parseArguments();c=this.finalize(this.startNode(a),new f.CallExpression(c,e))}else if(this.match("["))this.context.isBindingElement=!1,this.context.isAssignmentTarget=!0,this.expect("["),e=this.isolateCoverGrammar(this.parseExpression),this.expect("]"),c=this.finalize(this.startNode(a),new f.ComputedMemberExpression(c,e));else if(this.match("."))this.context.isBindingElement=!1,this.context.isAssignmentTarget=!0,this.expect("."),e=this.parseIdentifierName(),
c=this.finalize(this.startNode(a),new f.StaticMemberExpression(c,e));else break;this.context.allowIn=b;return c};d.parseLeftHandSideExpression=function(){p.assert(this.context.allowIn,"callee of new expression always allow in keyword.");const a=this.startNode(this.lookahead);let b=this.inheritCoverGrammar(this.parsePrimaryExpression);for(;;)if(this.match("[")){this.context.isBindingElement=!1;this.context.isAssignmentTarget=!0;this.expect("[");var c=this.isolateCoverGrammar(this.parseExpression);
this.expect("]");b=this.finalize(a,new f.ComputedMemberExpression(b,c))}else if(this.match("."))this.context.isBindingElement=!1,this.context.isAssignmentTarget=!0,this.expect("."),c=this.parseIdentifierName(),b=this.finalize(a,new f.StaticMemberExpression(b,c));else break;return b};d.parseUpdateExpression=function(){let a;var b=this.lookahead;if(this.match("++")||this.match("--")){b=this.startNode(b);var c=this.nextToken();a=this.inheritCoverGrammar(this.parseUnaryExpression);this.context.isAssignmentTarget||
this.tolerateError(k.Messages.InvalidLHSInAssignment);a=this.finalize(b,new f.UpdateExpression(c.value,a,!0));this.context.isAssignmentTarget=!1;this.context.isBindingElement=!1}else a=this.inheritCoverGrammar(this.parseLeftHandSideExpressionAllowCall),this.hasLineTerminator||7!==this.lookahead.type||!this.match("++")&&!this.match("--")||(this.context.isAssignmentTarget||this.tolerateError(k.Messages.InvalidLHSInAssignment),this.context.isAssignmentTarget=!1,this.context.isBindingElement=!1,c=this.nextToken().value,
a=this.finalize(this.startNode(b),new f.UpdateExpression(c,a,!1)));return a};d.parseUnaryExpression=function(){let a;if(this.match("+")||this.match("-")||this.match("~")||this.match("!")){const b=this.startNode(this.lookahead),c=this.nextToken();a=this.inheritCoverGrammar(this.parseUnaryExpression);a=this.finalize(b,new f.UnaryExpression(c.value,a));this.context.isAssignmentTarget=!1;this.context.isBindingElement=!1}else a=this.parseUpdateExpression();return a};d.binaryPrecedence=function(a){const b=
a.value;return 7===a.type?this.operatorPrecedence[b]||0:4===a.type?this.context.allowIn&&"in"===b?12:0:0};d.parseBinaryExpression=function(){var a=this.lookahead,b=this.inheritCoverGrammar(this.parseUnaryExpression),c=this.lookahead,e=this.binaryPrecedence(c);if(0<e){this.nextToken();this.context.isAssignmentTarget=!1;this.context.isBindingElement=!1;a=[a,this.lookahead];var g=this.inheritCoverGrammar(this.parseUnaryExpression);c=[b,c.value,g];for(var h=[e];;){e=this.binaryPrecedence(this.lookahead);
if(0>=e)break;for(;2<c.length&&e<=h[h.length-1];){g=c.pop();const n=c.pop();h.pop();b=c.pop();a.pop();var l=a[a.length-1];l=this.startNode(l,l.lineStart);c.push(this.finalize(l,new f.BinaryExpression(n,b,g)))}c.push(this.nextToken().value);h.push(e);a.push(this.lookahead);c.push(this.inheritCoverGrammar(this.parseUnaryExpression))}e=c.length-1;b=c[e];for(h=a.pop();1<e;){g=a.pop();if(!g)break;h=this.startNode(g,h&&h.lineStart);b=this.finalize(h,new f.BinaryExpression(c[e-1],c[e-2],b));e-=2;h=g}}return b};
d.parseAssignmentExpression=function(){const a=this.lookahead;var b=a;let c=this.inheritCoverGrammar(this.parseBinaryExpression);if(this.matchAssign()){this.context.isAssignmentTarget||this.tolerateError(k.Messages.InvalidLHSInAssignment);this.match("\x3d")||(this.context.isAssignmentTarget=!1,this.context.isBindingElement=!1);b=this.nextToken();b=b.value;const e=this.isolateCoverGrammar(this.parseAssignmentExpression);c=this.finalize(this.startNode(a),new f.AssignmentExpression(b,c,e));this.context.firstCoverInitializedNameError=
null}return c};d.parseExpression=function(){return this.isolateCoverGrammar(this.parseAssignmentExpression)};d.parseStatementListItem=function(){let a;this.context.isAssignmentTarget=!0;this.context.isBindingElement=!0;if(4===this.lookahead.type)switch(this.lookahead.value){case "function":a=this.parseFunctionDeclaration();break;default:a=this.parseStatement()}else a=this.parseStatement();return a};d.parseBlock=function(){const a=this.createNode();this.expect("{");const b=[];for(;!this.match("}");)b.push(this.parseStatementListItem());
this.expect("}");return this.finalize(a,new f.BlockStatement(b))};d.parseObjectStatement=function(){const a=this.createNode(),b=this.parseObjectInitializer();return this.finalize(a,new f.ExpressionStatement(b))};d.parseBlockOrObjectStatement=function(){let a="asObject"===this.context.curlyParsing;"asObjectOrBlock"===this.context.curlyParsing&&this.peekAhead(b=>{let c=b();if(3===c.type||8===c.type)c=b(),7===c.type&&":"===c.value&&(a=!0)});return a?this.parseObjectStatement():this.parseBlock()};d.parseVariableIdentifier=
function(){const a=this.createNode(),b=this.nextToken();3!==b.type&&this.throwUnexpectedToken(b,k.Messages.IdentiferExpected);return this.finalize(a,new f.Identifier(b.value))};d.parseVariableDeclaration=function(a){const b=this.createNode(),c=this.parseVariableIdentifier();let e=null;this.match("\x3d")?(this.nextToken(),e=this.isolateCoverGrammar(this.parseAssignmentExpression)):c.type===r.Syntax.Identifier||a.inFor||this.expect("\x3d");return this.finalize(b,new f.VariableDeclarator(c,e))};d.parseVariableDeclarationList=
function(a){const b=[this.parseVariableDeclaration(a)];for(;this.match(",");)this.nextToken(),b.push(this.parseVariableDeclaration(a));return b};d.parseVariableStatement=function(){const a=this.createNode();this.expectKeyword("var");const b=this.parseVariableDeclarationList({inFor:!1});this.consumeSemicolon();return this.finalize(a,new f.VariableDeclaration(b,"var"))};d.parseEmptyStatement=function(){const a=this.createNode();this.expect(";");return this.finalize(a,new f.EmptyStatement)};d.parseExpressionStatement=
function(){const a=this.createNode(),b=this.parseExpression();this.consumeSemicolon();return this.finalize(a,new f.ExpressionStatement(b))};d.parseIfClause=function(){const a=this.context.curlyParsing;this.context.curlyParsing="asObjectOrBlock";const b=this.parseStatement();this.context.curlyParsing=a;return b};d.parseIfStatement=function(){const a=this.createNode();let b,c=null;this.expectKeyword("if");this.expect("(");const e=this.parseExpression();!this.match(")")&&this.config.tolerant?(this.tolerateUnexpectedToken(this.nextToken()),
b=this.finalize(this.createNode(),new f.EmptyStatement)):(this.expect(")"),b=this.parseIfClause(),this.matchKeyword("else")&&(this.nextToken(),c=this.parseIfClause()));return this.finalize(a,new f.IfStatement(e,b,c))};d.parseForStatement=function(){let a=null,b=null,c=null,e=null,g=null;const h=this.createNode();this.expectKeyword("for");this.expect("(");if(this.match(";"))this.nextToken();else if(this.matchKeyword("var")){var l=this.createNode();this.nextToken();var n=this.context.allowIn;this.context.allowIn=
!1;var m=this.parseVariableDeclarationList({inFor:!0});this.context.allowIn=n;1===m.length&&this.matchKeyword("in")?(m[0].init&&this.tolerateError(k.Messages.ForInOfLoopInitializer,"for-in"),e=this.finalize(l,new f.VariableDeclaration(m,"var")),this.nextToken(),g=this.parseExpression()):(a=this.finalize(l,new f.VariableDeclaration(m,"var")),this.expect(";"))}else{l=this.context.isBindingElement;n=this.context.isAssignmentTarget;m=this.context.firstCoverInitializedNameError;const x=this.context.allowIn;
this.context.allowIn=!1;a=this.inheritCoverGrammar(this.parseAssignmentExpression);this.context.allowIn=x;this.matchKeyword("in")?(this.context.isAssignmentTarget&&a.type!==r.Syntax.AssignmentExpression||this.tolerateError(k.Messages.InvalidLHSInForIn),this.nextToken(),e=a,g=this.parseExpression(),a=null):(this.context.isBindingElement=l,this.context.isAssignmentTarget=n,this.context.firstCoverInitializedNameError=m,this.expect(";"))}e||(this.match(";")||(b=this.isolateCoverGrammar(this.parseExpression)),
this.expect(";"),this.match(")")||(c=this.isolateCoverGrammar(this.parseExpression)));!this.match(")")&&this.config.tolerant?(this.tolerateUnexpectedToken(this.nextToken()),l=this.finalize(this.createNode(),new f.EmptyStatement)):(this.expect(")"),n=this.context.inIteration,m=this.context.curlyParsing,this.context.inIteration=!0,this.context.curlyParsing="asObjectOrBlock",l=this.isolateCoverGrammar(this.parseStatement),this.context.curlyParsing=m,this.context.inIteration=n);return e&&g?this.finalize(h,
new f.ForInStatement(e,g,l)):this.finalize(h,new f.ForStatement(a,b,c,l))};d.parseContinueStatement=function(){const a=this.createNode();this.expectKeyword("continue");this.consumeSemicolon();return this.finalize(a,new f.ContinueStatement)};d.parseBreakStatement=function(){const a=this.createNode();this.expectKeyword("break");this.consumeSemicolon();return this.finalize(a,new f.BreakStatement)};d.parseReturnStatement=function(){this.config.globalReturn||this.context.inFunctionBody||this.tolerateError(k.Messages.IllegalReturn);
const a=this.createNode();this.expectKeyword("return");const b=(this.match(";")||this.match("}")||this.hasLineTerminator||2===this.lookahead.type)&&8!==this.lookahead.type&&10!==this.lookahead.type?null:this.parseExpression();this.consumeSemicolon();return this.finalize(a,new f.ReturnStatement(b))};d.parseStatement=function(){switch(this.lookahead.type){case 1:case 5:case 6:case 8:case 10:case 3:var a=this.parseExpressionStatement();break;case 7:a=this.lookahead.value;a="{"===a?this.parseBlockOrObjectStatement():
"("===a?this.parseExpressionStatement():";"===a?this.parseEmptyStatement():this.parseExpressionStatement();break;case 4:switch(this.lookahead.value.toLowerCase()){case "break":a=this.parseBreakStatement();break;case "continue":a=this.parseContinueStatement();break;case "for":a=this.parseForStatement();break;case "function":a=this.parseFunctionDeclaration();break;case "if":a=this.parseIfStatement();break;case "return":a=this.parseReturnStatement();break;case "var":a=this.parseVariableStatement();break;
default:a=this.parseExpressionStatement()}break;default:a=this.throwUnexpectedToken(this.lookahead)}return a};d.parseFunctionSourceElements=function(){const a=this.createNode();this.expect("{");const b=this.context.inIteration,c=this.context.inFunctionBody;this.context.inIteration=!1;this.context.inFunctionBody=!0;const e=[];for(;2!==this.lookahead.type&&!this.match("}");)e.push(this.parseStatementListItem());this.expect("}");this.context.inIteration=b;this.context.inFunctionBody=c;return this.finalize(a,
new f.BlockStatement(e))};d.parseFormalParameters=function(){const a=[];this.expect("(");if(!this.match(")"))for(;2!==this.lookahead.type;){a.push(this.parseVariableIdentifier());if(this.match(")"))break;this.expect(",");if(this.match(")"))break}this.expect(")");return a};d.parseFunctionDeclaration=function(){const a=this.createNode();this.expectKeyword("function");const b=this.parseVariableIdentifier(),c=this.parseFormalParameters(),e=this.parseFunctionSourceElements();return this.finalize(a,new f.FunctionDeclaration(b,
c,e))};d.parseScript=function(){const a=this.createNode(),b=[];for(;2!==this.lookahead.type;)b.push(this.parseStatementListItem());return this.finalize(a,new f.Program(b))};return t}();q.Parser=y;Object.defineProperty(q,"__esModule",{value:!0})});