// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/domUtils ../../core/maybe ../../core/watchUtils ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ../Widget ./widgetUtils ../../core/Logger ./jsxFactory".split(" "),function(ia,G,ja,N,ka,K,B,Wa,Xa,Ca,Da,Ea,Ya,la){function O(a,b){a=a.getBoundingClientRect();return{width:a.width/1,height:a.height/1,top:a.top/
1,right:a.right/1,bottom:a.bottom/1,left:a.left/1,x:a.left/1,y:a.top/1}}function y(a){return null==a?window:"[object Window]"!==a.toString()?(a=a.ownerDocument)?a.defaultView||window:window:a}function aa(a){a=y(a);return{scrollLeft:a.pageXOffset,scrollTop:a.pageYOffset}}function R(a){var b=y(a).Element;return a instanceof b||a instanceof Element}function w(a){var b=y(a).HTMLElement;return a instanceof b||a instanceof HTMLElement}function ma(a){if("undefined"===typeof ShadowRoot)return!1;var b=y(a).ShadowRoot;
return a instanceof b||a instanceof ShadowRoot}function C(a){return a?(a.nodeName||"").toLowerCase():null}function H(a){return((R(a)?a.ownerDocument:a.document)||window.document).documentElement}function ba(a){return O(H(a)).left+aa(a).scrollLeft}function F(a){return y(a).getComputedStyle(a)}function ca(a){a=F(a);return/auto|scroll|overlay|hidden/.test(a.overflow+a.overflowY+a.overflowX)}function Fa(a,b,c){void 0===c&&(c=!1);var d=w(b);w(b)&&b.getBoundingClientRect();var e=H(b);a=O(a);var f={scrollLeft:0,
scrollTop:0},g={x:0,y:0};if(d||!d&&!c){if("body"!==C(b)||ca(e))f=b!==y(b)&&w(b)?{scrollLeft:b.scrollLeft,scrollTop:b.scrollTop}:aa(b);w(b)?(g=O(b),g.x+=b.clientLeft,g.y+=b.clientTop):e&&(g.x=ba(e))}return{x:a.left+f.scrollLeft-g.x,y:a.top+f.scrollTop-g.y,width:a.width,height:a.height}}function da(a){var b=O(a),c=a.offsetWidth,d=a.offsetHeight;1>=Math.abs(b.width-c)&&(c=b.width);1>=Math.abs(b.height-d)&&(d=b.height);return{x:a.offsetLeft,y:a.offsetTop,width:c,height:d}}function W(a){return"html"===
C(a)?a:a.assignedSlot||a.parentNode||(ma(a)?a.host:null)||H(a)}function na(a){return 0<=["html","body","#document"].indexOf(C(a))?a.ownerDocument.body:w(a)&&ca(a)?a:na(W(a))}function S(a,b){var c;void 0===b&&(b=[]);var d=na(a);a=d===(null==(c=a.ownerDocument)?void 0:c.body);c=y(d);d=a?[c].concat(c.visualViewport||[],ca(d)?d:[]):d;b=b.concat(d);return a?b:b.concat(S(W(d)))}function oa(a){return w(a)&&"fixed"!==F(a).position?a.offsetParent:null}function T(a){for(var b=y(a),c=oa(a);c&&0<=["table","td",
"th"].indexOf(C(c))&&"static"===F(c).position;)c=oa(c);if(c&&("html"===C(c)||"body"===C(c)&&"static"===F(c).position))return b;if(!c)a:{c=-1!==navigator.userAgent.toLowerCase().indexOf("firefox");if(-1===navigator.userAgent.indexOf("Trident")||!w(a)||"fixed"!==F(a).position)for(a=W(a);w(a)&&0>["html","body"].indexOf(C(a));){var d=F(a);if("none"!==d.transform||"none"!==d.perspective||"paint"===d.contain||-1!==["transform","perspective"].indexOf(d.willChange)||c&&"filter"===d.willChange||c&&d.filter&&
"none"!==d.filter){c=a;break a}else a=a.parentNode}c=null}return c||b}function Ga(a){function b(f){d.add(f.name);[].concat(f.requires||[],f.requiresIfExists||[]).forEach(function(g){d.has(g)||(g=c.get(g))&&b(g)});e.push(f)}var c=new Map,d=new Set,e=[];a.forEach(function(f){c.set(f.name,f)});a.forEach(function(f){d.has(f.name)||b(f)});return e}function Ha(a){var b=Ga(a);return Ia.reduce(function(c,d){return c.concat(b.filter(function(e){return e.phase===d}))},[])}function Ja(a){var b;return function(){b||
(b=new Promise(function(c){Promise.resolve().then(function(){b=void 0;c(a())})}));return b}}function D(a){return a.split("-")[0]}function Ka(a){var b=a.reduce(function(c,d){var e=c[d.name];c[d.name]=e?Object.assign({},e,d,{options:Object.assign({},e.options,d.options),data:Object.assign({},e.data,d.data)}):d;return c},{});return Object.keys(b).map(function(c){return b[c]})}function pa(a,b){var c=b.getRootNode&&b.getRootNode();if(a.contains(b))return!0;if(c&&ma(c)){do{if(b&&a.isSameNode(b))return!0;
b=b.parentNode||b.host}while(b)}return!1}function ea(a){return Object.assign({},a,{left:a.x,top:a.y,right:a.x+a.width,bottom:a.y+a.height})}function qa(a,b){if("viewport"===b){b=y(a);var c=H(a);b=b.visualViewport;var d=c.clientWidth;c=c.clientHeight;var e=0,f=0;b&&(d=b.width,c=b.height,/^((?!chrome|android).)*safari/i.test(navigator.userAgent)||(e=b.offsetLeft,f=b.offsetTop));a={width:d,height:c,x:e+ba(a),y:f};a=ea(a)}else w(b)?(a=O(b),a.top+=b.clientTop,a.left+=b.clientLeft,a.bottom=a.top+b.clientHeight,
a.right=a.left+b.clientWidth,a.width=b.clientWidth,a.height=b.clientHeight,a.x=a.left,a.y=a.top):(f=H(a),a=H(f),d=aa(f),b=null==(c=f.ownerDocument)?void 0:c.body,c=z(a.scrollWidth,a.clientWidth,b?b.scrollWidth:0,b?b.clientWidth:0),e=z(a.scrollHeight,a.clientHeight,b?b.scrollHeight:0,b?b.clientHeight:0),f=-d.scrollLeft+ba(f),d=-d.scrollTop,"rtl"===F(b||a).direction&&(f+=z(a.clientWidth,b?b.clientWidth:0)-c),a=ea({width:c,height:e,x:f,y:d}));return a}function La(a){var b=S(W(a)),c=0<=["absolute","fixed"].indexOf(F(a).position)&&
w(a)?T(a):a;return R(c)?b.filter(function(d){return R(d)&&pa(d,c)&&"body"!==C(d)}):[]}function Ma(a,b,c){b="clippingParents"===b?La(a):[].concat(b);c=[].concat(b,[c]);c=c.reduce(function(d,e){e=qa(a,e);d.top=z(e.top,d.top);d.right=I(e.right,d.right);d.bottom=I(e.bottom,d.bottom);d.left=z(e.left,d.left);return d},qa(a,c[0]));c.width=c.right-c.left;c.height=c.bottom-c.top;c.x=c.left;c.y=c.top;return c}function P(a){return a.split("-")[1]}function fa(a){return 0<=["top","bottom"].indexOf(a)?"x":"y"}
function ra(a){var b=a.reference,c=a.element,d=(a=a.placement)?D(a):null;a=a?P(a):null;var e=b.x+b.width/2-c.width/2,f=b.y+b.height/2-c.height/2;switch(d){case "top":e={x:e,y:b.y-c.height};break;case "bottom":e={x:e,y:b.y+b.height};break;case "right":e={x:b.x+b.width,y:f};break;case "left":e={x:b.x-c.width,y:f};break;default:e={x:b.x,y:b.y}}d=d?fa(d):null;if(null!=d)switch(f="y"===d?"height":"width",a){case "start":e[d]-=b[f]/2-c[f]/2;break;case "end":e[d]+=b[f]/2-c[f]/2}return e}function sa(a){return Object.assign({},
{top:0,right:0,bottom:0,left:0},a)}function ta(a,b){return b.reduce(function(c,d){c[d]=a;return c},{})}function U(a,b){void 0===b&&(b={});var c=b;b=c.placement;b=void 0===b?a.placement:b;var d=c.boundary,e=void 0===d?"clippingParents":d;d=c.rootBoundary;var f=void 0===d?"viewport":d;d=c.elementContext;d=void 0===d?"popper":d;var g=c.altBoundary,l=void 0===g?!1:g;c=c.padding;c=void 0===c?0:c;c=sa("number"!==typeof c?c:ta(c,V));g=a.rects.popper;l=a.elements[l?"popper"===d?"reference":"popper":d];e=
Ma(R(l)?l:l.contextElement||H(a.elements.popper),e,f);f=O(a.elements.reference);l=ra({reference:f,element:g,strategy:"absolute",placement:b});g=ea(Object.assign({},g,l));f="popper"===d?g:f;var p={top:e.top-f.top+c.top,bottom:f.bottom-e.bottom+c.bottom,left:e.left-f.left+c.left,right:f.right-e.right+c.right};a=a.modifiersData.offset;if("popper"===d&&a){var m=a[b];Object.keys(p).forEach(function(h){var n=0<=["right","bottom"].indexOf(h)?1:-1,r=0<=["top","bottom"].indexOf(h)?"y":"x";p[h]+=m[r]*n})}return p}
function ua(){for(var a=arguments.length,b=Array(a),c=0;c<a;c++)b[c]=arguments[c];return!b.some(function(d){return!(d&&"function"===typeof d.getBoundingClientRect)})}function va(a){var b,c=a.popper,d=a.popperRect,e=a.placement,f=a.variation,g=a.offsets,l=a.position,p=a.gpuAcceleration,m=a.adaptive;a=a.roundOffsets;if(!0===a){a=g.y;var h=window.devicePixelRatio||1;a={x:X(X(g.x*h)/h)||0,y:X(X(a*h)/h)||0}}else a="function"===typeof a?a(g):g;h=a;a=h.x;a=void 0===a?0:a;h=h.y;h=void 0===h?0:h;var n=g.hasOwnProperty("x");
g=g.hasOwnProperty("y");var r="left",k="top",t=window;if(m){var q=T(c),v="clientHeight",u="clientWidth";q===y(c)&&(q=H(c),"static"!==F(q).position&&"absolute"===l&&(v="scrollHeight",u="scrollWidth"));if("top"===e||("left"===e||"right"===e)&&"end"===f)k="bottom",h-=q[v]-d.height,h*=p?1:-1;if("left"===e||("top"===e||"bottom"===e)&&"end"===f)r="right",a-=q[u]-d.width,a*=p?1:-1}c=Object.assign({position:l},m&&Na);if(p){var A;return Object.assign({},c,(A={},A[k]=g?"0":"",A[r]=n?"0":"",A.transform=1>=(t.devicePixelRatio||
1)?"translate("+a+"px, "+h+"px)":"translate3d("+a+"px, "+h+"px, 0)",A))}return Object.assign({},c,(b={},b[k]=g?h+"px":"",b[r]=n?a+"px":"",b.transform="",b))}function Y(a){return a.replace(/left|right|bottom|top/g,function(b){return Oa[b]})}function wa(a){return a.replace(/start|end/g,function(b){return Pa[b]})}function Qa(a,b){void 0===b&&(b={});var c=b.boundary,d=b.rootBoundary,e=b.padding,f=b.flipVariations,g=b.allowedAutoPlacements,l=void 0===g?xa:g,p=P(b.placement);b=p?f?ya:ya.filter(function(h){return P(h)===
p}):V;f=b.filter(function(h){return 0<=l.indexOf(h)});0===f.length&&(f=b);var m=f.reduce(function(h,n){h[n]=U(a,{placement:n,boundary:c,rootBoundary:d,padding:e})[D(n)];return h},{});return Object.keys(m).sort(function(h,n){return m[h]-m[n]})}function Ra(a){if("auto"===D(a))return[];var b=Y(a);return[wa(a),b,wa(b)]}function za(a,b,c){void 0===c&&(c={x:0,y:0});return{top:a.top-b.height-c.y,right:a.right-b.width+c.x,bottom:a.bottom-b.height+c.y,left:a.left-b.width-c.x}}function Aa(a){return["top","right",
"bottom","left"].some(function(b){return 0<=a[b]})}var V=["top","bottom","right","left"],ya=V.reduce(function(a,b){return a.concat([b+"-start",b+"-end"])},[]),xa=[].concat(V,["auto"]).reduce(function(a,b){return a.concat([b,b+"-start",b+"-end"])},[]),Ia="beforeRead read afterRead beforeMain main afterMain beforeWrite write afterWrite".split(" "),z=Math.max,I=Math.min,X=Math.round,Ba={placement:"bottom",modifiers:[],strategy:"absolute"},Z={passive:!0},Na={top:"auto",right:"auto",bottom:"auto",left:"auto"},
Oa={left:"right",right:"left",bottom:"top",top:"bottom"},Pa={start:"end",end:"start"},Ta=function(a){void 0===a&&(a={});var b=a.defaultModifiers,c=void 0===b?[]:b;a=a.defaultOptions;var d=void 0===a?Ba:a;return function(e,f,g){function l(){m.orderedModifiers.forEach(function(k){var t=k.name,q=k.options;q=void 0===q?{}:q;k=k.effect;"function"===typeof k&&(t=k({state:m,name:t,instance:r,options:q}),h.push(t||function(){}))})}function p(){h.forEach(function(k){return k()});h=[]}void 0===g&&(g=d);var m=
{placement:"bottom",orderedModifiers:[],options:Object.assign({},Ba,d),modifiersData:{},elements:{reference:e,popper:f},attributes:{},styles:{}},h=[],n=!1,r={state:m,setOptions:function(k){k="function"===typeof k?k(m.options):k;p();m.options=Object.assign({},d,m.options,k);m.scrollParents={reference:R(e)?S(e):e.contextElement?S(e.contextElement):[],popper:S(f)};k=Ha(Ka([].concat(c,m.options.modifiers)));m.orderedModifiers=k.filter(function(t){return t.enabled});l();return r.update()},forceUpdate:function(){if(!n){var k=
m.elements,t=k.reference;k=k.popper;if(ua(t,k))for(m.rects={reference:Fa(t,T(k),"fixed"===m.options.strategy),popper:da(k)},m.reset=!1,m.placement=m.options.placement,m.orderedModifiers.forEach(function(u){return m.modifiersData[u.name]=Object.assign({},u.data)}),t=0;t<m.orderedModifiers.length;t++)if(!0===m.reset)m.reset=!1,t=-1;else{var q=m.orderedModifiers[t];k=q.fn;var v=q.options;v=void 0===v?{}:v;q=q.name;"function"===typeof k&&(m=k({state:m,options:v,name:q,instance:r})||m)}}},update:Ja(function(){return new Promise(function(k){r.forceUpdate();
k(m)})}),destroy:function(){p();n=!0}};if(!ua(e,f))return r;r.setOptions(g).then(function(k){if(!n&&g.onFirstUpdate)g.onFirstUpdate(k)});return r}}({defaultModifiers:[{name:"eventListeners",enabled:!0,phase:"write",fn:function(){},effect:function(a){var b=a.state,c=a.instance;a=a.options;var d=a.scroll,e=void 0===d?!0:d;a=a.resize;var f=void 0===a?!0:a,g=y(b.elements.popper),l=[].concat(b.scrollParents.reference,b.scrollParents.popper);e&&l.forEach(function(p){p.addEventListener("scroll",c.update,
Z)});f&&g.addEventListener("resize",c.update,Z);return function(){e&&l.forEach(function(p){p.removeEventListener("scroll",c.update,Z)});f&&g.removeEventListener("resize",c.update,Z)}},data:{}},{name:"popperOffsets",enabled:!0,phase:"read",fn:function(a){var b=a.state;b.modifiersData[a.name]=ra({reference:b.rects.reference,element:b.rects.popper,strategy:"absolute",placement:b.placement})},data:{}},{name:"computeStyles",enabled:!0,phase:"beforeWrite",fn:function(a){var b=a.state,c=a.options;a=c.gpuAcceleration;
a=void 0===a?!0:a;var d=c.adaptive;d=void 0===d?!0:d;c=c.roundOffsets;c=void 0===c?!0:c;a={placement:D(b.placement),variation:P(b.placement),popper:b.elements.popper,popperRect:b.rects.popper,gpuAcceleration:a};null!=b.modifiersData.popperOffsets&&(b.styles.popper=Object.assign({},b.styles.popper,va(Object.assign({},a,{offsets:b.modifiersData.popperOffsets,position:b.options.strategy,adaptive:d,roundOffsets:c}))));null!=b.modifiersData.arrow&&(b.styles.arrow=Object.assign({},b.styles.arrow,va(Object.assign({},
a,{offsets:b.modifiersData.arrow,position:"absolute",adaptive:!1,roundOffsets:c}))));b.attributes.popper=Object.assign({},b.attributes.popper,{"data-popper-placement":b.placement})},data:{}},{name:"applyStyles",enabled:!0,phase:"write",fn:function(a){var b=a.state;Object.keys(b.elements).forEach(function(c){var d=b.styles[c]||{},e=b.attributes[c]||{},f=b.elements[c];w(f)&&C(f)&&(Object.assign(f.style,d),Object.keys(e).forEach(function(g){var l=e[g];!1===l?f.removeAttribute(g):f.setAttribute(g,!0===
l?"":l)}))})},effect:function(a){var b=a.state,c={popper:{position:b.options.strategy,left:"0",top:"0",margin:"0"},arrow:{position:"absolute"},reference:{}};Object.assign(b.elements.popper.style,c.popper);b.styles=c;b.elements.arrow&&Object.assign(b.elements.arrow.style,c.arrow);return function(){Object.keys(b.elements).forEach(function(d){var e=b.elements[d],f=b.attributes[d]||{};d=Object.keys(b.styles.hasOwnProperty(d)?b.styles[d]:c[d]).reduce(function(g,l){g[l]="";return g},{});w(e)&&C(e)&&(Object.assign(e.style,
d),Object.keys(f).forEach(function(g){e.removeAttribute(g)}))})}},requires:["computeStyles"]},{name:"offset",enabled:!0,phase:"main",requires:["popperOffsets"],fn:function(a){var b=a.state,c=a.name;a=a.options.offset;var d=void 0===a?[0,0]:a;a=xa.reduce(function(g,l){var p=b.rects;var m=D(l);var h=0<=["left","top"].indexOf(m)?-1:1,n="function"===typeof d?d(Object.assign({},p,{placement:l})):d;p=n[0];n=n[1];p=p||0;n=(n||0)*h;m=0<=["left","right"].indexOf(m)?{x:n,y:p}:{x:p,y:n};g[l]=m;return g},{});
var e=a[b.placement],f=e.x;e=e.y;null!=b.modifiersData.popperOffsets&&(b.modifiersData.popperOffsets.x+=f,b.modifiersData.popperOffsets.y+=e);b.modifiersData[c]=a}},{name:"flip",enabled:!0,phase:"main",fn:function(a){var b=a.state,c=a.options;a=a.name;if(!b.modifiersData[a]._skip){var d=c.mainAxis;d=void 0===d?!0:d;var e=c.altAxis;e=void 0===e?!0:e;var f=c.fallbackPlacements,g=c.padding,l=c.boundary,p=c.rootBoundary,m=c.altBoundary,h=c.flipVariations,n=void 0===h?!0:h,r=c.allowedAutoPlacements;c=
b.options.placement;h=D(c);f=f||(h!==c&&n?Ra(c):[Y(c)]);var k=[c].concat(f).reduce(function(J,Q){return J.concat("auto"===D(Q)?Qa(b,{placement:Q,boundary:l,rootBoundary:p,padding:g,flipVariations:n,allowedAutoPlacements:r}):Q)},[]);c=b.rects.reference;f=b.rects.popper;var t=new Map;h=!0;for(var q=k[0],v=0;v<k.length;v++){var u=k[v],A=D(u),E="start"===P(u),x=0<=["top","bottom"].indexOf(A),L=x?"width":"height",M=U(b,{placement:u,boundary:l,rootBoundary:p,altBoundary:m,padding:g});E=x?E?"right":"left":
E?"bottom":"top";c[L]>f[L]&&(E=Y(E));L=Y(E);x=[];d&&x.push(0>=M[A]);e&&x.push(0>=M[E],0>=M[L]);if(x.every(function(J){return J})){q=u;h=!1;break}t.set(u,x)}if(h)for(d=function(J){var Q=k.find(function(ha){if(ha=t.get(ha))return ha.slice(0,J).every(function(Sa){return Sa})});if(Q)return q=Q,"break"},e=n?3:1;0<e&&"break"!==d(e);e--);b.placement!==q&&(b.modifiersData[a]._skip=!0,b.placement=q,b.reset=!0)}},requiresIfExists:["offset"],data:{_skip:!1}},{name:"preventOverflow",enabled:!0,phase:"main",fn:function(a){var b=
a.state,c=a.options;a=a.name;var d=c.mainAxis,e=void 0===d?!0:d;d=c.altAxis;var f=void 0===d?!1:d;d=c.tether;d=void 0===d?!0:d;var g=c.tetherOffset,l=void 0===g?0:g,p=U(b,{boundary:c.boundary,rootBoundary:c.rootBoundary,padding:c.padding,altBoundary:c.altBoundary});c=D(b.placement);var m=P(b.placement),h=!m,n=fa(c);c="x"===n?"y":"x";g=b.modifiersData.popperOffsets;var r=b.rects.reference,k=b.rects.popper,t="function"===typeof l?l(Object.assign({},b.rects,{placement:b.placement})):l;l={x:0,y:0};if(g){if(e||
f){var q="y"===n?"top":"left",v="y"===n?"bottom":"right",u="y"===n?"height":"width",A=g[n],E=g[n]+p[q],x=g[n]-p[v],L=d?-k[u]/2:0,M="start"===m?r[u]:k[u];m="start"===m?-k[u]:-r[u];k=b.elements.arrow;k=d&&k?da(k):{width:0,height:0};var J=b.modifiersData["arrow#persistent"]?b.modifiersData["arrow#persistent"].padding:{top:0,right:0,bottom:0,left:0};q=J[q];v=J[v];k=z(0,I(r[u],k[u]));M=h?r[u]/2-L-k-q-t:M-k-q-t;r=h?-r[u]/2+L+k+v+t:m+k+v+t;h=b.elements.arrow&&T(b.elements.arrow);t=b.modifiersData.offset?
b.modifiersData.offset[b.placement][n]:0;h=g[n]+M-t-(h?"y"===n?h.clientTop||0:h.clientLeft||0:0);r=g[n]+r-t;e&&(e=d?I(E,h):E,x=d?z(x,r):x,e=z(e,I(A,x)),g[n]=e,l[n]=e-A);f&&(f=g[c],e=f+p["x"===n?"top":"left"],p=f-p["x"===n?"bottom":"right"],e=d?I(e,h):e,d=d?z(p,r):p,d=z(e,I(f,d)),g[c]=d,l[c]=d-f)}b.modifiersData[a]=l}},requiresIfExists:["offset"]},{name:"arrow",enabled:!0,phase:"main",fn:function(a){var b,c=a.state,d=a.name,e=a.options,f=c.elements.arrow,g=c.modifiersData.popperOffsets,l=D(c.placement);
a=fa(l);l=0<=["left","right"].indexOf(l)?"height":"width";if(f&&g){e=e.padding;e="function"===typeof e?e(Object.assign({},c.rects,{placement:c.placement})):e;e=sa("number"!==typeof e?e:ta(e,V));var p=da(f),m="y"===a?"top":"left",h="y"===a?"bottom":"right",n=c.rects.reference[l]+c.rects.reference[a]-g[a]-c.rects.popper[l];g=g[a]-c.rects.reference[a];f=(f=T(f))?"y"===a?f.clientHeight||0:f.clientWidth||0:0;g=f/2-p[l]/2+(n/2-g/2);l=z(e[m],I(g,f-p[l]-e[h]));c.modifiersData[d]=(b={},b[a]=l,b.centerOffset=
l-g,b)}},effect:function(a){var b=a.state;a=a.options.element;a=void 0===a?"[data-popper-arrow]":a;if(null!=a){if("string"===typeof a&&(a=b.elements.popper.querySelector(a),!a))return;pa(b.elements.popper,a)&&(b.elements.arrow=a)}},requires:["popperOffsets"],requiresIfExists:["preventOverflow"]},{name:"hide",enabled:!0,phase:"main",requiresIfExists:["preventOverflow"],fn:function(a){var b=a.state;a=a.name;var c=b.rects.reference,d=b.rects.popper,e=b.modifiersData.preventOverflow,f=U(b,{elementContext:"reference"}),
g=U(b,{altBoundary:!0});c=za(f,c);d=za(g,d,e);e=Aa(c);g=Aa(d);b.modifiersData[a]={referenceClippingOffsets:c,popperEscapeOffsets:d,isReferenceHidden:e,hasPopperEscaped:g};b.attributes.popper=Object.assign({},b.attributes.popper,{"data-popper-reference-hidden":e,"data-popper-escaped":g})}}]});const Ua="bottom bottom-start bottom-end left left-start left-end right right-start right-end top top-start top-end".split(" "),Va={position:"fixed","z-index":"1000"};B=function(a){function b(d,e){var f=a.call(this,
d,e)||this;f._popper=null;f._contentNode=null;f._renderAttached=!1;f._rootNode=null;f.anchorElement=null;f.offset=[0,0];f.open=!1;f.renderContentFunction=null;f._afterRootCreate=g=>{f._rootNode=g};f._afterContentCreate=g=>{f._contentNode=g};f._updatePosition=()=>{N.isSome(f._popper)&&f._popper.update()};return f}ia._inheritsLoose(b,a);var c=b.prototype;c.initialize=function(){this.when(()=>{this._projector.append(document.body,this.render);this._renderAttached=!0});this.own(ka.init(this,["open","anchorElement"],
()=>this._buildPopper()),ka.init(this,["placement","offset"],()=>this._setPopperOptions()))};c.destroy=function(){this.renderContentFunction=this.anchorElement=this.owner=null;this._renderAttached&&(this._projector.detach(this.render),this._renderAttached=!1);N.isSome(this._rootNode)&&(ja.remove(this._rootNode),this._rootNode=null);this._contentNode=null;N.isSome(this._popper)&&(this._popper.destroy(),this._popper=null)};c.render=function(){var d;const {open:e,owner:f,renderContentFunction:g}=this;
return la.tsx("div",{afterCreate:this._afterRootCreate,class:this.classes("esri-popover",e?"esri-popover--open":null),styles:Va},la.tsx("div",{dir:Ea.getDir(null==(d=this.owner)?void 0:d.container),afterCreate:this._afterContentCreate,afterUpdate:this._updatePosition},e&&(null==g?void 0:g.call(f))))};c._buildPopper=function(){N.isSome(this._popper)&&(this._popper.destroy(),this._popper=null);const d=this._contentNode;if(!N.isNone(d)&&this.open&&this.renderContentFunction){var e=this._getAnchor();
e&&(this._popper=Ta(e,d),this._setPopperOptions())}};c._setPopperOptions=function(){const {placement:d,offset:e,_popper:f}=this;N.isNone(f)||(f.setOptions({placement:d,modifiers:[{name:"offset",options:{offset:e}}]}),f.forceUpdate())};c._getAnchor=function(){const {anchorElement:d}=this;return ja.byId("function"===typeof d?d():d)};ia._createClass(b,[{key:"container",set:function(d){}},{key:"owner",set:function(d){this._set("owner",d)}},{key:"placement",get:function(){return"top"},set:function(d){-1===
Ua.indexOf(d)?this._clearOverride("placement"):this._override("placement",d)}}]);return b}(Da);G.__decorate([K.property()],B.prototype,"anchorElement",void 0);G.__decorate([K.property()],B.prototype,"container",null);G.__decorate([K.property()],B.prototype,"offset",void 0);G.__decorate([K.property()],B.prototype,"open",void 0);G.__decorate([K.property()],B.prototype,"owner",null);G.__decorate([K.property()],B.prototype,"placement",null);G.__decorate([K.property()],B.prototype,"renderContentFunction",
void 0);return B=G.__decorate([Ca.subclass("esri.widgets.support.Popover")],B)});