// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
require({cache:{"esri/smartMapping/statistics/support/utils":function(){define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../core/Error ../../../core/maybe ../../../geometry/SpatialReference ../../../layers/support/fieldUtils ../../../statistics/utils ../../../support/arcadeOnDemand".split(" "),function(z,n,q,w,y,H,I,J){function x(){x=n._asyncToGenerator(function*(h,f){if(!f)return[];const g=h.field,p=h.valueExpression,A=h.normalizationType,b=h.normalizationField,e=h.normalizationTotal,
k=[];h=h.viewInfoParams;let v=null,B=null;if(p){if(!r){const {arcadeUtils:C}=yield J.loadArcade();r=C}v=r.createFunction(p);B=h&&r.getViewInfo({viewingMode:h.viewingMode,scale:h.scale,spatialReference:new y(h.spatialReference)})}f.forEach(C=>{var D=C.attributes;if(p){var E=r.createExecContext(C,B);E=r.executeFunction(v,E)}else D&&(E=D[g]);A&&isFinite(E)&&(D=D&&parseFloat(D[b]),E=I.getNormalizedValue(E,A,D,e));k.push(E)});return k});return x.apply(this,arguments)}function u(h,f){return new q(h,f)}
function d(h,f){h=w.isSome(h)?h:"";w.isSome(f)&&f&&(h=h?"("+h+") AND ("+f+")":f);return h}function l(h){const f=h.layer;return h.fields.filter(g=>!f.getField(g))}function t(h){const f=h.layer;return h.fields.filter(g=>{g=f.getFieldUsageInfo(g);return!g||!g.supportsStatistics})}let r=null;z.createError=u;z.getDataValues=function(h,f){return x.apply(this,arguments)};z.getRangeExpr=function(h,f,g){f=null!=f?h+" \x3e\x3d "+f:"";h=null!=g?h+" \x3c\x3d "+g:"";g="";return(g=f&&h?d(f,h):f||h)?"("+g+")":""};
z.getSQLFilterForNormalization=function(h){const f=h.field,g=h.normalizationType;h=h.normalizationField;let p;if("field"===g)p="(NOT "+h+" \x3d 0)";else if("log"===g||"natural-log"===g||"square-root"===g)p=`(${f} > 0)`;return p};z.mergeWhereClauses=d;z.verifyBasicFieldValidity=function(h,f,g){const p=l({layer:h,fields:f});if(p.length)return u(g,"Unknown fields: "+p.join(", ")+". You can only use fields defined in the layer schema");h=t({layer:h,fields:f});if(h.length)return u(g,"Unsupported fields: "+
h.join(", ")+". You can only use fields that can be fetched i.e. AdapterFieldUsageInfo.supportsStatistics must be true")};z.verifyFieldType=function(h,f,g,p){let A=null;if(!f)A=u(g,"'field' is not defined in the layer schema");else if(f.name===h.objectIdField||-1===p.indexOf(f.type))A=u(g,"'field' should be one of these types: "+p.join(","));return A};z.verifyNumericField=function(h,f,g){let p;f?f.name!==h.objectIdField&&H.isNumericField(f)||(p=u(g,"'field' should be one of these numeric types: "+
H.numericTypes.join(","))):p=u(g,"'field' is not defined in the layer schema");return p};Object.defineProperty(z,"__esModule",{value:!0})})},"esri/layers/support/fieldUtils":function(){define("require exports ../../chunks/_rollupPluginBabelHelpers ../../core/Error ../../core/maybe ../../core/object ./domainUtils ../../support/arcadeOnDemand".split(" "),function(z,n,q,w,y,H,I,J){function x(a,c,m){if(a)for(const F of a)(a=(a=H.getDeepValue(F,c))&&"function"!==typeof a&&m.get(a))&&H.setDeepValue(F,a.name,
c)}function u(a,c){if(!a||!c)return[];W.clear();d(W,a,c);return Array.from(W).sort()}function d(a,c,m){var F;if(m)if(null!=c&&null!=(F=c.fields)&&F.length)if(m.includes("*"))for(const {name:K}of c.fields)a.add(K);else for(const K of m)l(a,c,K);else if(m.includes("*"))a.clear(),a.add("*");else for(const K of m)a.add(K)}function l(a,c,m){"string"===typeof m&&(c?(c=c.get(m))&&a.add(c.name):a.add(m))}function t(a,c,m){return r.apply(this,arguments)}function r(){r=q._asyncToGenerator(function*(a,c,m){var F;
if(m){var {arcadeUtils:K}=yield J.loadArcade();m=K.extractFieldNames(m,null==c?void 0:null==(F=c.fields)?void 0:F.map(P=>P.name));for(const P of m)l(a,c,P)}});return r.apply(this,arguments)}function h(a,c,m){return f.apply(this,arguments)}function f(){f=q._asyncToGenerator(function*(a,c,m){if(m&&"1\x3d1"!==m){m=(yield new Promise((F,K)=>z(["../../core/sql/WhereClause"],F,K))).WhereClause.create(m,c);if(!m.isStandardized)throw new w("fieldUtils:collectFilterFields","Where clause is not standardized");
d(a,c,m.fieldNames)}});return f.apply(this,arguments)}function g(a,c){for(const m of a)if(m&&m.valueType&&m.valueType===c)return m.name;return null}function p(){p=q._asyncToGenerator(function*(a){if(!a)return[];const c=new Set;yield A(c,a);return Array.from(c).sort()});return p.apply(this,arguments)}function A(a,c){return b.apply(this,arguments)}function b(){b=q._asyncToGenerator(function*(a,c){if(c){var m=H.getDeepValue("elevationInfo.featureExpressionInfo",c);if(m)return m.collectRequiredFields(a,
c.fieldsIndex)}});return b.apply(this,arguments)}function e(a,c,m){return k.apply(this,arguments)}function k(){k=q._asyncToGenerator(function*(a,c,m){m.outStatistic.onStatisticValueExpression?t(a,c,m.outStatistic.onStatisticValueExpression):a.add(m.outStatistic.onStatisticField)});return k.apply(this,arguments)}function v(){v=q._asyncToGenerator(function*(a,c,m){var F,K;if(c&&m&&"cluster"===m.type){var P=[];null!=(F=m.popupTemplate)&&F.expressionInfos&&P.push(...m.popupTemplate.expressionInfos.map(R=>
t(a,c.fieldsIndex,R.expression)));if(Array.isArray(null==(K=m.popupTemplate)?void 0:K.content)){F=m.popupTemplate.content;for(const R of F)"expression"===R.type&&R.expressionInfo&&P.push(t(a,c.fieldsIndex,R.expressionInfo.expression))}m.fields&&P.push(...m.fields.map(R=>e(a,c.fieldsIndex,R)));yield Promise.all(P)}});return v.apply(this,arguments)}function B(){B=q._asyncToGenerator(function*(a,c,m){c&&(c.timeInfo&&y.isSome(m)&&m.timeExtent&&d(a,c.fieldsIndex,[c.timeInfo.startField,c.timeInfo.endField]),
c.floorInfo&&d(a,c.fieldsIndex,[c.floorInfo.floorField]),y.isSome(m)&&y.isSome(m.where)&&(yield h(a,c.fieldsIndex,m.where)))});return B.apply(this,arguments)}function C(){C=q._asyncToGenerator(function*(a,c,m){c&&m&&(yield Promise.all(m.map(F=>D(a,c,F))))});return C.apply(this,arguments)}function D(a,c,m){return E.apply(this,arguments)}function E(){E=q._asyncToGenerator(function*(a,c,m){c&&m&&(m.valueExpression?yield t(a,c.fieldsIndex,m.valueExpression):m.field&&l(a,c.fieldsIndex,m.field))});return E.apply(this,
arguments)}function G(){G=q._asyncToGenerator(function*(a){if(!a)return[];const c="timeInfo"in a&&a.timeInfo;return c?u(a.fieldsIndex,[a.trackIdField,c.startField,c.endField]):[]});return G.apply(this,arguments)}function N(){N=q._asyncToGenerator(function*(a){if(!a)return[];const c=new Set;yield L(c,a);return Array.from(c).sort()});return N.apply(this,arguments)}function L(a,c){return O.apply(this,arguments)}function O(){O=q._asyncToGenerator(function*(a,c){const {labelingInfo:m,fieldsIndex:F}=c;
m&&m.length&&(yield Promise.all(m.map(K=>Q(a,F,K))))});return O.apply(this,arguments)}function Q(a,c,m){return M.apply(this,arguments)}function M(){M=q._asyncToGenerator(function*(a,c,m){if(m){var F=m.getLabelExpression();m=m.where;"arcade"===F.type?yield t(a,c,F.expression):(F=F.expression.match(/{[^}]*}/g))&&F.forEach(K=>{l(a,c,K.slice(1,-1))});yield h(a,c,m)}});return M.apply(this,arguments)}function X(a){return"number"===typeof a&&!isNaN(a)&&isFinite(a)}function la(a){return null===a||X(a)}function ma(a){return null===
a||S(a)}function ca(a){return null!=a&&"string"===typeof a}function na(a){return null===a||ca(a)}function oa(){return!0}function Y(a,c){let m;switch(a.type){case "date":case "integer":case "long":case "small-integer":case "esriFieldTypeDate":case "esriFieldTypeInteger":case "esriFieldTypeLong":case "esriFieldTypeSmallInteger":m=a.nullable?ma:S;break;case "double":case "single":case "esriFieldTypeSingle":case "esriFieldTypeDouble":m=a.nullable?la:X;break;case "string":case "esriFieldTypeString":m=
a.nullable?na:ca;break;default:m=oa}return 1===arguments.length?m:m(c)}function Z(a){return null!=a&&pa.has(a.type)}function da(a,c){return a.nullable&&null===c?null:Z(a)&&!ea(a.type,Number(c))?n.NumericRangeValidationError.OUT_OF_RANGE:Y(a,c)?a.domain?I.validateDomainValue(a.domain,c):null:n.TypeValidationError.INVALID_TYPE}function ea(a,c){return(a="string"===typeof a?aa(a):a)?a.isInteger?S(c)&&c>=a.min&&c<=a.max:c>=a.min&&c<=a.max:!1}function aa(a){switch(a){case "esriFieldTypeSmallInteger":case "small-integer":return T;
case "esriFieldTypeInteger":case "integer":return U;case "esriFieldTypeSingle":case "single":return V;case "esriFieldTypeDouble":case "double":return fa}}function ha(a,c,m){if(!c||!c.attributes||!a){if(y.isSome(m))for(var F of a)m.add(F);return!0}c=c.attributes;F=!1;for(const K of a)if(!(K in c))if(F=!0,y.isSome(m))m.add(K);else break;return F}function ba(){ba=q._asyncToGenerator(function*(a,c){const m=new Set;for(const F of c)yield t(m,a.fieldsIndex,F);return Array.from(m).sort()});return ba.apply(this,
arguments)}const ia="field field2 field3 normalizationField rotationInfo.field proportionalSymbolInfo.field proportionalSymbolInfo.normalizationField colorInfo.field colorInfo.normalizationField".split(" "),ja=["field","normalizationField"],W=new Set,S=(()=>"isInteger"in Number?Number.isInteger:a=>"number"===typeof a&&isFinite(a)&&Math.floor(a)===a)(),ka=["integer","small-integer","single","double"],pa=new Set([...ka,"esriFieldTypeInteger","esriFieldTypeSmallInteger","esriFieldTypeSingle","esriFieldTypeDouble"]);
n.NumericRangeValidationError=void 0;(n.NumericRangeValidationError||(n.NumericRangeValidationError={})).OUT_OF_RANGE="numeric-range-validation-error::out-of-range";n.TypeValidationError=void 0;(n.TypeValidationError||(n.TypeValidationError={})).INVALID_TYPE="type-validation-error::invalid-type";const T={min:-32768,max:32767,isInteger:!0},U={min:-2147483648,max:2147483647,isInteger:!0},V={min:-3.4E38,max:1.2E38,isInteger:!1},fa={min:-Number.MAX_VALUE,max:Number.MAX_VALUE,isInteger:!1};n.collectArcadeFieldNames=
t;n.collectElevationFields=A;n.collectFeatureReductionFields=function(a,c,m){return v.apply(this,arguments)};n.collectField=l;n.collectFields=d;n.collectFilterFields=function(a,c,m){return B.apply(this,arguments)};n.collectLabelingFields=L;n.collectOrderByInfos=function(a,c,m){return C.apply(this,arguments)};n.doubleRange=fa;n.featureHasFields=function(a,c){return!ha(a,c,null)};n.fixFields=u;n.fixRendererFields=function(a,c){if(null!=a&&null!=c)for(const m of Array.isArray(a)?a:[a])if(x(ia,m,c),"visualVariables"in
m&&m.visualVariables)for(const F of m.visualVariables)x(ja,F,c)};n.fixTimeInfoFields=function(a,c){if(null!=a&&null!=c&&c.fields.length)if("startField"in a){var m=c.get(a.startField);c=c.get(a.endField);a.startField=m&&m.name||null;a.endField=c&&c.name||null}else m=c.get(a.startTimeField),c=c.get(a.endTimeField),a.startTimeField=m&&m.name||null,a.endTimeField=c&&c.name||null};n.getDisplayFieldName=function({displayField:a,fields:c}){if(a)return a;if(!c||!c.length)return null;if(!(a=g(c,"name-or-title")||
g(c,"unique-identifier")||g(c,"type-or-category")))a:{for(const m of c)if(m&&m.name&&(c=m.name.toLowerCase(),-1<c.indexOf("name")||-1<c.indexOf("title"))){a=m.name;break a}a=null}return a};n.getElevationFields=function(a){return p.apply(this,arguments)};n.getExpressionFields=function(a,c){return ba.apply(this,arguments)};n.getFeatureEditFields=function(a){if(!a)return[];const c="editFieldsInfo"in a&&a.editFieldsInfo;return c?u(a.fieldsIndex,[c&&c.creatorField,c&&c.creationDateField,c&&c.editorField,
c&&c.editDateField]):[]};n.getFeatureGeometryFields=function(a){if(!a)return[];const c=a.geometryFieldsInfo;return c?u(a.fieldsIndex,[c.shapeAreaField,c.shapeLengthField]):[]};n.getFieldDefaultValue=function(a){const c=a.defaultValue;if(void 0!==c&&Y(a,c))return c;if(a.nullable)return null};n.getFieldRange=function(a){const c=I.getDomainRange(a.domain);if(c)return c;if(Z(a))return aa(a.type)};n.getLabelingFields=function(a){return N.apply(this,arguments)};n.getNumericTypeForValue=function(a){if(!X(a))return null;
if(S(a)){if(a>=T.min&&a<=T.max)return"esriFieldTypeSmallInteger";if(a>=U.min&&a<=U.max)return"esriFieldTypeInteger"}return a>=V.min&&a<=V.max?"esriFieldTypeSingle":"esriFieldTypeDouble"};n.getTimeFields=function(a){return G.apply(this,arguments)};n.integerRange=U;n.isDateField=function(a){return null!=a&&("date"===a.type||"esriFieldTypeDate"===a.type)};n.isNumberInRange=ea;n.isNumericField=Z;n.isStringField=function(a){return null!=a&&("string"===a.type||"esriFieldTypeString"===a.type)};n.isValidFieldValue=
function(a,c){return null===da(a,c)};n.isValueMatchingFieldType=Y;n.numericTypes=ka;n.packFields=function(a,c,m=1){if(!c||!a)return[];if(c.includes("*"))return["*"];c=u(a,c);return c.length/a.fields.length>=m?["*"]:c};n.populateMissingFields=ha;n.rendererFields=ia;n.sanitizeNullFieldValue=function(a){return null==a||"number"===typeof a&&isNaN(a)?null:a};n.singleRange=V;n.smallIntegerRange=T;n.unpackFieldNames=function(a,c){return y.isNone(c)||y.isNone(a)?[]:c.includes("*")?a.fields.map(m=>m.name):
c};n.validateFieldValue=da;n.validationErrorToString=function(a,c,m){switch(a){case I.DomainValidationError.INVALID_CODED_VALUE:return`Value ${m} is not in the coded domain - field: ${c.name}, domain: ${JSON.stringify(c.domain)}`;case I.DomainValidationError.VALUE_OUT_OF_RANGE:return`Value ${m} is out of the range of valid values - field: ${c.name}, domain: ${JSON.stringify(c.domain)}`;case n.TypeValidationError.INVALID_TYPE:return`Value ${m} is not a valid value for the field type - field: ${c.name}, type: ${c.type}, nullable: ${c.nullable}`;
case n.NumericRangeValidationError.OUT_OF_RANGE:{const {min:F,max:K}=aa(c.type);return`Value ${m} is out of range for the number type - field: ${c.name}, type: ${c.type}, value range is ${F} to ${K}`}}};n.visualVariableFields=ja;Object.defineProperty(n,"__esModule",{value:!0})})},"esri/layers/support/domainUtils":function(){define(["exports"],function(z){function n(q,w){switch(q.type){case "range":{const y="range"in q?q.range[1]:q.maxValue;if(+w<("range"in q?q.range[0]:q.minValue)||+w>y)return z.DomainValidationError.VALUE_OUT_OF_RANGE;
break}case "coded-value":case "codedValue":if(null==q.codedValues||q.codedValues.every(y=>null==y||y.code!==w))return z.DomainValidationError.INVALID_CODED_VALUE}return null}z.DomainValidationError=void 0;(function(q){q.VALUE_OUT_OF_RANGE="domain-validation-error::value-out-of-range";q.INVALID_CODED_VALUE="domain-validation-error::invalid-coded-value"})(z.DomainValidationError||(z.DomainValidationError={}));z.getDomainRange=function(q){if(q&&"range"===q.type)return{min:"range"in q?q.range[0]:q.minValue,
max:"range"in q?q.range[1]:q.maxValue}};z.isValidDomainValue=function(q,w){return null===n(q,w)};z.validateDomainValue=n;Object.defineProperty(z,"__esModule",{value:!0})})},"esri/support/arcadeOnDemand":function(){define("require exports ../chunks/_rollupPluginBabelHelpers ../geometry ../core/maybe ../geometry/SpatialReference".split(" "),function(z,n,q,w,y,H){function I(){J||(J=q._asyncToGenerator(function*(){const u=yield new Promise((d,l)=>z(["./arcadeUtils"],d,l));return{arcade:u.arcade,arcadeUtils:u,
Dictionary:u.Dictionary,Feature:u.arcadeFeature}})());return J}let J;w=(u,d,l)=>x.create(u,d,l,null,["$feature","$view"]);let x=function(){function u(l,t,r,h,f,g,p,A){this.script=l;this.evaluate=f;this.fields=Array.isArray(p)?p:p.fields;this._syntaxTree=h;this._arcade=t;this._arcadeDictionary=r;this._arcadeFeature=g;this._spatialReference=A;this._referencesGeometry=t.scriptTouchesGeometry(this._syntaxTree);this._referencesScale=this._arcade.referencesMember(this._syntaxTree,"scale")}u.create=function(){var l=
q._asyncToGenerator(function*(t,r,h,f,g,p){const {arcade:A,Feature:b,Dictionary:e}=yield I(),k=H.fromJSON(r);r=A.parseScript(t,p);g=g.reduce((E,G)=>({...E,[G]:null}),{});let v=null;y.isSome(f)&&(v=new e(f),v.immutable=!0,g.$config=null);f=A.scriptUsesGeometryEngine(r)&&A.enableGeometrySupport();p=A.scriptUsesFeatureSet(r)&&A.enableFeatureSetSupport();const B=A.scriptIsAsync(r)&&A.enableAsyncSupport();g={vars:g,spatialReference:k,useAsync:!!B};const C=new e;C.immutable=!1;C.setField("scale",0);const D=
A.compileScript(r,g);yield Promise.all([f,p,B]);return new u(t,A,e,r,E=>{"$view"in E&&E.$view&&(C.setField("scale",E.$view.scale),E.$view=C);v&&(E.$config=v);return D({vars:E,spatialReference:k})},new b,h,k)});return function(t,r,h,f,g,p){return l.apply(this,arguments)}}();var d=u.prototype;d.repurposeFeature=function(l){l.geometry&&!l.geometry.spatialReference&&(l.geometry.spatialReference=this._spatialReference);this._arcadeFeature.repurposeFromGraphicLikeObject(l.geometry,l.attributes,{fields:this.fields});
return this._arcadeFeature};d.repurposeAdapter=function(l){this._arcadeFeature.repurposeFromAdapter(l,{fields:this.fields});return this._arcadeFeature};d.createDictionary=function(){return new this._arcadeDictionary};d.referencesMember=function(l){return this._arcade.referencesMember(this._syntaxTree,l)};d.referencesFunction=function(l){return this._arcade.referencesFunction(this._syntaxTree,l)};d.referencesGeometry=function(){return this._referencesGeometry};d.referencesScale=function(){return this._referencesScale};
d.extractFieldLiterals=function(){return this._arcade.extractExpectedFieldLiterals(this._syntaxTree)};return u}();n.ArcadeExpression=x;n.createDictionaryExpression=(u,d,l,t)=>x.create(u,d,l,t,["$feature","$view"]);n.createLabelExpression=(u,d,l)=>x.create(u,d,l,null,["$feature"]);n.createRendererExpression=w;n.createVVExpression=w;n.default=x;n.loadArcade=I;Object.defineProperty(n,"__esModule",{value:!0})})},"esri/statistics/utils":function(){define(["exports","../rest/support/ClassBreaksDefinition",
"../rest/support/generateRendererUtils"],function(z,n,q){function w(b){const e=null!=b.minValue||null!=b.maxValue,k=!!b.sqlExpression&&b.supportsSQLExpression;return!(null!=b.normalizationField||null!=b.normalizationType)&&!e&&!k}function y(b){const {values:e,useSampleStdDev:k,supportsNullCount:v}=b;var B=Number.POSITIVE_INFINITY;let C=Number.NEGATIVE_INFINITY,D=null,E=null;var G=null;let N=null,L=0;const O=null==b.minValue?-Infinity:b.minValue,Q=null==b.maxValue?Infinity:b.maxValue;for(const M of e)Number.isFinite(M)?
M>=O&&M<=Q&&(D+=M,B=Math.min(B,M),C=Math.max(C,M),L++):"string"===typeof M&&L++;if(L&&null!=D){E=D/L;G=0;for(const M of e)Number.isFinite(M)&&M>=O&&M<=Q&&(G+=(M-E)**2);N=k?1<L?G/(L-1):0:0<L?G/L:0;G=Math.sqrt(N)}else C=B=null;B={avg:E,count:L,max:C,min:B,stddev:G,sum:D,variance:N};v&&(B.nullcount=e.length-L);b.percentileParams&&(B.median=H(e,b.percentileParams));return B}function H(b,e){const {fieldType:k,value:v,orderBy:B,isDiscrete:C}=e,D=I(k,"desc"===B);b=[...b].filter(L=>null!=L).sort((L,O)=>D(L,
O));if(0===b.length)return null;if(0>=v)return b[0];if(1<=v)return b[b.length-1];var E=(b.length-1)*v,G=Math.floor(E);e=G+1;E%=1;G=b[G];const N=b[e];return e>=b.length||C||"string"===typeof G||"string"===typeof N?G:G*(1-E)+N*E}function I(b,e){const k=e?1:-1,v=x(e),B=J(e);if(!b||!["esriFieldTypeDate","esriFieldTypeString","esriFieldTypeGUID","esriFieldTypeGlobalID",...p].includes(b))return(C,D)=>"number"===typeof C&&"number"===typeof D?v(C,D):"string"===typeof C&&"string"===typeof D?B(C,D):k;if("esriFieldTypeDate"===
b)return(C,D)=>{C=(new Date(C)).getTime();D=(new Date(D)).getTime();return isNaN(C)||isNaN(D)?k:v(C,D)};if(p.has(b))return(C,D)=>v(C,D);if("esriFieldTypeString"===b)return(C,D)=>B(C,D);if("esriFieldTypeGUID"===b||"esriFieldTypeGlobalID"===b){const C=J(e);return(D,E)=>C(u(D),u(E))}return e?(C,D)=>1:(C,D)=>-1}function J(b){return b?(e,k)=>{e=e.toUpperCase();k=k.toUpperCase();return e>k?-1:e<k?1:0}:(e,k)=>{e=e.toUpperCase();k=k.toUpperCase();return e<k?-1:e>k?1:0}}function x(b){return b?(e,k)=>k-e:(e,
k)=>e-k}function u(b){return b.substr(24,12)+b.substr(19,4)+b.substr(16,2)+b.substr(14,2)+b.substr(11,2)+b.substr(9,2)+b.substr(6,2)+b.substr(4,2)+b.substr(2,2)+b.substr(0,2)}function d(b,e){const k=t({field:e.field,normalizationType:e.normalizationType,normalizationField:e.normalizationField,classificationMethod:e.classificationMethod,standardDeviationInterval:e.standardDeviationInterval,breakCount:e.numClasses||5});b=l(b,e.minValue,e.maxValue);return q.createGenerateRendererClassBreaks({definition:k,
values:b,normalizationTotal:e.normalizationTotal})}function l(b,e,k){e=null==e?-Infinity:e;k=null==k?Infinity:k;return b.filter(v=>Number.isFinite(v)&&v>=e&&v<=k)}function t(b){const e=b.field,k=b.classificationMethod||"equal-interval",v=b.normalizationType,B=b.normalizationField,C=new n;C.classificationField=e;C.breakCount=b.breakCount;C.classificationMethod=k;C.standardDeviationInterval="standard-deviation"===k?b.standardDeviationInterval||1:void 0;C.normalizationType=v;C.normalizationField="field"===
v?B:void 0;return C}function r(b,e){const {field:k,classificationMethod:v,standardDeviationInterval:B,normalizationType:C,normalizationField:D,normalizationTotal:E,minValue:G,maxValue:N}=e,L=e.numBins||10;let O=e=null,Q=null;v&&"equal-interval"!==v||C?({classBreaks:b}=d(b,{field:k,normalizationType:C,normalizationField:D,normalizationTotal:E,classificationMethod:v,standardDeviationInterval:B,minValue:G,maxValue:N,numClasses:L}),e=b[0].minValue,O=b[b.length-1].maxValue,Q=b.map(M=>[M.minValue,M.maxValue])):
(null!=G&&null!=N?(e=G,O=N):(b=y({values:b,minValue:G,maxValue:N,useSampleStdDev:!C,supportsNullCount:w({normalizationType:C,normalizationField:D,minValue:G,maxValue:N})}),e=b.min,O=b.max),Q=f(e,O,L));return{min:e,max:O,intervals:Q}}function h(b,e){let k=-1;for(let v=b.length-1;0<=v;v--)if(e>=b[v][0]){k=v;break}return k}function f(b,e,k){const v=(e-b)/k,B=[];let C;for(let D=1;D<=k;D++)C=b+v,C=Number(C.toFixed(16)),B.push([b,D===k?e:C]),b=C;return B}const g=/\s*(\+|-)?((\d+(\.\d+)?)|(\.\d+))\s*/gi,
p=new Set(["esriFieldTypeInteger","esriFieldTypeSmallInteger","esriFieldTypeSingle","esriFieldTypeDouble"]),A="min max avg stddev count sum variance nullcount median".split(" ");z.calculateClassBreaks=d;z.calculateHistogram=function(b,e){const {min:k,max:v,intervals:B}=r(b,e),C=B.map((D,E)=>({minValue:B[E][0],maxValue:B[E][1],count:0}));for(const D of b)null!=D&&D>=k&&D<=v&&(b=h(B,D),-1<b&&C[b].count++);return{bins:C,minValue:k,maxValue:v,normalizationTotal:e.normalizationTotal}};z.calculatePercentile=
H;z.calculateStatistics=y;z.calculateStringStatistics=function(b){const e=b.returnDistinct?[...new Set(b.values)]:b.values,k=e.filter(B=>null!=B).length,v={count:k};b.supportsNullCount&&(v.nullcount=e.length-k);b.percentileParams&&(v.median=H(e,b.percentileParams));return v};z.calculateUniqueValuesCount=function(b){const e={};for(let k of b){if(null==k||"string"===typeof k&&""===k.trim())k=null;null==e[k]?e[k]={count:1,data:k}:e[k].count++}return{count:e}};z.createClassBreaksDefinition=t;z.createUVResult=
function(b,e,k){const v=b.count;b=[];k&&e&&"coded-value"===e.type&&e.codedValues.forEach(B=>{B=B.code;v.hasOwnProperty(B)||(v[B]={data:B,count:0})});for(const B in v)e=v[B],b.push({value:e.data,count:e.count,label:e.label});return{uniqueValueInfos:b}};z.getAttributeComparator=I;z.getEqualIntervalBins=f;z.getNormalizedValue=function(b,e,k,v){let B=null;switch(e){case "log":0!==b&&(B=Math.log(b)*Math.LOG10E);break;case "percent-of-total":Number.isFinite(v)&&0!==v&&(B=b/v*100);break;case "field":Number.isFinite(k)&&
0!==k&&(B=b/k);break;case "natural-log":0<b&&(B=Math.log(b));break;case "square-root":0<b&&(B=b**.5)}return B};z.isNullCountSupported=w;z.processSummaryStatisticsResult=function(b,e){let k;for(k in b)-1<A.indexOf(k)&&(Number.isFinite(b[k])||(b[k]=null));if(!e)return b;["avg","stddev","variance"].forEach(v=>{null!=b[v]&&(b[v]=Math.ceil(b[v]))});return b};z.resolveCBResult=function(b,e){let k=b.classBreaks;const v=k[0].minValue,B=k[k.length-1].maxValue,C="standard-deviation"===e;k=k.map(D=>{const E=
D.label;D={minValue:D.minValue,maxValue:D.maxValue,label:E};if(C&&E){const G=E.match(g).map(N=>+N.trim());2===G.length?(D.minStdDev=G[0],D.maxStdDev=G[1],0>G[0]&&0<G[1]&&(D.hasAvg=!0)):1===G.length&&(E.includes("\x3c")?(D.minStdDev=null,D.maxStdDev=G[0]):E.includes("\x3e")&&(D.minStdDev=G[0],D.maxStdDev=null))}return D});return{minValue:v,maxValue:B,classBreakInfos:k,normalizationTotal:b.normalizationTotal}};z.statisticTypes=A;Object.defineProperty(z,"__esModule",{value:!0})})},"esri/rest/support/ClassBreaksDefinition":function(){define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/jsonMap ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ./ClassificationDefinition".split(" "),
function(z,n,q,w,y,H,I,J,x){y=new q.JSONMap({esriClassifyEqualInterval:"equal-interval",esriClassifyManual:"manual",esriClassifyNaturalBreaks:"natural-breaks",esriClassifyQuantile:"quantile",esriClassifyStandardDeviation:"standard-deviation",esriClassifyDefinedInterval:"defined-interval"});q=new q.JSONMap({esriNormalizeByLog:"log",esriNormalizeByPercentOfTotal:"percent-of-total",esriNormalizeByField:"field"});x=function(u){function d(){var l=u.apply(this,arguments)||this;l.breakCount=null;l.classificationField=
null;l.classificationMethod=null;l.normalizationField=null;l.normalizationType=null;l.type="class-breaks-definition";return l}z._inheritsLoose(d,u);z._createClass(d,[{key:"standardDeviationInterval",set:function(l){"standard-deviation"===this.classificationMethod&&this._set("standardDeviationInterval",l)}},{key:"definedInterval",set:function(l){"defined-interval"===this.classificationMethod&&this._set("definedInterval",l)}}]);return d}(x);n.__decorate([w.property({json:{write:!0}})],x.prototype,"breakCount",
void 0);n.__decorate([w.property({json:{write:!0}})],x.prototype,"classificationField",void 0);n.__decorate([w.property({type:String,json:{read:y.read,write:y.write}})],x.prototype,"classificationMethod",void 0);n.__decorate([w.property({json:{write:!0}})],x.prototype,"normalizationField",void 0);n.__decorate([w.property({json:{read:q.read,write:q.write}})],x.prototype,"normalizationType",void 0);n.__decorate([w.property({value:null,json:{write:!0}})],x.prototype,"standardDeviationInterval",null);
n.__decorate([w.property({value:null,json:{write:!0}})],x.prototype,"definedInterval",null);n.__decorate([w.property()],x.prototype,"type",void 0);return x=n.__decorate([J.subclass("esri.rest.support.ClassBreaksDefinition")],x)})},"esri/rest/support/ClassificationDefinition":function(){define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/jsonMap ../../core/JSONSupport ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ./colorRamps ../../symbols/Symbol".split(" "),
function(z,n,q,w,y,H,I,J,x,u,d){q=new q.JSONMap({classBreaksDef:"class-breaks-definition",uniqueValueDef:"unique-value-definition"});w=function(l){function t(){var r=l.apply(this,arguments)||this;r.baseSymbol=null;r.colorRamp=null;r.type=null;return r}z._inheritsLoose(t,l);return t}(w.JSONSupport);n.__decorate([y.property({type:d,json:{write:!0}})],w.prototype,"baseSymbol",void 0);n.__decorate([y.property({types:u.types,json:{read:{reader:u.fromJSON},write:!0}})],w.prototype,"colorRamp",void 0);n.__decorate([y.property({json:{read:q.read,
write:q.write}})],w.prototype,"type",void 0);return w=n.__decorate([x.subclass("esri.rest.support.ClassificationDefinition")],w)})},"esri/rest/support/colorRamps":function(){define(["exports","./AlgorithmicColorRamp","./ColorRamp","./MultipartColorRamp"],function(z,n,q,w){q={key:"type",base:q,typeMap:{algorithmic:n,multipart:w}};z.fromJSON=function(y){return y&&y.type?"algorithmic"===y.type?n.fromJSON(y):"multipart"===y.type?w.fromJSON(y):null:null};z.types=q;Object.defineProperty(z,"__esModule",
{value:!0})})},"esri/rest/support/AlgorithmicColorRamp":function(){define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../Color ../../core/lang ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/enumeration ../../core/accessorSupport/decorators/subclass ./ColorRamp".split(" "),function(z,n,q,w,y,H,I,J,x){var u;x=u=function(d){function l(t){t=d.call(this,t)||this;t.algorithm=null;t.fromColor=null;t.toColor=
null;t.type="algorithmic";return t}z._inheritsLoose(l,d);l.prototype.clone=function(){return new u({fromColor:w.clone(this.fromColor),toColor:w.clone(this.toColor),algorithm:this.algorithm})};return l}(x);n.__decorate([I.enumeration({esriCIELabAlgorithm:"cie-lab",esriHSVAlgorithm:"hsv",esriLabLChAlgorithm:"lab-lch"})],x.prototype,"algorithm",void 0);n.__decorate([y.property({type:q,json:{type:[H.Integer],write:!0}})],x.prototype,"fromColor",void 0);n.__decorate([y.property({type:q,json:{type:[H.Integer],
write:!0}})],x.prototype,"toColor",void 0);n.__decorate([y.property({type:["algorithmic"]})],x.prototype,"type",void 0);return x=u=n.__decorate([J.subclass("esri.rest.support.AlgorithmicColorRamp")],x)})},"esri/core/accessorSupport/decorators/enumeration":function(){define(["exports","../../jsonMap","./property"],function(z,n,q){z.enumeration=function(w,y={}){var H;w=w instanceof n.JSONMap?w:new n.JSONMap(w,y);w={type:(null!=(H=null==y?void 0:y.ignoreUnknown)?H:1)?w.apiValues:String,readOnly:null==
y?void 0:y.readOnly,json:{type:w.jsonValues,read:null!=y&&y.readOnly?!1:{reader:w.read},write:{writer:w.write}}};void 0!==(null==y?void 0:y.default)&&(w.json.default=y.default);void 0!==(null==y?void 0:y.name)&&(w.json.name=y.name);return q.property(w)};Object.defineProperty(z,"__esModule",{value:!0})})},"esri/rest/support/ColorRamp":function(){define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/JSONSupport ../../core/accessorSupport/decorators/property ../../core/arrayUtils ../../core/has ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass".split(" "),
function(z,n,q,w,y,H,I,J){q=function(x){function u(d){d=x.call(this,d)||this;d.type=null;return d}z._inheritsLoose(u,x);return u}(q.JSONSupport);n.__decorate([w.property({readOnly:!0,json:{read:!1,write:!0}})],q.prototype,"type",void 0);return q=n.__decorate([J.subclass("esri.rest.support.ColorRamp")],q)})},"esri/rest/support/MultipartColorRamp":function(){define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/lang ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/accessorSupport/decorators/subclass ./AlgorithmicColorRamp ./ColorRamp".split(" "),
function(z,n,q,w,y,H,I,J){var x;y=x=function(u){function d(l){l=u.call(this,l)||this;l.colorRamps=null;l.type="multipart";return l}z._inheritsLoose(d,u);d.prototype.clone=function(){return new x({colorRamps:q.clone(this.colorRamps)})};return d}(J);n.__decorate([w.property({type:[I],json:{write:!0}})],y.prototype,"colorRamps",void 0);n.__decorate([w.property({type:["multipart"]})],y.prototype,"type",void 0);return y=x=n.__decorate([H.subclass("esri.rest.support.MultipartColorRamp")],y)})},"esri/symbols/Symbol":function(){define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../Color ../core/jsonMap ../core/JSONSupport ../core/accessorSupport/decorators/property ../core/arrayUtils ../core/has ../core/accessorSupport/ensureType ../core/accessorSupport/decorators/reader ../core/accessorSupport/decorators/subclass".split(" "),
function(z,n,q,w,y,H,I,J,x,u,d){w=new w.JSONMap({esriSMS:"simple-marker",esriPMS:"picture-marker",esriSLS:"simple-line",esriSFS:"simple-fill",esriPFS:"picture-fill",esriTS:"text",esriSHD:"shield-label-symbol",PointSymbol3D:"point-3d",LineSymbol3D:"line-3d",PolygonSymbol3D:"polygon-3d",WebStyleSymbol:"web-style",MeshSymbol3D:"mesh-3d",LabelSymbol3D:"label-3d",CIMSymbolReference:"cim"});let l=0;y=function(t){function r(f){f=t.call(this,f)||this;f.id=`sym${l++}`;f.type=null;return f}z._inheritsLoose(r,
t);var h=r.prototype;h.readColor=function(f){return f&&null!=f[0]?[f[0],f[1],f[2],f[3]/255]:f};h.collectRequiredFields=function(){var f=z._asyncToGenerator(function*(g,p){});return function(g,p){return f.apply(this,arguments)}}();h.hash=function(){return JSON.stringify(this.toJSON())};h.clone=function(){};z._createClass(r,[{key:"color",set:function(f){this._set("color",f)}}]);return r}(y.JSONSupport);n.__decorate([H.property({type:w.apiValues,readOnly:!0,json:{read:!1,write:{ignoreOrigin:!0,writer:w.write}}})],
y.prototype,"type",void 0);n.__decorate([H.property({type:q,value:new q([0,0,0,1]),json:{write:{allowNull:!0}}})],y.prototype,"color",null);n.__decorate([u.reader("color")],y.prototype,"readColor",null);return y=n.__decorate([d.subclass("esri.symbols.Symbol")],y)})},"esri/rest/support/generateRendererUtils":function(){define(["exports"],function(z){function n(d){const {classificationMethod:l,breakCount:t,normalizationType:r,definedInterval:h}=d.definition,f=[];var g=d.values;if(0===g.length)return[];
g=g.sort((v,B)=>v-B);var p=g[0],A=g[g.length-1];if("equal-interval"===l)if(g.length>=t){g=(A-p)/t;d=p;for(var b=1;b<t;b++){var e=Number((p+b*g).toFixed(6));f.push({minValue:d,maxValue:e,label:q(d,e,r)});d=e}f.push({minValue:d,maxValue:A,label:q(d,A,r)})}else g.forEach(v=>{f.push({minValue:v,maxValue:v,label:q(v,v,r)})});else if("natural-breaks"===l){g=w(g);d=y(g.uniqueValues,d.valueFrequency||g.valueFrequency,t);for(b=1;b<t;b++)g.uniqueValues.length>b&&(e=Number(g.uniqueValues[d[b]].toFixed(6)),f.push({minValue:p,
maxValue:e,label:q(p,e,r)}),p=e);f.push({minValue:p,maxValue:A,label:q(p,A,r)})}else if("quantile"===l)if(g.length>=t&&p!==A){d=Math.ceil(g.length/t);b=0;for(e=1;e<t;e++){var k=d+b-1;k>g.length&&(k=g.length-1);0>k&&(k=0);f.push({minValue:p,maxValue:g[k],label:q(p,g[k],r)});p=g[k];b+=d;d=Math.ceil((g.length-b)/(t-e))}f.push({minValue:p,maxValue:A,label:q(p,A,r)})}else for(A=-1,p=0;p<g.length;p++)d=g[p],d!==A&&(A=d,f.push({minValue:A,maxValue:d,label:q(A,d,r)}),A=d);else if("standard-deviation"===l)if(d=
J(g),b=x(g,d),0===b)f.push({minValue:g[0],maxValue:g[0],label:q(g[0],g[0],r)});else{g=I(p,A,t,d,b)*b;b=0;for(e=t;1<=e;e--)k=Number((d-(e-.5)*g).toFixed(6)),f.push({minValue:p,maxValue:k,label:q(p,k,r)}),p=k,b++;e=Number((d+.5*g).toFixed(6));f.push({minValue:p,maxValue:e,label:q(p,e,r)});p=e;b++;for(k=1;k<=t;k++)e=b===2*t?A:Number((d+(k+.5)*g).toFixed(6)),f.push({minValue:p,maxValue:e,label:q(p,e,r)}),p=e,b++}else if("defined-interval"===l){if(!h)return f;A=g[0];g=g[g.length-1];p=Math.ceil((g-A)/h);
d=A;for(b=1;b<p;b++)e=Number((A+b*h).toFixed(6)),f.push({minValue:d,maxValue:e,label:q(d,e,r)}),d=e;f.push({minValue:d,maxValue:g,label:q(d,g,r)})}return f}function q(d,l,t){let r=null;return r=d===l?t&&"percent-of-total"===t?d+"%":d.toString():t&&"percent-of-total"===t?d+"% - "+l+"%":d+" - "+l}function w(d){const l=[],t=[];let r=Number.MIN_VALUE,h=1,f=-1;for(let g=0;g<d.length;g++){const p=d[g];p===r?(h++,t[f]=h):null!==p&&(l.push(p),r=p,h=1,t.push(h),f++)}return{uniqueValues:l,valueFrequency:t}}
function y(d,l,t){var r=d.length;const h=[];t>r&&(t=r);for(var f=0;f<t;f++)h.push(Math.round(f*r/t-1));h.push(r-1);f=H(h,d,l,t);{r=f.mean;f=f.sdcm;var g=t,p=0,A=0;let e=0,k=0,v=!0;for(let B=0;2>B&&v;B++){0===B&&(v=!1);for(var b=0;b<g-1;b++)for(;h[b+1]+1!==h[b+2];)if(h[b+1]+=1,p=u(b,h,d,l),e=p.sbMean,p=p.sbSdcm,A=u(b+1,h,d,l),k=A.sbMean,A=A.sbSdcm,p+A<f[b]+f[b+1])f[b]=p,f[b+1]=A,r[b]=e,r[b+1]=k,v=!0;else{--h[b+1];break}for(b=g-1;0<b;b--)for(;h[b]!==h[b-1]+1;)if(--h[b],p=u(b-1,h,d,l),e=p.sbMean,p=p.sbSdcm,
A=u(b,h,d,l),k=A.sbMean,A=A.sbSdcm,p+A<f[b-1]+f[b])f[b-1]=p,f[b]=A,r[b-1]=e,r[b]=k,v=!0;else{h[b]+=1;break}}r=v}r&&(f=H(h,d,l,t));return h}function H(d,l,t,r){let h=[];var f=[],g=[];let p=0;const A=[],b=[];for(var e=0;e<r;e++){var k=u(e,d,l,t);A.push(k.sbMean);b.push(k.sbSdcm);p+=b[e]}k=p;for(e=!0;e||p<k;){e=!1;h=[];for(f=0;f<r;f++)h.push(d[f]);for(g=0;g<r;g++)for(k=d[g]+1;k<=d[g+1];k++)if(f=l[k],0<g&&k!==d[g+1]&&Math.abs(f-A[g])>Math.abs(f-A[g-1]))d[g]=k;else if(g<r-1&&d[g]!==k-1&&Math.abs(f-A[g])>
Math.abs(f-A[g+1])){d[g+1]=k-1;break}k=p;p=0;f=[];g=[];for(let v=0;v<r;v++){f.push(A[v]);g.push(b[v]);const B=u(v,d,l,t);A[v]=B.sbMean;b[v]=B.sbSdcm;p+=b[v]}}if(p>k){for(l=0;l<r;l++)d[l]=h[l],A[l]=f[l],b[l]=g[l];p=k}return{mean:A,sdcm:b}}function I(d,l,t,r,h){d=Math.max(r-d,l-r)/h/t;return 1<=d?1:.5<=d?.5:.25}function J(d){let l=0;for(let t=0;t<d.length;t++)l+=d[t];return l/=d.length}function x(d,l){let t=0;for(let r=0;r<d.length;r++){const h=d[r];t+=(h-l)*(h-l)}t/=d.length;return Math.sqrt(t)}function u(d,
l,t,r){var h=0,f=0;for(var g=l[d]+1;g<=l[d+1];g++){const p=r[g];h+=t[g]*p;f+=p}0>=f&&console.log("Exception in Natural Breaks calculation");h/=f;f=0;for(g=l[d]+1;g<=l[d+1];g++)f+=r[g]*(t[g]-h)**2;return{sbMean:h,sbSdcm:f}}z.createGenerateRendererClassBreaks=function(d){const {normalizationTotal:l}=d;return{classBreaks:n(d),normalizationTotal:l}};z.createGenerateRendererUniqueValues=function(d){d=w(d);const l=[],t=d.uniqueValues.length;for(let r=0;r<t;r++){const h=d.uniqueValues[r];l.push({value:h,
count:d.valueFrequency[r],label:h.toString()})}return{uniqueValues:l}};Object.defineProperty(z,"__esModule",{value:!0})})},"*noref":1}});
define(["exports","../../../chunks/_rollupPluginBabelHelpers","./utils","../../../statistics/utils"],function(z,n,q,w){function y(){y=n._asyncToGenerator(function*(x){const {attribute:u,features:d}=x,{normalizationType:l,normalizationField:t,minValue:r,maxValue:h,fieldType:f}=u;x=yield q.getDataValues({field:u.field,valueExpression:u.valueExpression,normalizationType:l,normalizationField:t,normalizationTotal:u.normalizationTotal,viewInfoParams:u.viewInfoParams},d);const g=w.isNullCountSupported({normalizationType:l,
normalizationField:t,minValue:r,maxValue:h}),p={value:.5,fieldType:f};x="esriFieldTypeString"===f?w.calculateStringStatistics({values:x,supportsNullCount:g,percentileParams:p}):w.calculateStatistics({values:x,minValue:r,maxValue:h,useSampleStdDev:!l,supportsNullCount:g,percentileParams:p});return w.processSummaryStatisticsResult(x,"esriFieldTypeDate"===f)});return y.apply(this,arguments)}function H(){H=n._asyncToGenerator(function*(x){const {attribute:u,features:d}=x;x=yield q.getDataValues({field:u.field,
valueExpression:u.valueExpression,viewInfoParams:u.viewInfoParams},d);x=w.calculateUniqueValuesCount(x);return w.createUVResult(x,u.domain,u.returnAllCodedValues)});return H.apply(this,arguments)}function I(){I=n._asyncToGenerator(function*(x){const {attribute:u,features:d}=x,{field:l,normalizationType:t,normalizationField:r,normalizationTotal:h,classificationMethod:f}=u;x=yield q.getDataValues({field:l,valueExpression:u.valueExpression,normalizationType:t,normalizationField:r,normalizationTotal:h,
viewInfoParams:u.viewInfoParams},d);x=w.calculateClassBreaks(x,{field:l,normalizationType:t,normalizationField:r,normalizationTotal:h,classificationMethod:f,standardDeviationInterval:u.standardDeviationInterval,numClasses:u.numClasses,minValue:u.minValue,maxValue:u.maxValue});return w.resolveCBResult(x,f)});return I.apply(this,arguments)}function J(){J=n._asyncToGenerator(function*(x){const {attribute:u,features:d}=x,{field:l,normalizationType:t,normalizationField:r,normalizationTotal:h,classificationMethod:f}=
u;x=yield q.getDataValues({field:l,valueExpression:u.valueExpression,normalizationType:t,normalizationField:r,normalizationTotal:h,viewInfoParams:u.viewInfoParams},d);return w.calculateHistogram(x,{field:l,normalizationType:t,normalizationField:r,normalizationTotal:h,classificationMethod:f,standardDeviationInterval:u.standardDeviationInterval,numBins:u.numBins,minValue:u.minValue,maxValue:u.maxValue})});return J.apply(this,arguments)}z.classBreaks=function(x){return I.apply(this,arguments)};z.histogram=
function(x){return J.apply(this,arguments)};z.summaryStatistics=function(x){return y.apply(this,arguments)};z.uniqueValues=function(x){return H.apply(this,arguments)};Object.defineProperty(z,"__esModule",{value:!0})});