// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
require({cache:{"esri/views/2d/engine/webgl/FeatureTile":function(){define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/CircularArray ../../../../core/has ../../../../core/maybe ../../../../chunks/mat2d ../../../../chunks/mat2df32 ../../../../chunks/vec2 ../../../../chunks/vec2f32 ./enums ./Utils ./WGLTile ./collisions/MetricReader ./cpuMapped/Geometry".split(" "),function(y,x,n,u,p,t,g,a,b,d,e,c,h,v){let r=0;u=function(m){function w(f,k,q,z,A){f=m.call(this,f,k,q)||this;
f.instanceId=r++;f.patchCount=0;f._renderState={current:{geometry:new Map,metrics:null},next:null,swap:!1,swapFrames:0,locked:!1};f._patches=new n(100);f._bufferPatches=new n(100);f._lastCommitTime=0;f._lastMessageWasClear=!1;f.transforms.labelMat2d=g.create();f._store=z;f._requestLabelUpdate=A;return f}x._inheritsLoose(w,m);var l=w.prototype;l.destroy=function(){m.prototype.destroy.call(this);this._renderState.current.geometry.forEach(f=>f.destroy())};l.getGeometry=function(f){return this._renderState.current.geometry.get(f)};
l.setTransform=function(f,k){m.prototype.setTransform.call(this,f,k);const q=this.transforms.labelMat2d;k=f.getScreenTransform(q,k);const z=b.create();a.transformMat2d(z,[this.x,this.y],k);t.identity(q);t.translate(q,q,z);t.multiply(q,f.viewMat2d,q)};l.patch=function(f,k){this.patchCount++;if(!f.clear||!this._lastMessageWasClear){(this._lastMessageWasClear=f.clear)&&50<=this._patches.size&&this._dropPatches();var q=f.addOrUpdate&&this.key.id!==f.addOrUpdate.tileKeyOrigin;k&&q?this._bufferPatches.enqueue(f):
(f.sort=f.sort&&!k,this._patches.enqueue(f));this.requestRender()}};l.commit=function(f){if(this._lastCommitTime!==f.time){this._lastCommitTime=f.time;for(f=0;4>f;f++)this._updateMesh(),this.isReady&&this._updateBufferMesh();this._renderState.swap&&(this._swapRenderStates(),this.requestRender())}};l.lock=function(){this._renderState.locked=!0};l.unlock=function(){this._renderState.locked=!1;this._flushUpdates();this._swap()};l._swapRenderStates=function(){this._renderState.next&&(this._renderState.locked?
(this._renderState.swap=!0,this.requestRender()):(this._renderState.swap=!0,0===this._renderState.swapFrames?(this._renderState.swapFrames=8,this.requestRender()):1!==this._renderState.swapFrames--?this.requestRender():this._swap()))};l._swap=function(){this._renderState.swap&&(this._renderState.swap=!1,p.isSome(this._renderState.next)&&(this._renderState.current.geometry.forEach(f=>f.destroy()),this._renderState.current=this._renderState.next,this._renderState.next=null,this._requestLabelUpdate()))};
l._flushUpdates=function(){let f=this._patches.maxSize;for(;this._patches.size&&f--;)this._updateMesh(),this._swap()};l._updateBufferMesh=function(){var f=this._bufferPatches.peek();if(!p.isSome(f)||!f.clear||null===this._renderState.next)for(;this._bufferPatches.size;)f=this._bufferPatches.dequeue(),p.isSome(f)&&this._patchBuffer(f)};l._updateMesh=function(){var f=this._patches.peek();p.isSome(f)&&f.clear&&null!==this._renderState.next||(f=this._patches.dequeue(),p.isSome(f)&&(!0===f.clear?this.isReady&&
(this._renderState.next={geometry:new Map,metrics:null}):(this.requestRender(),this._patch(f),f.end&&(this.ready(),this._swapRenderStates()))))};l._patch=function(f){e.forEachGeometryType(k=>{this._remove(k,f.remove);this._insert(k,f,!1)})};l._patchBuffer=function(f){e.forEachGeometryType(k=>{this._insert(k,f,!0)})};l._insert=function(f,k,q){try{var z;const A=p.unwrapOr(this._renderState.next,this._renderState.current),B=null==(z=k.addOrUpdate)?void 0:z.data[f],C=A.geometry;p.isNone(B)||(C.has(f)||
C.set(f,new v.Geometry(f,this.stage)),C.get(f).insert(B,k.sort,q),f===d.WGLGeometryType.LABEL&&this._insertLabelMetrics(k.type,B.metrics,k.clear))}catch(A){}};l._insertLabelMetrics=function(f,k,q){q=p.unwrapOr(this._renderState.next,this._renderState.current);if(!p.isNone(k))if(k=h.MetricReader.from(k),p.isNone(q.metrics))q.metrics=k;else{if("update"===f)for(f=k.getCursor();f.next();)q.metrics.delete(f.id);q.metrics.link(k)}};l._remove=function(f,k){f=p.unwrapOr(this._renderState.next,this._renderState.current).geometry.get(f);
k&&k.length&&f&&(f.remove(k),this._removeLabelMetrics(k))};l._removeLabelMetrics=function(f){const {metrics:k}=p.unwrapOr(this._renderState.next,this._renderState.current);if(!p.isNone(k)&&f.length)for(const q of f)for(;k.delete(q););};l._dropPatches=function(){const f=[];let k=!1;for(;this._patches.size;){const q=this._patches.dequeue();if(p.isNone(q))break;if(q.clear){if(k)break;k=!0}f.push(q)}this._patches.clear();f.forEach(q=>this._patches.enqueue(q))};x._createClass(w,[{key:"labelMetrics",get:function(){return this._renderState.current.metrics}},
{key:"hasData",get:function(){return!!this._renderState.current.geometry.size}}]);return w}(c.WGLTile);y.FeatureTile=u;Object.defineProperty(y,"__esModule",{value:!0})})},"esri/views/2d/engine/webgl/collisions/MetricReader":function(){define(["exports","../../../../../chunks/_rollupPluginBabelHelpers","../../../../../core/maybe"],function(y,x,n){let u=function(){function t(a){this._cursor=this._head=a}t.from=function(a){a=p.from(new Float32Array(a));return new t(a)};var g=t.prototype;g.computedMinZoom=
function(){return this._cursor.computedMinZoom()};g.setComputedMinZoom=function(a){return this._cursor.setComputedMinZoom(a)};g.boundsComputedAnchorX=function(a){return this._cursor.boundsComputedAnchorX(a)};g.boundsComputedAnchorY=function(a){return this._cursor.boundsComputedAnchorY(a)};g.setBoundsComputedAnchorX=function(a,b){return this._cursor.setBoundsComputedAnchorX(a,b)};g.setBoundsComputedAnchorY=function(a,b){return this._cursor.setBoundsComputedAnchorY(a,b)};g.boundsX=function(a){return this._cursor.boundsX(a)};
g.boundsY=function(a){return this._cursor.boundsY(a)};g.boundsWidth=function(a){return this._cursor.boundsWidth(a)};g.boundsHeight=function(a){return this._cursor.boundsHeight(a)};g.link=function(a){if(n.isSome(a._head))return this._cursor.link(a._head)};g.getCursor=function(){return this.copy()};g.copy=function(){var a;const b=new t(null==(a=this._head)?void 0:a.copy());if(!b._head)return b;a=b._head;let d=b._head._link;for(;d;)a._link=d.copy(),a=d,d=a._link;return b};g.peekId=function(){var a;return null!=
(a=this._cursor.peekId())?a:this._cursor._link.peekId()};g.nextId=function(){const a=this.id;for(;a===this.id;)if(!this.next())return!1;return!0};g.save=function(){this._savedCursor=this._cursor;this._savedOffset=this._cursor._offset};g.restore=function(){this._cursor=this._savedCursor;this._cursor._offset=this._savedOffset};g.next=function(){if(!this._cursor)return!1;if(!this._cursor.next()){if(!this._cursor._link)return!1;this._cursor=this._cursor._link;this._cursor._offset=0}return!0};g.lookup=
function(a){for(this._cursor=this._head;this._cursor&&!this._cursor.lookup(a);){if(!this._cursor._link)return!1;this._cursor=this._cursor._link}return!!this._cursor};g.delete=function(a){let b=this._head,d=null;for(;b;){if(b.delete(a))return b.isEmpty()&&n.isSome(d)&&(d._link=b._link),!0;d=b;b=b._link}return!1};x._createClass(t,[{key:"id",get:function(){return this._cursor.id}},{key:"baseZoom",get:function(){return this._cursor.baseZoom}},{key:"anchorX",get:function(){return this._cursor.anchorX}},
{key:"anchorY",get:function(){return this._cursor.anchorY}},{key:"directionX",get:function(){return this._cursor.directionX}},{key:"directionY",get:function(){return this._cursor.directionY}},{key:"size",get:function(){return this._cursor.size}},{key:"materialKey",get:function(){return this._cursor.materialKey}},{key:"boundsCount",get:function(){return this._cursor.boundsCount}}]);return t}(),p=function(){function t(a){this._offset=-1;this._link=null;this._deletedCount=this._count=0;this._offsets=
{instance:null};this._buffer=a}t.from=function(a){return new t(new Float32Array(a))};var g=t.prototype;g.isEmpty=function(){return this._deletedCount===this.count};g.computedMinZoom=function(){return this._buffer[this._offset+8]};g.setComputedMinZoom=function(a){this._buffer[this._offset+8]=a};g.boundsComputedAnchorX=function(a){return this._buffer[this._offset+10+6*a+0]};g.boundsComputedAnchorY=function(a){return this._buffer[this._offset+10+6*a+1]};g.setBoundsComputedAnchorX=function(a,b){this._buffer[this._offset+
10+6*a+0]=b};g.setBoundsComputedAnchorY=function(a,b){this._buffer[this._offset+10+6*a+1]=b};g.boundsX=function(a){return this._buffer[this._offset+10+6*a+2]};g.boundsY=function(a){return this._buffer[this._offset+10+6*a+3]};g.boundsWidth=function(a){return this._buffer[this._offset+10+6*a+4]};g.boundsHeight=function(a){return this._buffer[this._offset+10+6*a+5]};g.link=function(a){let b=this;for(;b._link;)b=b._link;b._link=a};g.getCursor=function(){return this.copy()};g.copy=function(){const a=new t(this._buffer);
a._link=this._link;a._offset=this._offset;a._deletedCount=this._deletedCount;a._offsets=this._offsets;a._count=this._count;return a};g.peekId=function(){const a=this._offset+10+6*this.boundsCount+0;return a>=this._buffer.length?0:this._buffer[a]};g.next=function(){let a=0;for(;this._offset<this._buffer.length&&100>a++&&(this._offset=-1===this._offset?0:this._offset+(10+6*this.boundsCount),4294967296===this.id););return 4294967296!==this.id&&this._offset<this._buffer.length};g.delete=function(a){const b=
this._offset,d=this.lookup(a);if(d)for(this.id=4294967295,++this._deletedCount;this.next()&&this.id===a;)this.id=4294967295,++this._deletedCount;this._offset=b;return d};g.lookup=function(a){const b=this._offset;if(n.isNone(this._offsets.instance)){this._offsets.instance=new Map;const d=this.copy();d._offset=-1;let e=0;for(;d.next();)d.id!==e&&(this._offsets.instance.set(d.id,d._offset),e=d.id)}if(!this._offsets.instance.has(a))return!1;this._offset=this._offsets.instance.get(a);return 4294967296===
this.id?(this._offset=b,!1):!0};g._computeCount=function(){const a=this._offset;let b=0;for(this._offset=-1;this.next();)b++;this._offset=a;return b};x._createClass(t,[{key:"count",get:function(){this._count||(this._count=this._computeCount());return this._count}},{key:"id",get:function(){return this._buffer[this._offset+0]},set:function(a){this._buffer[this._offset+0]=a}},{key:"baseZoom",get:function(){return this._buffer[this._offset+1]}},{key:"anchorX",get:function(){return this._buffer[this._offset+
2]}},{key:"anchorY",get:function(){return this._buffer[this._offset+3]}},{key:"directionX",get:function(){return this._buffer[this._offset+4]}},{key:"directionY",get:function(){return this._buffer[this._offset+5]}},{key:"size",get:function(){return this._buffer[this._offset+6]}},{key:"materialKey",get:function(){return this._buffer[this._offset+7]}},{key:"boundsCount",get:function(){return this._buffer[this._offset+9]}}]);return t}();y.MetricReader=u;y.MetricReaderNode=p;Object.defineProperty(y,"__esModule",
{value:!0})})},"esri/views/2d/engine/webgl/cpuMapped/Geometry":function(){define("exports ../../../../../core/maybe ../FeatureDisplayList ./Buffer ./DisplayRecordReader ../../../../webgl/VertexArrayObject".split(" "),function(y,x,n,u,p,t){let g=function(){function a(d,e){this._indicesInvalid=!1;this.geometryType=d}var b=a.prototype;b.destroy=function(){this._vao&&(this._vao.dispose(),this._vao=null);this._indexBuffer&&this._indexBuffer.destroy();this._vertexBuffer&&this._vertexBuffer.destroy()};b.insert=
function(d,e,c){if(d.records.byteLength)if(c=d.stride,this._vertexBuffer&&this._indexBuffer){var h=d.vertices.byteLength/c;this._indexBuffer.ensure(d.indices.byteLength/4);this._vertexBuffer.ensure(h);const {vertices:v,indices:r}=d;d=p.DisplayRecordReader.from(d.records);const m=this._vertexBuffer.insert(v,0,v.byteLength/c,0),w=this._indexBuffer.insert(r,0,r.byteLength/4,m);d.forEach(l=>{l.indexFrom+=w;l.vertexFrom+=m});x.unwrapOrThrow(this._records,"Expected records to be defined").link(d);if(e)this._indicesInvalid=
!0;else if(this._displayList)for(e=d.getCursor();e.next();)this._displayList.addRecord(e)}else{h=d.indices.byteLength/4;const v=d.vertices.byteLength/c,r=c/Uint32Array.BYTES_PER_ELEMENT;this._records=p.DisplayRecordReader.from(d.records);this._indexBuffer=new u.Buffer("index",h,1);this._vertexBuffer=new u.Buffer("vertex",v,r);this._indexBuffer.insert(d.indices,0,d.indices.byteLength/4,0);this._vertexBuffer.insert(d.vertices,0,d.vertices.byteLength/c,0);e&&(this._indicesInvalid=!0)}};b.remove=function(d){if(!x.isNone(this._records))for(const e of d){d=
this._records.getCursor();if(!d.lookup(e))continue;const c=d.indexFrom,h=d.vertexFrom;let v=d.indexCount,r=d.vertexCount;for(;d.next()&&d.id===e;)v+=d.indexCount,r+=d.vertexCount;this._indexBuffer.free(c,v);this._vertexBuffer.free(h,r,!0);this._records.delete(e)}};b.draw=function(d,e,c,h,v){if(this._vertexBuffer&&this._indexBuffer&&!x.isNone(this._records)){if(x.isNone(this._vertexBuffer.gpu)||x.isNone(this._indexBuffer.gpu))this._vao&&(this._vao.dispose(),this._vao=null),this._vertexBuffer.gpu=null,
this._indexBuffer.gpu=null;this._vertexBuffer.upload(d);this._indexBuffer.upload(d);if(!this._vao){const r=this._vertexBuffer.gpu,m=this._indexBuffer.gpu;if(!m||!r)return;this._vao=new t(d,c,e,{geometry:r},m)}e=h*Uint32Array.BYTES_PER_ELEMENT;d.bindVAO(this._vao);d.drawElements(4,v,5125,e)}};b.forEachCommand=function(d){if(!x.isNone(this._records)){this._sortIndices(this._records);if(!this._displayList){const e=this._cursorIndexOrder;this._displayList=n.FeatureDisplayList.from(this,this.geometryType,
this._records.getCursor(),e)}this._displayList.forEach(d)}};b._sortIndices=function(d){if(this._indicesInvalid){this._indicesInvalid=!1;for(var e=0,c=d.getCursor(),h=this._indexBuffer.getBuffer(),v=[],r=[],m=[];c.next();)r.push(c.index),m.push(c.sortKey),v.push(c.id);r.sort((w,l)=>{const f=m[l],k=m[w];return k===f?v[l]-v[w]:f-k});d=d.getCursor();for(const w of r){if(!d.seekIndex(w))throw Error("Expected to find index");const {indexFrom:l,indexCount:f}=d;d.indexFrom=e;for(c=0;c<f;c++)this._indexBuffer.set(e++,
h.array[l+c])}this._cursorIndexOrder=r;this._displayList=null}};return a}();y.Geometry=g;Object.defineProperty(y,"__esModule",{value:!0})})},"esri/views/2d/engine/webgl/FeatureDisplayList":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers","../../../../core/maybe","./cpuMapped/FreeList"],function(y,x,n,u){let p=function(){function g(b,d,e,c,h){this.target=b;this.geometryType=d;this.materialKey=e;this.indexFrom=c;this.indexCount=h}var a=g.prototype;a.extend=function(b){this.indexCount+=
b};a.draw=function(b,d,e){this.target.draw(b,d,e,this.indexFrom,this.indexCount)};x._createClass(g,[{key:"indexEnd",get:function(){return this.indexFrom+this.indexCount}}]);return g}(),t=function(){function g(b,d){this.geometryType=0;this._target=b;this.geometryType=d}g.from=function(b,d,e,c){b=new g(b,d);if(n.isSome(c))for(const h of c)e.seekIndex(h),b.addRecord(e);else for(;e.next();)b.addRecord(e);return b};var a=g.prototype;a.addRecord=function(b){var d=this._target,e=this.geometryType,c=b.materialKey;
const h=b.indexFrom;b=b.indexCount;if(n.isNone(this._head))c=new p(d,e,c,h,b),this._head=new u.List(c);else{d=null;for(e=this._head;e;){if(h<e.data.indexFrom)return this._insert(c,h,b,d,e);d=e;e=e.next}this._insert(c,h,b,d,null)}};a.forEach=function(b){n.isSome(this._head)&&this._head.forEach(b)};a.infos=function*(){if(n.isSome(this._head))for(const b of this._head.values())yield b};a._insert=function(b,d,e,c,h){if(n.isNone(c)&&n.isNone(h)){const v=new p(this._target,this.geometryType,b,d,e);this._head=
new u.List(v)}if(n.isNone(c)&&n.isSome(h))return this._insertAtHead(b,d,e,h);if(n.isSome(c)&&n.isNone(h))return this._insertAtEnd(b,d,e,c);if(n.isSome(c)&&n.isSome(h))return this._insertAtMiddle(b,d,e,c,h)};a._insertAtHead=function(b,d,e,c){b===c.data.materialKey&&d+e===c.data.indexFrom?(c.data.indexFrom=d,c.data.indexCount+=e):(b=new p(this._target,this.geometryType,b,d,e),this._head=new u.List(b),this._head.next=c)};a._insertAtEnd=function(b,d,e,c){c.data.materialKey===b&&c.data.indexEnd===d?c.data.indexCount+=
e:(b=new p(this._target,this.geometryType,b,d,e),b=new u.List(b),c.next=b)};a._insertAtMiddle=function(b,d,e,c,h){c.data.materialKey===b&&c.data.indexEnd===d?(c.data.indexCount+=e,c.data.materialKey===h.data.materialKey&&c.data.indexEnd===h.data.indexFrom&&(c.data.indexCount+=h.data.indexCount,c.next=h.next)):b===h.data.materialKey&&d+e===h.data.indexFrom?(h.data.indexFrom=d,h.data.indexCount+=e):(b=new p(this._target,this.geometryType,b,d,e),b=new u.List(b),c.next=b,b.next=h)};return g}();y.FeatureDisplayList=
t;y.FeatureDisplayListInfo=p;Object.defineProperty(y,"__esModule",{value:!0})})},"esri/views/2d/engine/webgl/cpuMapped/FreeList":function(){define(["exports","../../../../../chunks/_rollupPluginBabelHelpers","../../../../../core/maybe"],function(y,x,n){let u=function(){function t(a){if(Array.isArray(a)){this.data=a[0];var b=this;for(let d=1;d<a.length;d++)b.next=new t([a[d]]),b=b.next}else this.data=a}var g=t.prototype;g.values=function*(){let a=this;for(;a;)yield a.data,a=a.next};g.forEach=function(a){let b=
this;for(;b;)a(b.data),b=b.next};g.find=function(a){var b;return a(this.data)?this:null==(b=this.next)?void 0:b.find(a)};g.max=function(a,b=this){b=a(this.data)>a(b.data)?this:b;return this.next?this.next.max(a,b):b};g.remove=function(a,b=null){return this===a?b?(b.next=this.next,b):this.next:this.next.remove(a,this)};x._createClass(t,[{key:"last",get:function(){return this.next?this.next.last:this}}]);return t}(),p=function(){function t(a){this._head=null;n.isNone(a)||(this._head=new u(a))}var g=
t.prototype;g.maxAvailableSpace=function(){if(n.isNone(this._head))return 0;const a=this._head.max(b=>b.end-b.start);return a.data.end-a.data.start};g.firstFit=function(a){if(n.isNone(this._head))return null;var b=null;let d=this._head;for(;d;){const e=d.data.end-d.data.start;if(e===a)return b?b.next=d.next:this._head=d.next,d.data.start;if(e>a)return b=d.data.start,d.data.start+=a,b;b=d;d=d.next}return null};g.free=function(a,b){const d=a+b;if(n.isNone(this._head))this._head=new u({start:a,end:d});
else if(d<=this._head.data.start)if(d===this._head.data.start)this._head.data.start-=b;else{var e=new u({start:a,end:d});e.next=this._head;this._head=e}else{e=this._head;for(var c=e.next;c;){if(c.data.start>=d){if(e.data.end===a){e.data.end+=b;e.data.end===c.data.start&&(e.data.end+=c.data.end-c.data.start,e.next=c.next);return}if(c.data.start===d){c.data.start-=b;return}a=new u({start:a,end:d});a.next=e.next;e.next=a;return}e=c;c=c.next}a===e.data.end?e.data.end+=b:(a=new u({start:a,end:d}),e.next=
a)}};x._createClass(t,[{key:"head",get:function(){return this._head}}]);return t}();y.FreeList=p;y.List=u;Object.defineProperty(y,"__esModule",{value:!0})})},"esri/views/2d/engine/webgl/cpuMapped/Buffer":function(){define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../core/maybe ../../../../webgl/BufferObject ../../../../webgl/FramebufferObject ../../../../../core/has ../../../../webgl/checkWebGLError ../../../../webgl/enums ../../../../../chunks/builtins ../../../../webgl/Texture ../../../../webgl/VertexArrayObject ../BufferPool ./FreeList".split(" "),
function(y,x,n,u,p,t,g,a,b,d,e,c,h){p=function(){function v(m,w,l){w=c.TypedBuffer.create(w*l*Uint32Array.BYTES_PER_ELEMENT);this.strideInt=l;this.bufferType=m;this.dirty={start:Infinity,end:0};this.gpu=null;this._cpu=w;this.clear()}var r=v.prototype;r.destroy=function(){n.andThen(this.gpu,m=>m.dispose());n.andThen(this._cpu,m=>m.destroy());n.andThen(this._cpu2,m=>m.destroy())};r.clear=function(){this.dirty.start=Infinity;this.dirty.end=0;this.freeList=new h.FreeList({start:0,end:this._cpu.length/
this.strideInt});this.fillPointer=0};r.ensure=function(m){if(!(this.maxAvailableSpace()>=m)&&m*this.strideInt>this._cpu.length-this.fillPointer){n.isSome(this.gpu)&&(this.gpu=null);const w=this._cpu.length/this.strideInt;m=Math.round(1.25*(w+m));this._cpu.expand(m*this.strideInt*Uint32Array.BYTES_PER_ELEMENT);this.freeList.free(w,m-w)}};r.set=function(m,w){this._cpu.array[m]!==w&&(this._cpu.array[m]=w,this.dirty.start=Math.min(m,this.dirty.start),this.dirty.end=Math.max(m,this.dirty.end))};r.getBuffer=
function(){this._cpu2||(this._cpu2=this._cpu.slice());this._cpu2.length!==this._cpu.length&&this._cpu2.expand(this._cpu.length*this._cpu.array.BYTES_PER_ELEMENT);this._cpu2.set(this._cpu);return this._cpu2};r.maxAvailableSpace=function(){return this.freeList.maxAvailableSpace()};r.insert=function(m,w,l,f){const k=l*this.strideInt;m=new Uint32Array(m,w*this.strideInt*Uint32Array.BYTES_PER_ELEMENT,k);l=n.unwrapOrThrow(this.freeList.firstFit(l),"First fit region must be defined")*this.strideInt;w=l/
this.strideInt-w;if(0!==f)for(let q=0;q<m.length;q++)m[q]+=f;this._cpu.array.set(m,l);this.dirty.start=Math.min(this.dirty.start,l);this.dirty.end=Math.max(this.dirty.end,l+k);this.fillPointer=Math.max(this.fillPointer,l+k);return w};r.free=function(m,w,l){const f=m*this.strideInt,k=(m+w)*this.strideInt;if(!0===l)for(l=m;l!==m+w;l++)this._cpu.array[l*this.strideInt]=2147450879;this.dirty.start=Math.min(this.dirty.start,f);this.dirty.end=Math.max(this.dirty.end,k);this.freeList.free(m,w)};r.upload=
function(m){this.dirty.end&&(n.isNone(this.gpu)?this.gpu=this._createBuffer(m):this.gpu.setSubDataFromView(this._cpu.array,this.dirty.start,this.dirty.start,this.dirty.end),this.dirty.start=Infinity,this.dirty.end=0)};r._createBuffer=function(m){return"index"===this.bufferType?u.createIndex(m,35048,this._cpu.array):u.createVertex(m,35048,this._cpu.array)};x._createClass(v,[{key:"elementSize",get:function(){return this._cpu.length/this.strideInt}},{key:"bufferSize",get:function(){return this._cpu.length/
this.strideInt}}]);return v}();y.Buffer=p;Object.defineProperty(y,"__esModule",{value:!0})})},"esri/views/2d/engine/webgl/BufferPool":function(){define(["exports","../../../../chunks/_rollupPluginBabelHelpers","../../../../core/has","../../../../core/maybe","./cpuMapped/FreeList"],function(y,x,n,u,p){const t=n("esri-2d-log-allocations");n=function(){function b(e){this._array=e}b.create=function(e){e=a.acquire(e);return new b(e)};var d=b.prototype;d.expand=function(e){e=a.acquire(e);e.set(this._array);
a.release(this._array);this._array=e};d.destroy=function(){a.release(this._array)};d.set=function(e,c){this._array.set(e._array,c)};d.slice=function(){const e=a.acquire(this._array.byteLength);e.set(this._array);return new b(e)};x._createClass(b,[{key:"array",get:function(){return this._array}},{key:"length",get:function(){return this._array.length}}]);return b}();let g=function(){function b(){this._data=new ArrayBuffer(b.BYTE_LENGTH);this._freeList=new p.FreeList({start:0,end:this._data.byteLength})}
var d=b.prototype;d.allocate=function(e){const c=this._freeList.firstFit(e);return u.isNone(c)?null:new Uint32Array(this._data,c,e/Uint32Array.BYTES_PER_ELEMENT)};d.free=function(e){this._freeList.free(e.byteOffset,e.byteLength)};x._createClass(b,[{key:"buffer",get:function(){return this._data}}],[{key:"BYTE_LENGTH",get:function(){return 64E6}}]);return b}();const a=new (function(){function b(){this._bytesAllocated=0;this._pages=[];this._pagesByBuffer=new Map;this._addPage()}var d=b.prototype;d.acquire=
function(e){this._bytesAllocated+=e;t&&console.log(`Allocating ${e}, (${this._bytesAllocated} / ${this._bytesTotal})`);if(e>g.BYTE_LENGTH)return new Uint32Array(e/Uint32Array.BYTES_PER_ELEMENT);for(const c of this._pages){const h=c.allocate(e);if(u.isSome(h))return h}return u.unwrapOrThrow(this._addPage().allocate(e),"Expected to allocate page")};d.release=function(e){this._bytesAllocated-=e.byteLength;t&&console.log(`Freeing ${e.byteLength}, (${this._bytesAllocated} / ${this._bytesTotal})`);const c=
this._pagesByBuffer.get(e.buffer);c&&c.free(e)};d._addPage=function(){const e=new g;this._pages.push(e);this._pagesByBuffer.set(e.buffer,e);return e};x._createClass(b,[{key:"_bytesTotal",get:function(){return this._pages.length*g.BYTE_LENGTH}}]);return b}());y.TypedBuffer=n;Object.defineProperty(y,"__esModule",{value:!0})})},"esri/views/2d/layers/features/tileRenderers/BaseTileRenderer":function(){define("../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/HandleOwner ../../../../../core/accessorSupport/decorators/property ../../../../../core/arrayUtils ../../../../../core/has ../../../../../core/accessorSupport/ensureType ../../../../../core/accessorSupport/decorators/subclass".split(" "),
function(y,x,n,u,p,t,g,a){n=function(b){function d(c){c=b.call(this,c)||this;c.tiles=new Map;return c}y._inheritsLoose(d,b);var e=d.prototype;e.destroy=function(){this.tiles.clear();this.layer=this.layerView=this.tileInfoView=this.tiles=null};e.acquireTile=function(c){const h=this.createTile(c);h.once("isReady",()=>this.notifyChange("updating"));this.tiles.set(c.id,h);return h};e.forceAttributeTextureUpload=function(){};e.forEachTile=function(c){this.tiles.forEach(c)};e.releaseTile=function(c){this.tiles.delete(c.key.id);
this.disposeTile(c)};e.isUpdating=function(){let c=!0;this.tiles.forEach(h=>{c=c&&h.isReady});return!c};e.setHighlight=function(){};e.invalidateLabels=function(){};e.requestUpdate=function(){this.layerView.requestUpdate()};y._createClass(d,[{key:"updating",get:function(){return this.isUpdating()}}]);return d}(n.HandleOwner);x.__decorate([u.property()],n.prototype,"layer",void 0);x.__decorate([u.property()],n.prototype,"layerView",void 0);x.__decorate([u.property()],n.prototype,"tileInfoView",void 0);
x.__decorate([u.property()],n.prototype,"updating",null);return n=x.__decorate([a.subclass("esri.views.2d.layers.features.tileRenderers.BaseTileRenderer")],n)})},"esri/views/2d/layers/features/tileRenderers/support/WGLFeatureView":function(){define("exports ../../../../../../chunks/_rollupPluginBabelHelpers ../../../../../../core/has ../../../../../../core/promiseUtils ../../../../engine/brushes ../../../../engine/FeatureContainer ../../../../engine/webgl/enums".split(" "),function(y,x,n,u,p,t,g){const a=
n("featurelayer-order-by-server-enabled");n=function(b){function d(c,h,v,r){c=b.call(this,c)||this;c._pointToCallbacks=new Map;c._layer=v;c._layerView=h;c._onUpdate=r;return c}x._inheritsLoose(d,b);var e=d.prototype;e.renderChildren=function(c){this.attributeView.update();this.hasAnimation&&c.painter.effects.integrate.draw(c,c.attributeView);b.prototype.renderChildren.call(this,c)};e.hasEmptyAttributeView=function(){return this.attributeView.isEmpty()};e.isUpdating=function(){return this.attributeView.isUpdating()};
e.hitTest=function(c){const h=u.createResolver();this._pointToCallbacks.set(c,h);this.requestRender();return h.promise};e.onTileData=function(c,h){const v=a&&"orderBy"in this._layer&&this._layer.orderBy,r=(null==v?void 0:v.length)&&!v[0].valueExpression&&v[0].field;c.patch(h,v&&this._layerView.orderByFields===r);this.contains(c)||this.addChild(c);this.requestRender()};e.onTileError=function(c){this.contains(c)||this.addChild(c)};e.updateTransitionProperties=function(c,h){b.prototype.updateTransitionProperties.call(this,
c,h);this._layerView.featureEffectView.transitionStep(c,h);this._layerView.featureEffectView.transitioning&&this.requestRender()};e.doRender=function(c){const {minScale:h,maxScale:v}=this._layer,r=c.state.scale;r<=(h||Infinity)&&r>=v&&b.prototype.doRender.call(this,c)};e.onAttributeStoreUpdate=function(){this.hasLabels&&this._layerView.view.labelManager.requestUpdate();this._onUpdate()};e.prepareRenderPasses=function(c){const h=c.registerRenderPass({name:"label",brushes:[p.brushes.label],target:()=>
this.hasLabels?this.children:null,drawPhase:g.WGLDrawPhase.LABEL|g.WGLDrawPhase.LABEL_ALPHA}),v=c.registerRenderPass({name:"geometry",brushes:[p.brushes.fill,p.brushes.line,p.brushes.marker,p.brushes.text],target:()=>this.children,enableDefaultDraw:()=>!this._layerView.featureEffectView.hasEffects,effects:[{apply:c.effects.outsideEffect,enable:()=>this._layerView.featureEffectView.hasEffects,args:()=>this._layerView.featureEffectView.excludedEffects},{apply:c.effects.insideEffect,enable:()=>this._layerView.featureEffectView.hasEffects,
args:()=>this._layerView.featureEffectView.includedEffects},{apply:c.effects.hittest,enable:()=>!!this._pointToCallbacks.size,args:()=>this._pointToCallbacks}]}),r=c.registerRenderPass({name:"highlight",brushes:[p.brushes.fill,p.brushes.line,p.brushes.marker,p.brushes.text],target:()=>this.children,drawPhase:g.WGLDrawPhase.HIGHLIGHT,enableDefaultDraw:()=>!1,effects:[{apply:c.effects.highlight,enable:()=>!!this._layerView.hasHighlight()}]});return[...b.prototype.prepareRenderPasses.call(this,c),v,
r,h]};x._createClass(d,[{key:"hasAnimation",get:function(){return this.hasLabels}},{key:"hasLabels",get:function(){if("sublayers"in this._layer)return this._layer.sublayers.some(h=>h.labelingInfo&&h.labelingInfo.length&&h.labelsVisible);var c=this._layer.featureReduction;c=c&&"cluster"===c.type&&c.labelsVisible&&c.labelingInfo&&c.labelingInfo.length;return this._layer.labelingInfo&&this._layer.labelingInfo.length&&this._layer.labelsVisible||!!c}}]);return d}(t.FeatureContainer);y.WGLFeatureView=n;
Object.defineProperty(y,"__esModule",{value:!0})})},"*noref":1}});
define("../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/has ../../../../../core/promiseUtils ../../../../../core/Logger ../../../../../core/accessorSupport/ensureType ../../../../../core/arrayUtils ../../../../../core/accessorSupport/set ../../../../../core/accessorSupport/decorators/subclass ../../../../../geometry/support/aaBoundingRect ../../../engine/webgl/FeatureTile ../support/rendererUtils ./BaseTileRenderer ./support/visualVariablesUtils ./support/WGLFeatureView".split(" "),function(y,
x,n,u,p,t,g,a,b,d,e,c,h,v,r){p=function(m){function w(){return m.apply(this,arguments)||this}y._inheritsLoose(w,m);var l=w.prototype;l.install=function(f){const k=new r.WGLFeatureView(this.tileInfoView,this.layerView,this.layer,()=>this.notifyChange("updating"));this.featuresView=k;f.addChild(k)};l.uninstall=function(f){f.removeChild(this.featuresView);this.featuresView.destroy()};l.fetchResource=function(f,k){({url:f}=f);const q=this.featuresView.stage;try{return q.resourceManager.fetchResource(f,
{signal:k.signal})}catch(z){return u.isAbortError(z)?Promise.resolve({width:0,height:0}):Promise.reject(z)}};l.isUpdating=function(){var f;const k=m.prototype.isUpdating.call(this),q=!this.featuresView||this.featuresView.isUpdating(),z=null==(f=this.featuresView)?void 0:f.hasEmptyAttributeView();f=k||q||k&&z;n("esri-2d-log-updating")&&console.log(`Updating SymbolTileRenderer ${f}\n  -> updatingTiles ${k}\n  -> hasFeaturesView ${!!this.featuresView}\n  -> updatingFeaturesView ${q}`);return f};l.hitTest=
function(f){return this.featuresView.hitTest(f)};l.supportsRenderer=function(f){return null!=f&&-1!==["simple","class-breaks","unique-value","dot-density","dictionary"].indexOf(f.type)};l.onConfigUpdate=function(f){var k=null;"visualVariables"in f&&(k=(c.simplifyVVRenderer(f).visualVariables||[]).map(q=>{const z=q.clone();"normalizationField"in q&&(z.normalizationField=null);q.valueExpression&&"$view.scale"!==q.valueExpression&&(z.valueExpression=null,z.field="nop");return z}),k=v.convertVisualVariables(k));
this.featuresView.setRendererInfo(f,k,this.layerView.featureEffect)};l.onTileData=function(f){const k=this.tiles.get(f.tileKey);if(k&&f.data)this.featuresView.onTileData(k,f.data);this.layerView.view.labelManager.requestUpdate()};l.onTileError=function(f){if(f=this.tiles.get(f.tileKey))this.featuresView.onTileError(f)};l.forceAttributeTextureUpload=function(){this.featuresView.attributeView.forceTextureUpload()};l.lockGPUUploads=function(){this.featuresView.attributeView.lockTextureUpload();this.tiles.forEach(f=>
f.lock())};l.unlockGPUUploads=function(){this.featuresView.attributeView.unlockTextureUpload();this.tiles.forEach(f=>f.unlock())};l.getMaterialItems=function(){var f=y._asyncToGenerator(function*(k){return this.featuresView.getMaterialItems(k)});return function(k){return f.apply(this,arguments)}}();l.invalidateLabels=function(){this.featuresView.hasLabels&&this.layerView.view.labelManager.requestUpdate()};l.createTile=function(f){const k=this.tileInfoView.getTileBounds(d.create(),f);return new e.FeatureTile(f,
k[0],k[3],this.featuresView.attributeView,()=>this.layerView.view.labelManager.requestUpdate())};l.disposeTile=function(f){this.featuresView.removeChild(f);f.destroy();this.layerView.view.labelManager.requestUpdate()};return w}(h);return p=x.__decorate([b.subclass("esri.views.2d.layers.features.tileRenderers.SymbolTileRenderer")],p)});