// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("require exports ../../chunks/_rollupPluginBabelHelpers ../../core/has ../../core/maybe ../../support/arcadeOnDemand ./utils".split(" "),function(r,t,w,G,n,B,q){function C(a,b){return x.apply(this,arguments)}function x(){x=w._asyncToGenerator(function*(a,b){switch(a.type){case "web-style":var {previewWebStyleSymbol:c}=yield new Promise((e,d)=>r(["./previewWebStyleSymbol"],e,d));return c(a,C,b);case "label-3d":case "line-3d":case "mesh-3d":case "point-3d":case "polygon-3d":return{previewSymbol3D:c}=
yield new Promise((e,d)=>r(["./previewSymbol3D"],e,d)),c(a,b);case "simple-marker":case "simple-line":case "simple-fill":case "picture-marker":case "picture-fill":case "text":return{previewSymbol2D:c}=yield new Promise((e,d)=>r(["./previewSymbol2D"],e,d)),c(a,b);case "cim":return{previewCIMSymbol:c}=yield new Promise((e,d)=>r(["./previewCIMSymbol"],e,d)),c(a,b)}});return x.apply(this,arguments)}function y(a){return a&&"opacity"in a?a.opacity*y(a.parent):1}function z(){z=w._asyncToGenerator(function*(a,
b){var c,e;if(a){var d=a.sourceLayer;d=null!=(c=n.isSome(b)&&null!=(e=b.useSourceLayer)&&e?d:a.layer)?c:d;c=y(d);if(n.isSome(a.symbol)&&(!n.isSome(b)||!0!==b.ignoreGraphicSymbol))return a="web-style"===a.symbol.type?yield a.symbol.fetchSymbol(n.isSome(b)?b.abortOptions:null):a.symbol.clone(),q.applyColorToSymbol(a,null,c),a;var g=n.isSome(b)&&b.renderer||d&&"renderer"in d&&d.renderer;if(e=g&&"getSymbolAsync"in g?yield g.getSymbolAsync(a,b):null){e="web-style"===e.type?yield e.fetchSymbol(n.isSome(b)?
b.abortOptions:null):e.clone();if(!("visualVariables"in g&&g.visualVariables&&g.visualVariables.length))return q.applyColorToSymbol(e,null,c),e;"arcadeRequiredForVisualVariables"in g&&g.arcadeRequiredForVisualVariables&&(n.isNone(b)||n.isNone(b.arcade))&&(b={...n.unwrap(b)},b.arcade=yield B.loadArcade());d=yield new Promise((p,u)=>r(["../../renderers/visualVariables/support/visualVariableUtils"],p,u));var k=[],f=[],h=[],l=[];for(var m of g.visualVariables)switch(m.type){case "color":k.push(m);break;
case "opacity":f.push(m);break;case "rotation":l.push(m);break;case "size":m.target||h.push(m)}m=(m=!!k.length&&k[k.length-1])?d.getColor(m,a,b):null;f=(f=!!f.length&&f[f.length-1])?d.getOpacity(f,a,b):null;null!=c&&(f=null!=f?f*c:c);q.applyColorToSymbol(e,m,f);h.length&&(c=d.getAllSizes(h,a,b),yield q.applySizesToSymbol(e,c));for(const p of l)q.applyRotationToSymbol(e,d.getRotationAngle(p,a,b),p.axis);return e}}});return z.apply(this,arguments)}function A(){A=w._asyncToGenerator(function*(a,b){var c;
if(a){var e=y(a.layer||a.sourceLayer);if(n.isSome(a.symbol)&&(!n.isSome(b)||!0!==b.ignoreGraphicSymbol))return a="web-style"===a.symbol.type?yield a.symbol.fetchSymbol(n.isSome(b)?b.abortOptions:null):a.symbol.clone(),q.getColorFromSymbol(a,e);var d=n.isSome(b)&&b.renderer||a.get("layer.renderer")||a.get("sourceLayer.renderer"),g=yield d.getSymbolAsync(a,b);if(g){g="web-style"===g.type?yield g.fetchSymbol(n.isSome(b)?b.abortOptions:null):g.clone();g=q.getColorFromSymbol(g,e);if(!("visualVariables"in
d)||"visualVariables"in d&&!d.visualVariables||"visualVariables"in d&&(null==(c=d.visualVariables)||!c.length))return g;d.arcadeRequiredForVisualVariables&&(n.isNone(b)||n.isNone(b.arcade))&&(b={...n.unwrap(b)},b.arcade=yield B.loadArcade());c=yield new Promise((h,l)=>r(["../../renderers/visualVariables/support/visualVariableUtils"],h,l));var k=[],f=[];for(const h of d.visualVariables)switch(h.type){case "color":k.push(h);break;case "opacity":f.push(h)}d=(d=0<k.length?k[k.length-1]:null)?c.getColor(d,
a,b):g;a=(g=0<f.length?f[f.length-1]:null)?c.getOpacity(g,a,b):null;null!=e&&(a=null!=a?a*e:e);return d?q.applyOpacityToColor(d,a):null}}});return A.apply(this,arguments)}let v=null;t.getDisplayedColor=function(a,b){return A.apply(this,arguments)};t.getDisplayedSymbol=function(a,b){return z.apply(this,arguments)};t.renderColorRampPreviewHTML=function(a,b={}){var c="horizontal"===b.align;const {width:e=c?75:24,height:d=c?24:75,gradient:g=!0}=b;var k=window.devicePixelRatio,f=e*k,h=d*k;k=document.createElement("canvas");
k.width=f;k.height=h;k.style.width=`${e}px`;k.style.height=`${d}px`;const l=k.getContext("2d");var m=c?f:0,p=c?0:h;if(g){const u=l.createLinearGradient(0,0,m,p);c=a.length;const D=1===c?0:1/(c-1);a.forEach((E,F)=>u.addColorStop(F*D,E.toString()));l.fillStyle=u;l.fillRect(0,0,f,h)}else{f=c?f/a.length:f;h=c?h:h/a.length;p=m=0;for(const u of a)l.fillStyle=u.toString(),l.fillRect(m,p,f,h),m=c?m+f:0,p=c?0:p+h}a=document.createElement("div");a.style.width=`${e}px`;a.style.height=`${d}px`;a.style.filter=
q.getCSSFilterFromEffectList(null==b?void 0:b.effectList);a.appendChild(k);return a};t.renderDotDensityPreviewHTML=function(a,b,c){const {backgroundColor:e,outline:d,dotSize:g}=a;c=c&&c.swatchSize||22;const k=Math.round(c*c/g**2*.8),f=window.devicePixelRatio;a=document.createElement("canvas");const h=c*f;a.width=h;a.height=h;a.style.width=`${a.width/f}px`;a.style.height=`${a.height/f}px`;const l=a.getContext("2d");e&&(l.fillStyle=e.toCss(!0),l.fillRect(0,0,h,h),l.fill());l.fillStyle=b.toCss(!0);if(v&&
v.length/2===k)for(b=0;b<2*k;b+=2)l.fillRect(v[b],v[b+1],g*f,g*f),l.fill();else for(v=[],b=0;b<2*k;b+=2){const m=Math.floor(Math.random()*(h-0+1)),p=Math.floor(Math.random()*(h-0+1));v.push(m,p);l.fillRect(m,p,g*f,g*f);l.fill()}d&&(d.color&&(l.strokeStyle=d.color.toCss(!0)),l.lineWidth=d.width,l.strokeRect(0,0,h,h));c=new Image(c,c);c.src=a.toDataURL();return c};t.renderPreviewHTML=C;Object.defineProperty(t,"__esModule",{value:!0})});