// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define(["exports"],function(p){function v(a,c){return"0"!==a.min&&c.length<Number(a.min)||"*"!==a.max&&c.length>Number(a.max)?-2:1}function x(a,c,b){if(null!==b.localScope&&void 0!==b.localScope[a.toLowerCase()]){const d=b.localScope[a.toLowerCase()];if("FormulaFunction"===d.type||"any"===d.type)return void 0===d.signature&&(d.signature={min:"0",max:"*"}),v(d.signature,c)}return void 0!==b.globalScope[a.toLowerCase()]&&(a=b.globalScope[a.toLowerCase()],"FormulaFunction"===a.type||"any"===a.type)?
(void 0===a.signature&&(a.signature={min:"0",max:"*"}),v(a.signature,c)):-1}function t(a,c){if(a)for(const b of a)n(b,c)}function n(a,c){if(a&&!1!==c(a))switch(a.type){case "ArrayExpression":t(a.elements,c);break;case "AssignmentExpression":case "BinaryExpression":n(a.left,c);n(a.right,c);break;case "BlockStatement":t(a.body,c);break;case "CallExpression":n(a.callee,c);t(a.arguments,c);break;case "ExpressionStatement":n(a.expression,c);break;case "ForInStatement":n(a.left,c);n(a.right,c);n(a.body,
c);break;case "ForStatement":n(a.init,c);n(a.test,c);n(a.update,c);n(a.body,c);break;case "FunctionDeclaration":n(a.id,c);t(a.params,c);n(a.body,c);break;case "IfStatement":n(a.test,c);n(a.consequent,c);n(a.alternate,c);break;case "LogicalExpression":n(a.left,c);n(a.right,c);break;case "MemberExpression":n(a.object,c);n(a.property,c);break;case "ObjectExpression":t(a.properties,c);break;case "Program":t(a.body,c);break;case "Property":n(a.key,c);n(a.value,c);break;case "ReturnStatement":n(a.argument,
c);break;case "UnaryExpression":n(a.argument,c);break;case "UpdateExpression":n(a.argument,c);break;case "VariableDeclaration":t(a.declarations,c);break;case "VariableDeclarator":n(a.id,c);n(a.init,c);break;case "TemplateLiteral":t(a.expressions,c),t(a.quasis,c)}}function h(a,c=!0){let b=k(a,"SYNTAX","UNREOGNISED");try{switch(a.type){case "VariableDeclarator":return"Identifier"!==a.id.type?k(a,"SYNTAX","VARIABLEMUSTHAVEIDENTIFIER"):null!==a.init?h(a.init,!1):"";case "VariableDeclaration":for(var d=
0;d<a.declarations.length;d++)if(b=h(a.declarations[d],c),""!==b)return b;return"";case "ForInStatement":b=h(a.left,c);if(""!==b)break;if("VariableDeclaration"===a.left.type){if(1<a.left.declarations.length)return k(a,"SYNTAX","ONLY1VAR");if(null!==a.left.declarations[0].init)return k(a,"SYNTAX","CANNOTDECLAREVAL")}else if("Identifier"!==a.left.type)return k(a,"SYNTAX","LEFTNOTVAR");b=h(a.right,c);if(""!==b)break;b=h(a.body,c);if(""!==b)break;return"";case "ForStatement":if(null!==a.test&&(b=h(a.test,
c),""!==b))break;if(null!==a.init&&(b=h(a.init,c),""!==b))break;if(null!==a.update&&(b=h(a.update,c),""!==b))break;if(null!==a.body&&(b=h(a.body,c),""!==b))break;return"";case "ContinueStatement":return"";case "EmptyStatement":return"";case "BreakStatement":return"";case "IfStatement":b=h(a.test,c);if(""!==b)break;if(null!==a.consequent&&(b=h(a.consequent,!1),""!==b))break;if(null!==a.alternate&&(b=h(a.alternate,!1),""!==b))break;return"";case "BlockStatement":d=[];for(var e=0;e<a.body.length;e++)"EmptyStatement"!==
a.body[e].type&&d.push(a.body[e]);a.body=d;for(d=0;d<a.body.length;d++)if(b=h(a.body[d],c),""!==b)return b;return"";case "FunctionDeclaration":return!1===c?k(a,"SYNTAX","GLOBALFUNCTIONSONLY"):"Identifier"!==a.id.type?k(a,"SYNTAX","FUNCTIONMUSTHAVEIDENTIFIER"):h(a.body,!1);case "ReturnStatement":return null!==a.argument?h(a.argument,c):"";case "UpdateExpression":return"Identifier"!==a.argument.type&&"MemberExpression"!==a.argument.type?k(a,"SYNTAX","ASSIGNMENTTOVARSONLY"):h(a.argument,c);case "AssignmentExpression":if("Identifier"!==
a.left.type&&"MemberExpression"!==a.left.type)return k(a,"SYNTAX","ASSIGNMENTTOVARSONLY");b=h(a.left,c);if(""!==b)break;switch(a.operator){case "\x3d":case "/\x3d":case "*\x3d":case "%\x3d":case "+\x3d":case "-\x3d":break;default:return k(a,"SYNTAX","OPERATORNOTRECOGNISED")}return h(a.right,!1);case "ExpressionStatement":return h(a.expression,!1);case "Identifier":b="";break;case "MemberExpression":b=h(a.object,c);if(""!==b)break;return!0===a.computed?h(a.property,c):"";case "Literal":return"";case "TemplateElement":return"";
case "CallExpression":if("Identifier"!==a.callee.type)return k(a,"SYNTAX","ONLYNODESSUPPORTED");b="";for(d=0;d<a.arguments.length;d++)if(b=h(a.arguments[d],c),""!==b)return b;return"";case "UnaryExpression":b=h(a.argument,c);break;case "BinaryExpression":b=h(a.left,c);if(""!==b)break;b=h(a.right,c);if(""!==b)break;switch(a.operator){case "|":case "\x26":case "\x3e\x3e":case "\x3c\x3c":case "\x3e\x3e":case "\x3e\x3e\x3e":case "^":case "\x3d\x3d":case "!\x3d":case "\x3c":case "\x3c\x3d":case "\x3e":case "\x3e\x3d":case "+":case "-":case "*":case "/":case "%":break;
default:return k(a,"SYNTAX","OPERATORNOTRECOGNISED")}return"";case "LogicalExpression":b=h(a.left,c);if(""!==b)break;b=h(a.right);if(""!==b)break;switch(a.operator){case "\x26\x26":case "||":break;default:return k(a,"SYNTAX","OPERATORNOTRECOGNISED")}return"";case "ArrayExpression":b="";for(d=0;d<a.elements.length&&(b=h(a.elements[d],c),""===b);d++);break;case "TemplateLiteral":b="";for(d=0;d<a.quasis.length;d++)if(b=h(a.quasis[d],c),""!==b)return b;for(d=0;d<a.expressions.length&&(b=h(a.expressions[d],
c),""===b);d++);break;case "ObjectExpression":b="";for(d=0;d<a.properties.length;d++){b="";if(null!==a.properties[d].key&&("Literal"!==a.properties[d].key.type&&"Identifier"!==a.properties[d].key.type&&(b=k(a,"SYNTAX","OBJECTPROPERTYMUSTBESTRING")),"Literal"===a.properties[d].key.type)){e=a.properties[d].key;const f="value"in e?e.value:null;"string"===typeof f||f instanceof String||(b=k(a,"SYNTAX","OBJECTPROPERTYMUSTBESTRING"))}""===b&&(b=h(a.properties[d],c));if(""!==b)break}break;case "Property":if("Literal"!==
a.key.type&&"Identifier"!==a.key.type)return k(a,"SYNTAX","ONLYLITERAL");if("Identifier"!==a.key.type&&(b=h(a.key,c),""!==b))break;b=h(a.value,c)}return b}catch(f){throw f;}}function l(a,c){var b=k(a,"SYNTAX","UNREOGNISED");let d=null,e="";try{switch(a.type){case "VariableDeclarator":{const g=null===a.init?"":l(a.init,c);if(""!==g)return g;"Identifier"===a.id.type&&(null===c.localScope?c.globalScope[a.id.name.toLowerCase()]={type:"any"}:c.localScope[a.id.name.toLowerCase()]={type:"any"});return""}case "FunctionDeclaration":d=
y(a.id.name.toLowerCase(),a);e=A(a,c);if(""!==e)return e;if(null!==c.localScope)return k(a,"SYNTAX","GLOBALFUNCTIONSONLY");d.isnative=!1;c.globalScope[a.id.name.toLowerCase()]={type:"FormulaFunction",signature:[d]};return"";case "VariableDeclaration":b="";for(var f=0;f<a.declarations.length&&(b=l(a.declarations[f],c),""===b);f++);break;case "IfStatement":b=l(a.test,c);if(""!==b)break;if("AssignmentExpression"===a.test.type||"UpdateExpression"===a.test.type)return k(a.test,"SYNTAX","CANNOT_USE_ASSIGNMENT_IN_CONDITION");
if(null!==a.consequent&&(b=l(a.consequent,c),""!==b))break;if(null!==a.alternate&&(b=l(a.alternate,c),""!==b))break;return"";case "EmptyStatement":return"";case "BlockStatement":for(f=0;f<a.body.length;f++)if(b=l(a.body[f],c),""!==b)return b;return"";case "ReturnStatement":return null!==a.argument?l(a.argument,c):"";case "ForInStatement":if("VariableDeclaration"===a.left.type){if(1<a.left.declarations.length)return k(a,"SYNTAX","ONLY1VAR");if(null!==a.left.declarations[0].init)return k(a,"SYNTAX",
"CANNOTDECLAREVAL")}else if("Identifier"!==a.left.type)return k(a,"SYNTAX","LEFTNOTVAR");b=l(a.left,c);if(""!==b)break;b=l(a.right,c);if(""!==b)break;b=l(a.body,c);if(""!==b)break;return"";case "ForStatement":if(null!==a.init&&(b=l(a.init,c),""!==b))break;if(null!==a.test&&(b=l(a.test,c),""!==b))break;if(null!==a.body&&(b=l(a.body,c),""!==b))break;if(null!==a.update&&(b=l(a.update,c),""!==b))break;return"";case "BreakStatement":return"";case "ContinueStatement":return"";case "UpdateExpression":if("Identifier"!==
a.argument.type&&"MemberExpression"!==a.argument.type)return k(a,"SYNTAX","ASSIGNMENTTOVARSONLY");b=!1;if("MemberExpression"===a.argument.type)return l(a.argument,c);null!==c.localScope&&void 0!==c.localScope[a.argument.name.toLowerCase()]&&(b=!0);void 0!==c.globalScope[a.argument.name.toLowerCase()]&&(b=!0);return!1===b?"Identifier "+a.argument.name+" has not been declared.":"";case "AssignmentExpression":if("Identifier"!==a.left.type&&"MemberExpression"!==a.left.type)return k(a,"SYNTAX","ASSIGNMENTTOVARSONLY");
f=l(a.right,c);if(""!==f)return f;b=!1;if("MemberExpression"===a.left.type)return f=l(a.left,c),""!==f?f:"";null!==c.localScope&&void 0!==c.localScope[a.left.name.toLowerCase()]&&(b=!0);void 0!==c.globalScope[a.left.name.toLowerCase()]&&(b=!0);return!1===b?"Identifier "+a.left.name+" has not been declared.":"";case "ExpressionStatement":return l(a.expression,c);case "Identifier":{const g=a.name.toLowerCase();if(null!==c.localScope&&void 0!==c.localScope[g])return"";b=void 0!==c.globalScope[g]?"":
k(a,"SYNTAX","VARIABLENOTFOUND");break}case "MemberExpression":b=l(a.object,c);if(""!==b)break;return!0===a.computed?l(a.property,c):"";case "Literal":return"";case "TemplateElement":return"";case "CallExpression":{if("Identifier"!==a.callee.type)return k(a,"SYNTAX","ONLYNODESSUPPORTED");b="";for(f=0;f<a.arguments.length;f++)if(b=l(a.arguments[f],c),""!==b)return b;const g=x(a.callee.name,a.arguments,c);-1===g&&(b=k(a,"SYNTAX","NOTFOUND"));-2===g&&(b=k(a,"SYNTAX","WRONGSIGNATURE"));break}case "UnaryExpression":b=
l(a.argument,c);break;case "BinaryExpression":b=l(a.left,c);if(""!==b)break;b=l(a.right,c);if(""!==b)break;return"";case "LogicalExpression":b=l(a.left,c);if(""!==b)break;if("AssignmentExpression"===a.left.type||"UpdateExpression"===a.left.type)return k(a.left,"SYNTAX","CANNOT_USE_ASSIGNMENT_IN_CONDITION");b=l(a.right,c);if(""!==b)break;return"AssignmentExpression"===a.right.type||"UpdateExpression"===a.right.type?k(a.right,"SYNTAX","CANNOT_USE_ASSIGNMENT_IN_CONDITION"):"";case "ArrayExpression":b=
"";for(f=0;f<a.elements.length&&(b=l(a.elements[f],c),""===b);f++);break;case "TemplateLiteral":b="";for(f=0;f<a.quasis.length;f++)if(b=l(a.quasis[f],c),""!==b)return b;for(f=0;f<a.expressions.length&&(b=l(a.expressions[f],c),""===b);f++);break;case "ObjectExpression":b="";for(f=0;f<a.properties.length;f++){b="";if(null!==a.properties[f].key&&("Literal"!==a.properties[f].key.type&&"Identifier"!==a.properties[f].key.type&&(b=k(a,"SYNTAX","OBJECTPROPERTYMUSTBESTRING")),"Literal"===a.properties[f].key.type)){const g=
a.properties[f].key,u="value"in g?g.value:null;"string"===typeof u||u instanceof String||(b=k(a,"SYNTAX","OBJECTPROPERTYMUSTBESTRING"))}""===b&&(b=l(a.properties[f],c));if(""!==b)break}break;case "Property":if("Literal"!==a.key.type&&"Identifier"!==a.key.type)return k(a,"SYNTAX","ONLYLITERAL");if("Identifier"!==a.key.type&&(b=l(a.key,c),""!==b))break;b=l(a.value,c)}return b}catch(g){throw g;}}function B(a,c){let b=!1;const d=c.toLowerCase();n(a,e=>{if(b)return!1;"Identifier"===e.type&&e.name&&e.name.toLowerCase()===
d&&(b=!0);return!0});return b}function y(a,c){const b=[];if(void 0!==c.params&&null!==c.params)for(let d=0;d<c.params.length;d++)b.push("any");return{name:a,return:"any",params:b}}function A(a,c){c={globalScope:c.globalScope,localScope:{}};for(let b=0;b<a.params.length;b++)c.localScope[a.params[b].name.toLowerCase()]={type:"any"};return l(a.body,c)}function z(a,c,b,d){const e={};if(void 0===a||null===a)a={};if(void 0===b||null===b)b={};e.infinity={type:"any"};e.textformatting={type:"any"};e.pi={type:"any"};
for(const f in c)"sync"===d&&void 0!==c[f].min?e[f]={type:"FormulaFunction",signature:{min:c[f].min,max:c[f].max}}:"sync"!==d&&void 0!==c[f].fmin&&(e[f]={type:"FormulaFunction",signature:{min:c[f].fmin,max:c[f].fmax}});for(c=0;c<b.length;c++)d=b[c],e[d.name]={type:"FormulaFunction",signature:d};for(const f in a)e[f]=a[f],e[f].type="any";return e}function k(a,c,b){let d="";switch(c){case "SYNTAX":d="Syntax Error: ";break;case "RUNTIME":d="Runtime Error: ";break;default:d="Syntax Error: "}try{switch(a.type){case "IfStatement":switch(b){case "CANNOT_USE_ASSIGNMENT_IN_CONDITION":d+=
" Assignments not be made in logical tests";break;case "CANNOT_USE_NONBOOLEAN_IN_CONDITION":d+=" Non Boolean used as Condition"}break;case "UpdateExpression":case "AssignmentExpression":switch(b){case "CANNOT_USE_ASSIGNMENT_IN_CONDITION":d+=" Assignments not be made in logical tests";break;case "ASSIGNMENTTOVARSONLY":d+=" Assignments can only be made to identifiers"}break;case "ExpressionStatement":d+=" Assignments can only be made to identifiers";break;case "FunctionDeclaration":switch(b){case "GLOBALFUNCTIONSONLY":d+=
" Functions cannot be declared as variables";break;case "FUNCTIONMUSTHAVEIDENTIFIER":d+=" Function Definition must have an identifier"}break;case "VariableDeclaration":d+=" Only 1 variable can be declared at a time";break;case "VariableDeclarator":switch(b){case "FUNCTIONVARIABLEDECLARATOR":d+=" Functions cannot be declared as variables";break;case "VARIABLEMUSTHAVEIDENTIFIER":d+=" Variable Definition must have an identifier"}break;case "Identifier":d+=" Identifier Not Found. ";d+=a.name;break;case "ObjectExpression":switch(b){case "OBJECTPROPERTYMUSTBESTRING":d+=
" Property name must be a string"}break;case "ForStatement":switch(b){case "CANNOT_USE_NONBOOLEAN_IN_CONDITION":d+=" Non Boolean used as Condition"}break;case "ForInStatement":switch(b){case "ONLY1VAR":d+=" Can only declare 1 var for use with IN";break;case "CANNOTDECLAREVAL":d+=" Can only declare value for use with IN";break;case "LEFTNOVAR":d+="Must provide a variable to iterate with.";break;case "VARIABLENOTDECLARED":d+="Variable must be declared before it is used..";break;case "CANNOTITERATETHISTYPE":d+=
"This type cannot be used in an IN loop"}break;case "MemberExpression":switch(b){case "PROPERTYNOTFOUND":d+="Cannot find member property. ";d+=!1===a.computed?"Identifier"===a.property.type?a.property.name:"":"";break;case "OUTOFBOUNDS":d+="Out of Bounds. ";d+=!1===a.computed?"Identifier"===a.property.type?a.property.name:"":"";break;case "NOTFOUND":d+="Cannot call member method on null. ";d+=!1===a.computed?"Identifier"===a.property.type?a.property.name:"":"";break;case "INVALIDTYPE":d+="Cannot call member property on object of this type. ",
d+=!1===a.computed?"Identifier"===a.property.type?a.property.name:"":""}break;case "Property":switch(b){case "ONLYLITERAL":d+="Property names must be literals or identifiers"}break;case "Literal":break;case "CallExpression":switch(b){case "WRONGSIGNATURE":d+="Function signature does not match: ";d+="Identifier"===a.callee.type?a.callee.name:"";break;case "ONLYNODESUPPORTED":d+="Functions must be declared.";d+="Identifier"===a.callee.type?a.callee.name:"";break;case "NOTAFUNCTION":d+="Not a Function: ";
d+="Identifier"===a.callee.type?a.callee.name:"";break;case "NOTFOUND":d+="Function Not Found: "+("Identifier"===a.callee.type?a.callee.name:"")}break;case "UnaryExpression":switch(b){case "NOTSUPPORTEDUNARYOPERATOR":d+="Operator "+a.operator+" not allowed in this context. Only ! can be used with boolean, and - with a number";break;case "NOTSUPPORTEDTYPE":d+="Unary operator "+a.operator+" cannot be used with this argument."}case "BinaryExpression":switch(b){case "OPERATORNOTRECOGNISED":d+="Binary Operator not recognised "+
a.operator}break;case "LogicalExpression":switch(b){case "ONLYBOOLEAN":d+="Operator "+a.operator+" cannot be used. Only || or \x26\x26 are allowed values";break;case "ONLYORORAND":d+="Logical Expression "+a.operator+" being applied to parameters that are not boolean."}break;case "ArrayExpression":switch(b){case "FUNCTIONCONTEXTILLEGAL":d+=" Cannot Put Function inside Array."}break;default:d+="Expression contains unrecognised code structures."}}catch(e){throw e;}return d}function q(a,c,b){return{line:a.loc.start.line,
character:a.loc.start.column,reason:k(a,c,b)}}function C(a,c,b,d){c={globalScope:c.globalScope,localScope:{}};for(let e=0;e<a.params.length;e++)c.localScope[a.params[e].name.toLowerCase()]={type:"any"};m(a.body,c,b,d,!1)}function m(a,c,b,d,e=!0){if(null===a)throw Error("Unnexpexted Expression Syntax");var f=null;try{switch(a.type){case "VariableDeclarator":"Identifier"!==a.id.type?d.push(q(a,"SYNTAX","VARIABLEMUSTHAVEIDENTIFIER")):(a.id.name.toLowerCase(),null===c.localScope?c.globalScope[a.id.name.toLowerCase()]=
{type:"any"}:c.localScope[a.id.name.toLowerCase()]={type:"any"});null!==a.init&&m(a.init,c,b,d,e);break;case "FunctionDeclaration":!1===e&&d.push(q(a,"SYNTAX","GLOBALFUNCTIONSONLY"));"Identifier"!==a.id.type&&d.push(q(a,"SYNTAX","FUNCTIONMUSTHAVEIDENTIFIER"));f=y("",a);C(a,c,b,d);null!==c.localScope&&d.push(q(a,"SYNTAX","GLOBALFUNCTIONSONLY"));f.isnative=!1;"Identifier"===a.id.type&&(c.globalScope[a.id.name.toLowerCase()]={type:"FormulaFunction",signature:[f]});break;case "VariableDeclaration":for(var g=
0;g<a.declarations.length;g++)m(a.declarations[g],c,b,d,e);break;case "IfStatement":null!==a.test&&(m(a.test,c,b,d,e),"AssignmentExpression"!==a.test.type&&"UpdateExpression"!==a.test.type||d.push(q(a.test,"SYNTAX","CANNOT_USE_ASSIGNMENT_IN_CONDITION")));null!==a.consequent&&m(a.consequent,c,b,d,e);null!==a.alternate&&m(a.alternate,c,b,d,e);break;case "EmptyStatement":break;case "BlockStatement":if(null!==a.body)for(g=0;g<a.body.length;g++)m(a.body[g],c,b,d,e);break;case "ReturnStatement":null!==
a.argument&&m(a.argument,c,b,d,e);break;case "ForInStatement":"VariableDeclaration"===a.left.type?(1<a.left.declarations.length&&d.push(q(a,"SYNTAX","ONLY1VAR")),null!==a.left.declarations[0].init&&d.push(q(a,"SYNTAX","CANNOTDECLAREVAL"))):"Identifier"!==a.left.type&&d.push(q(a,"SYNTAX","LEFTNOTVAR"));m(a.left,c,b,d,e);m(a.right,c,b,d,e);m(a.body,c,b,d,e);break;case "ForStatement":null!==a.init&&m(a.init,c,b,d,e);null!==a.test&&m(a.test,c,b,d,e);null!==a.body&&m(a.body,c,b,d,e);null!==a.update&&m(a.update,
c,b,d,e);break;case "BreakStatement":break;case "ContinueStatement":break;case "UpdateExpression":"Identifier"!==a.argument.type&&"MemberExpression"!==a.argument.type?d.push(q(a,"SYNTAX","ASSIGNMENTTOVARSONLY")):("Identifier"===a.argument.type&&(g=!1,!1===b&&(null!==c.localScope&&void 0!==c.localScope[a.argument.name.toLowerCase()]&&(g=!0),void 0!==c.globalScope[a.argument.name.toLowerCase()]&&(g=!0),!1===g&&d.push({line:null===a?0:a.loc.start.line,character:null===a?0:a.loc.start.column,reason:"Identifier "+
a.argument.name+" has not been declared."}))),"MemberExpression"===a.argument.type&&m(a.argument,c,b,d,e));break;case "AssignmentExpression":"Identifier"!==a.left.type&&"MemberExpression"!==a.left.type&&d.push(q(a,"SYNTAX","ASSIGNMENTTOVARSONLY"));switch(a.operator){case "\x3d":case "/\x3d":case "*\x3d":case "%\x3d":case "+\x3d":case "-\x3d":break;default:d.push(q(a,"SYNTAX","OPERATORNOTRECOGNISED"))}m(a.right,c,b,d,e);g=!1;"Identifier"===a.left.type&&(null!==c.localScope&&void 0!==c.localScope[a.left.name.toLowerCase()]&&
(g=!0),void 0!==c.globalScope[a.left.name.toLowerCase()]&&(g=!0),!1===b&&!1===g&&d.push({line:null===a?0:a.loc.start.line,character:null===a?0:a.loc.start.column,reason:"Identifier "+a.left.name+" has not been declared."}));"MemberExpression"===a.left.type&&m(a.left,c,b,d,e);break;case "ExpressionStatement":m(a.expression,c,b,d,e);break;case "Identifier":{const u=a.name.toLowerCase();if(null!==c.localScope&&void 0!==c.localScope[u]||void 0!==c.globalScope[u])break;!1===b&&d.push(q(a,"SYNTAX","VARIABLENOTFOUND"));
break}case "MemberExpression":m(a.object,c,b,d,e);!0===a.computed&&m(a.property,c,b,d,e);break;case "Literal":break;case "TemplateElement":break;case "CallExpression":"Identifier"!==a.callee.type&&d.push(q(a,"SYNTAX","ONLYNODESSUPPORTED"));for(f=0;f<a.arguments.length;f++)m(a.arguments[f],c,b,d,e);"Identifier"===a.callee.type&&(g=x(a.callee.name,a.arguments,c),!1===b&&-1===g&&d.push(q(a,"SYNTAX","NOTFOUND")),-2===g&&d.push(q(a,"SYNTAX","WRONGSIGNATURE")));break;case "UnaryExpression":m(a.argument,
c,b,d,e);break;case "BinaryExpression":m(a.left,c,b,d,e);m(a.right,c,b,d,e);switch(a.operator){case "\x3d\x3d":case "!\x3d":case "\x3c":case "\x3c\x3d":case "\x3e":case "\x3e\x3d":case "+":case "-":case "*":case "/":case "%":case "\x26":case "|":case "^":case "\x3c\x3c":case "\x3e\x3e":case "\x3e\x3e\x3e":break;default:d.push(q(a,"SYNTAX","OPERATORNOTRECOGNISED"))}break;case "LogicalExpression":switch(a.operator){case "\x26\x26":case "||":break;default:d.push(q(a,"SYNTAX","OPERATORNOTRECOGNISED"))}m(a.left,
c,b,d,e);"AssignmentExpression"!==a.left.type&&"UpdateExpression"!==a.left.type||d.push(q(a,"SYNTAX","CANNOT_USE_ASSIGNMENT_IN_CONDITION"));m(a.right,c,b,d,e);"AssignmentExpression"!==a.right.type&&"UpdateExpression"!==a.right.type||d.push(q(a,"SYNTAX","CANNOT_USE_ASSIGNMENT_IN_CONDITION"));break;case "ArrayExpression":for(g=0;g<a.elements.length;g++)m(a.elements[g],c,b,d,e);break;case "TemplateLiteral":for(g=0;g<a.quasis.length;g++)m(a.quasis[g],c,b,d,e);for(g=0;g<a.expressions.length;g++)m(a.expressions[g],
c,b,d,e);break;case "ObjectExpression":for(g=0;g<a.properties.length;g++)m(a.properties[g],c,b,d,e);break;case "Property":"Literal"!==a.key.type&&"Identifier"!==a.key.type&&d.push(q(a,"SYNTAX","ONLYLITERAL"));"Literal"===a.key.type&&m(a.key,c,b,d,e);m(a.value,c,b,d,e);break;default:d.push(q(a,"SYNTAX","UNRECOGNISED"))}}catch(u){d.push({line:null===a?0:a.loc.start.line,character:null===a?0:a.loc.start.column,reason:"Unnexpected Syntax"})}}function w(a){const c=[];n(a,b=>{"CallExpression"===b.type&&
"Identifier"===b.callee.type&&c.push(b.callee.name.toLowerCase());return!0});return c}const r={all:{min:"2",max:"2"},none:{min:"2",max:"2"},any:{min:"2",max:"2"},reduce:{min:"2",max:"3"},map:{min:"2",max:"2"},filter:{min:"2",max:"2"},fromcodepoint:{min:"1",max:"*"},fromcharcode:{min:"1",max:"*"},tocodepoint:{min:"1",max:"2"},tocharcode:{min:"1",max:"2"},concatenate:{min:"0",max:"*"},expects:{min:"1",max:"*"},getfeatureset:{min:"1",max:"2"},week:{min:"1",max:"2"},fromjson:{min:"1",max:"1"},length3d:{min:"1",
max:"2"},tohex:{min:"1",max:"1"},hash:{min:"1",max:"1"},isoweek:{min:"1",max:"1"},isoweekday:{min:"1",max:"1"},isomonth:{min:"1",max:"1"},isoyear:{min:"1",max:"1"},resize:{min:"2",max:"3"},slice:{min:"0",max:"*"},splice:{min:"0",max:"*"},push:{min:"2",max:"2"},pop:{min:"1",max:"1"},includes:{min:"2",max:"2"},array:{min:"1",max:"2"},front:{min:"1",max:"1"},back:{min:"1",max:"1"},insert:{min:"3",max:"3"},erase:{min:"2",max:"2"},split:{min:"2",max:"4"},guid:{min:"0",max:"1"},today:{min:"0",max:"0"},
angle:{min:"2",max:"3"},bearing:{min:"2",max:"3"},urlencode:{min:"1",max:"1"},now:{min:"0",max:"0"},timestamp:{min:"0",max:"0"},day:{min:"1",max:"1"},month:{min:"1",max:"1"},year:{min:"1",max:"1"},hour:{min:"1",max:"1"},second:{min:"1",max:"1"},millisecond:{min:"1",max:"1"},minute:{min:"1",max:"1"},weekday:{min:"1",max:"1"},toutc:{min:"1",max:"1"},tolocal:{min:"1",max:"1"},date:{min:"0",max:"7"},datediff:{min:"2",max:"3"},dateadd:{min:"2",max:"3"},trim:{min:"1",max:"1"},text:{min:"1",max:"2"},left:{min:"2",
max:"2"},right:{min:"2",max:"2"},mid:{min:"2",max:"3"},upper:{min:"1",max:"1"},proper:{min:"1",max:"2"},lower:{min:"1",max:"1"},find:{min:"2",max:"3"},iif:{min:"3",max:"3"},decode:{min:"2",max:"*"},when:{min:"2",max:"*"},defaultvalue:{min:"2",max:"2"},isempty:{min:"1",max:"1"},domaincode:{min:"2",max:"4"},domainname:{min:"2",max:"4"},polygon:{min:"1",max:"1"},point:{min:"1",max:"1"},polyline:{min:"1",max:"1"},extent:{min:"1",max:"1"},multipoint:{min:"1",max:"1"},ringisclockwise:{min:"1",max:"1"},
geometry:{min:"1",max:"1"},count:{min:"0",max:"*"},number:{min:"1",max:"2"},acos:{min:"1",max:"1"},asin:{min:"1",max:"1"},atan:{min:"1",max:"1"},atan2:{min:"2",max:"2"},ceil:{min:"1",max:"2"},floor:{min:"1",max:"2"},round:{min:"1",max:"2"},cos:{min:"1",max:"1"},exp:{min:"1",max:"1"},log:{min:"1",max:"1"},min:{min:"0",max:"*"},constrain:{min:"3",max:"3"},console:{min:"0",max:"*"},max:{min:"0",max:"*"},pow:{min:"2",max:"2"},random:{min:"0",max:"0"},sqrt:{min:"1",max:"1"},sin:{min:"1",max:"1"},tan:{min:"1",
max:"1"},abs:{min:"1",max:"1"},isnan:{min:"1",max:"1"},stdev:{min:"0",max:"*"},average:{min:"0",max:"*"},mean:{min:"0",max:"*"},sum:{min:"0",max:"*"},variance:{min:"0",max:"*"},distinct:{min:"0",max:"*"},first:{min:"1",max:"1"},top:{min:"2",max:"2"},boolean:{min:"1",max:"1"},dictionary:{min:"0",max:"*"},typeof:{min:"1",max:"1"},reverse:{min:"1",max:"1"},replace:{min:"3",max:"4"},sort:{min:"1",max:"2"},feature:{min:"1",max:"*"},haskey:{min:"2",max:"2"},indexof:{min:"2",max:"2"},disjoint:{min:"2",max:"2"},
intersects:{min:"2",max:"2"},touches:{min:"2",max:"2"},crosses:{min:"2",max:"2"},within:{min:"2",max:"2"},contains:{min:"2",max:"2"},overlaps:{min:"2",max:"2"},equals:{min:"2",max:"2"},relate:{min:"3",max:"3"},intersection:{min:"2",max:"2"},union:{min:"1",max:"2"},difference:{min:"2",max:"2"},symmetricdifference:{min:"2",max:"2"},clip:{min:"2",max:"2"},cut:{min:"2",max:"2"},area:{min:"1",max:"2"},areageodetic:{min:"1",max:"2"},length:{min:"1",max:"2"},lengthgeodetic:{min:"1",max:"2"},distancegeodetic:{min:"2",
max:"3"},distance:{min:"2",max:"3"},densify:{min:"2",max:"3"},densifygeodetic:{min:"2",max:"3"},generalize:{min:"2",max:"4"},buffer:{min:"2",max:"3"},buffergeodetic:{min:"2",max:"3"},offset:{min:"2",max:"6"},rotate:{min:"2",max:"3"},issimple:{min:"1",max:"1"},simplify:{min:"1",max:"1"},centroid:{min:"1",max:"1"},isselfintersecting:{min:"1",max:"1"},multiparttosinglepart:{min:"1",max:"1"},setgeometry:{min:"2",max:"2"},portal:{min:"1",max:"1"},getuser:{min:"1",max:"2"},subtypes:{min:"1",max:"1"},subtypecode:{min:"1",
max:"1"},subtypename:{min:"1",max:"1"},domain:{min:"2",max:"3"},convertdirection:{min:"3",max:"3"},schema:{min:"1",max:"1"}};for(const a in r)r[a].fmin=r[a].min,r[a].fmax=r[a].max;const D="featureset getuser featuresetbyid featuresetbyname featuresetbyassociation featuresetbyrelationshipname featuresetbyurl getfeatureset attachments featuresetbyportalitem".split(" "),E="disjoint intersects touches crosses within contains overlaps equals relate intersection union difference symmetricdifference clip cut area areageodetic length length3d lengthgeodetic distance distancegeodetic densify densifygeodetic generalize buffer buffergeodetic offset rotate issimple simplify multiparttosinglepart".split(" ");
p.addFunctionDeclaration=function(a,c){const b=r[a.name.toLowerCase()];void 0===b?"sync"===c?r[a.name.toLowerCase()]={min:a.min,max:a.max}:r[a.name.toLowerCase()]={fmin:a.min,fmax:a.max}:"sync"===c?(b.min=a.min,b.max=a.max):(b.fmin=a.min,b.fmax=a.max)};p.checkFunctionSignature=v;p.checkScript=function(a,c,b,d="async",e=r){const f=[];if("BlockStatement"!==a.body[0].body.type)return[{line:0,character:0,reason:"Invalid Body"}];if(null===c||void 0===c)c={vars:{},customFunctions:[]};c={globalScope:z(c.vars,
e,c.customFunctions,d),localScope:null};try{m(a.body[0].body,c,b,f)}catch(g){}return f};p.constructGlobalScope=z;p.extractAllIssues=m;p.extractAllIssuesInFunction=C;p.extractFunctionDeclaration=y;p.findExpectedFieldLiterals=function(a){const c=[];n(a,b=>{if("CallExpression"===b.type&&"Identifier"===b.callee.type&&"expects"===b.callee.name.toLowerCase()){let e="";for(let f=0;f<(b.arguments||[]).length;f++)if(0===f)"Identifier"===b.arguments[f].type&&(e=b.arguments[f].name.toLowerCase());else{var d;
if(d=e&&"Literal"===b.arguments[f].type)d=b.arguments[f].value,d="string"===typeof d||d instanceof String;d&&c.push(e+"."+b.arguments[f].value.toLowerCase())}return!1}if("MemberExpression"!==b.type||"Identifier"!==b.object.type)return!0;!1===b.computed&&b.object&&b.object.name&&b.property&&"Identifier"===b.property.type&&b.property.name?c.push(b.object.name.toLowerCase()+"."+b.property.name.toLowerCase()):b.object&&b.object.name&&b.property&&"Literal"===b.property.type&&"string"===typeof b.property.value&&
c.push(b.object.name.toLowerCase()+"."+b.property.value.toString().toLowerCase());return!1});return c};p.findFieldLiterals=function(a){const c=[];n(a,b=>{if("MemberExpression"!==b.type||"Identifier"!==b.object.type)return!0;!1===b.computed&&b.object&&b.object.name&&b.property&&"Identifier"===b.property.type&&b.property.name?c.push(b.object.name.toLowerCase()+"."+b.property.name.toLowerCase()):b.object&&b.object.name&&b.property&&"Literal"===b.property.type&&"string"===typeof b.property.value&&c.push(b.object.name.toLowerCase()+
"."+b.property.value.toString().toLowerCase());return!1});return c};p.findFunction=x;p.findFunctionCalls=w;p.findScriptDependencies=function(a,c=[]){let b=null;if(void 0===a.usesFeatureSet){null===b&&(b=w(a));a.usesFeatureSet=!1;for(let d=0;d<b.length;d++)-1<D.indexOf(b[d])&&(a.usesFeatureSet=!0,a.isAsync=!0);if(!1===a.usesFeatureSet&&c&&0<c.length)for(const d of c)if(B(a,d)){a.usesFeatureSet=!0;a.isAsync=!0;break}}if(void 0===a.usesGeometry)for(a.usesGeometry=!1,null===b&&(b=w(a)),c=0;c<b.length;c++)-1<
E.indexOf(b[c])&&(a.usesGeometry=!0)};p.functionDecls=r;p.makeError=q;p.nodeErrorMessage=k;p.referencesFunction=function(a,c){let b=!1;const d=c.toLowerCase();n(a,e=>b?!1:"CallExpression"===e.type&&"Identifier"===e.callee.type&&e.callee.name&&e.callee.name.toLowerCase()===d?(b=!0,!1):!0);return b};p.referencesMember=B;p.scriptUsesFeatureSet=function(a){a=w(a);for(let c=0;c<a.length;c++)if(-1<D.indexOf(a[c]))return!0;return!1};p.testValidityOfExpression=l;p.validateFunction=A;p.validateLanguage=function(a){return"BlockStatement"!==
a.body[0].body.type?"Invalid formula content.":h(a.body[0].body)};p.validateLanguageNode=h;p.validateScript=function(a,c,b="async",d=r){c={globalScope:z(c.vars,d,c.customFunctions,b),localScope:null};return l(a.body[0].body,c)};p.walk=n;Object.defineProperty(p,"__esModule",{value:!0})});