// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/promiseUtils ../../../../renderers/support/heatmapUtils ../../../statistics/support/predominanceUtils ../../utils ../../../../statistics/utils".split(" "),function(m,E,F,A,G,p,H){function x(){x=E._asyncToGenerator(function*(a,c,b){const d=[];if(c)for(const f of c)c=a.getField(f),"availableFields"in b&&-1===b.availableFields.indexOf(c.name)&&d.push(c.name);return d});return x.apply(this,arguments)}function B(a){const {field:c,
normalizationType:b,normalizationField:d,normalizationTotal:f,layer:k}=a;a=p.isIntegerField(k,c);let l=c;"percent-of-total"===b?l=`((${a?p.castIntegerFieldToFloat(c):c} / ${f}) * 100)`:"log"===b?l=`(log(${c}) * ${I})`:"field"===b?l=`(${a?p.castIntegerFieldToFloat(c):c} / ${d})`:"natural-log"===b?l=`(log(${a?p.castIntegerFieldToFloat(c):c}))`:"square-root"===b&&(l=`(power(${a?p.castIntegerFieldToFloat(c):c}, 0.5))`);return l}function C(a,c){let b;c=c.toLowerCase();if(a)for(const d in a)if(d.toLowerCase()!==
c){b=a[d];break}return b}function y(a,c){let b;c=c.toLowerCase();if(a)for(const d in a)if(d.toLowerCase()===c){b=a[d];break}return b}function z(a,c){if(c)for(const b in a)a[b].label=c[b];return{count:a}}const J=/_value$/i,I=Math.LOG10E;m.calculateHeatmapStats=function(a,c=10,b,d,f,k){const l=new Float64Array(f*k),g=A.createKernel(c);c=Math.round(3*c);let h=Number.POSITIVE_INFINITY,n=Number.NEGATIVE_INFINITY;var e=0;let t=0,D=0,q=0;b=A.createValueFunction(d,b);for(const {geometry:u,attributes:K}of a){a=
u.x-c;d=u.y-c;const L=Math.max(0,a);e=Math.max(0,d);const M=Math.min(k,u.y+c),N=Math.min(f,u.x+c),O=+b(K);for(let v=e;v<M;v++){const P=g[v-d];for(let w=L;w<N;w++){e=v*f+w;var r=l[e];e=l[e]+=P*g[w-a]*O;r=e-r;t+=r;D+=r*r;e<h&&(h=e);e>n&&(n=e);q++}}}return q?{mean:t/q,stdDev:Math.sqrt((D-t*t/q)/q),min:h,max:n,mid:(n-h)/2,count:q}:{mean:0,stddev:0,min:0,max:0,mid:0,count:0}};m.ensureFeaturesJSON=function(a){return a.map(c=>c.toJSON())};m.generateBinParams=function(a){const c=[],b=a.classBreaks,d=b[0].minValue,
f=b[b.length-1].maxValue;b.forEach(k=>{c.push([k.minValue,k.maxValue])});return{min:d,max:f,intervals:c,sqlExpr:B({field:a.field,normalizationType:a.normalizationType,normalizationField:a.normalizationField,normalizationTotal:a.normalizationTotal,layer:a.layer}),excludeZerosExpr:a.where,normTotal:a.normalizationTotal}};m.getFieldExpr=B;m.getHistogramFromFeatureSet=function(a,c,b,d,f){const k={};a&&a.features&&a.features.forEach(g=>{var h=g.attributes;g=C(h,"countOFExpr");h=y(h,"countOFExpr");0!==
g&&(k[g]=h)});const l=[];H.getEqualIntervalBins(c,b,d).forEach((g,h)=>{h=(h+1).toString();l.push({minValue:g[0],maxValue:g[1],count:k.hasOwnProperty(h)?k[h]:0})});return{bins:l,minValue:c,maxValue:b,normalizationTotal:f}};m.getMissingFields=function(a,c,b){return x.apply(this,arguments)};m.getPredominantCategoriesFromUVInfos=function(a,c){const b=a.map(f=>f.value),d=c.filter(f=>-1===b.indexOf(f));for(const f of d)a.push({value:f,count:0});a.sort((f,k)=>c.indexOf(f.value)-c.indexOf(k.value));for(const f of a)f.value===
G.noDominantCategoryField&&(f.value=null);return{predominantCategoryInfos:a}};m.getSummaryStatisticsFromFeatureSet=function(a,c){a=(a=a&&a.features)&&a[0]&&a[0].attributes;const b={};for(const d in a)b[d.replace(J,"").toLowerCase()]=a[d];null!=b.totalcount&&b.totalcount>=b.count&&(b.nullcount=b.totalcount-b.count);delete b.totalcount;b.min===b.max&&null!=b.min&&null==b.stddev&&(b.stddev=b.variance=0);c&&("min max avg stddev sum variance".split(" ").forEach(d=>{null!=b[d]&&(b[d]=Math.ceil(b[d]))}),
b.min===b.max&&null!=b.min&&(b.avg=b.min,b.stddev=b.variance=0));return b};m.getUniqueValuesFromFeatureSet=function(a,c,b,d,f,k){const l="countOF"+(b||"Expr"),g={};let h=!1;(a&&a.features).forEach(n=>{var e=n.attributes;n=y(e,l);e=b?y(e,b):C(e,l);null===e&&0===n&&(h=!0);if(null==e||"string"===typeof e&&""===e.trim())e=null;null==g[e]?g[e]={count:n,data:e}:g[e].count+=n});return b&&h?c.queryFeatureCount({whereClause:b+" is NULL",view:d,signal:k}).then(n=>{g["null"].count+=n||0;return z(g,f)}).catch(()=>
{F.throwIfAborted(k);return z(g,f)}):Promise.resolve(z(g,f))};m.getViewInfoParams=function(a){var c;return{viewingMode:"2d"===a.type?"map":a.viewingMode,scale:a.scale,spatialReference:null==(c=a.spatialReference)?void 0:c.toJSON()}};m.msSinceUnixEpochSQL=function(a,c){return p.getDateDiffSQL(a,new Date(0),c,"milliseconds").sqlExpression};Object.defineProperty(m,"__esModule",{value:!0})});