// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
define(["exports","../rest/support/ClassBreaksDefinition","../rest/support/generateRendererUtils"],function(m,E,F){function u(a){const b=null!=a.minValue||null!=a.maxValue,c=!!a.sqlExpression&&a.supportsSQLExpression;return!(null!=a.normalizationField||null!=a.normalizationType)&&!b&&!c}function v(a){const {values:b,useSampleStdDev:c,supportsNullCount:e}=a;var g=Number.POSITIVE_INFINITY;let f=Number.NEGATIVE_INFINITY,d=null,k=null;var h=null;let p=null,l=0;const q=null==a.minValue?-Infinity:a.minValue,
r=null==a.maxValue?Infinity:a.maxValue;for(const n of b)Number.isFinite(n)?n>=q&&n<=r&&(d+=n,g=Math.min(g,n),f=Math.max(f,n),l++):"string"===typeof n&&l++;if(l&&null!=d){k=d/l;h=0;for(const n of b)Number.isFinite(n)&&n>=q&&n<=r&&(h+=(n-k)**2);p=c?1<l?h/(l-1):0:0<l?h/l:0;h=Math.sqrt(p)}else f=g=null;g={avg:k,count:l,max:f,min:g,stddev:h,sum:d,variance:p};e&&(g.nullcount=b.length-l);a.percentileParams&&(g.median=t(b,a.percentileParams));return g}function t(a,b){const {fieldType:c,value:e,orderBy:g,
isDiscrete:f}=b,d=w(c,"desc"===g);a=[...a].filter(l=>null!=l).sort((l,q)=>d(l,q));if(0===a.length)return null;if(0>=e)return a[0];if(1<=e)return a[a.length-1];var k=(a.length-1)*e,h=Math.floor(k);b=h+1;k%=1;h=a[h];const p=a[b];return b>=a.length||f||"string"===typeof h||"string"===typeof p?h:h*(1-k)+p*k}function w(a,b){const c=b?1:-1,e=G(b),g=x(b);if(!a||!["esriFieldTypeDate","esriFieldTypeString","esriFieldTypeGUID","esriFieldTypeGlobalID",...y].includes(a))return(f,d)=>"number"===typeof f&&"number"===
typeof d?e(f,d):"string"===typeof f&&"string"===typeof d?g(f,d):c;if("esriFieldTypeDate"===a)return(f,d)=>{f=(new Date(f)).getTime();d=(new Date(d)).getTime();return isNaN(f)||isNaN(d)?c:e(f,d)};if(y.has(a))return(f,d)=>e(f,d);if("esriFieldTypeString"===a)return(f,d)=>g(f,d);if("esriFieldTypeGUID"===a||"esriFieldTypeGlobalID"===a){const f=x(b);return(d,k)=>f(z(d),z(k))}return b?(f,d)=>1:(f,d)=>-1}function x(a){return a?(b,c)=>{b=b.toUpperCase();c=c.toUpperCase();return b>c?-1:b<c?1:0}:(b,c)=>{b=b.toUpperCase();
c=c.toUpperCase();return b<c?-1:b>c?1:0}}function G(a){return a?(b,c)=>c-b:(b,c)=>b-c}function z(a){return a.substr(24,12)+a.substr(19,4)+a.substr(16,2)+a.substr(14,2)+a.substr(11,2)+a.substr(9,2)+a.substr(6,2)+a.substr(4,2)+a.substr(2,2)+a.substr(0,2)}function A(a,b){const c=B({field:b.field,normalizationType:b.normalizationType,normalizationField:b.normalizationField,classificationMethod:b.classificationMethod,standardDeviationInterval:b.standardDeviationInterval,breakCount:b.numClasses||5});a=
H(a,b.minValue,b.maxValue);return F.createGenerateRendererClassBreaks({definition:c,values:a,normalizationTotal:b.normalizationTotal})}function H(a,b,c){b=null==b?-Infinity:b;c=null==c?Infinity:c;return a.filter(e=>Number.isFinite(e)&&e>=b&&e<=c)}function B(a){const b=a.field,c=a.classificationMethod||"equal-interval",e=a.normalizationType,g=a.normalizationField,f=new E;f.classificationField=b;f.breakCount=a.breakCount;f.classificationMethod=c;f.standardDeviationInterval="standard-deviation"===c?
a.standardDeviationInterval||1:void 0;f.normalizationType=e;f.normalizationField="field"===e?g:void 0;return f}function I(a,b){const {field:c,classificationMethod:e,standardDeviationInterval:g,normalizationType:f,normalizationField:d,normalizationTotal:k,minValue:h,maxValue:p}=b,l=b.numBins||10;let q=b=null,r=null;e&&"equal-interval"!==e||f?({classBreaks:a}=A(a,{field:c,normalizationType:f,normalizationField:d,normalizationTotal:k,classificationMethod:e,standardDeviationInterval:g,minValue:h,maxValue:p,
numClasses:l}),b=a[0].minValue,q=a[a.length-1].maxValue,r=a.map(n=>[n.minValue,n.maxValue])):(null!=h&&null!=p?(b=h,q=p):(a=v({values:a,minValue:h,maxValue:p,useSampleStdDev:!f,supportsNullCount:u({normalizationType:f,normalizationField:d,minValue:h,maxValue:p})}),b=a.min,q=a.max),r=C(b,q,l));return{min:b,max:q,intervals:r}}function J(a,b){let c=-1;for(let e=a.length-1;0<=e;e--)if(b>=a[e][0]){c=e;break}return c}function C(a,b,c){const e=(b-a)/c,g=[];let f;for(let d=1;d<=c;d++)f=a+e,f=Number(f.toFixed(16)),
g.push([a,d===c?b:f]),a=f;return g}const K=/\s*(\+|-)?((\d+(\.\d+)?)|(\.\d+))\s*/gi,y=new Set(["esriFieldTypeInteger","esriFieldTypeSmallInteger","esriFieldTypeSingle","esriFieldTypeDouble"]),D="min max avg stddev count sum variance nullcount median".split(" ");m.calculateClassBreaks=A;m.calculateHistogram=function(a,b){const {min:c,max:e,intervals:g}=I(a,b),f=g.map((d,k)=>({minValue:g[k][0],maxValue:g[k][1],count:0}));for(const d of a)null!=d&&d>=c&&d<=e&&(a=J(g,d),-1<a&&f[a].count++);return{bins:f,
minValue:c,maxValue:e,normalizationTotal:b.normalizationTotal}};m.calculatePercentile=t;m.calculateStatistics=v;m.calculateStringStatistics=function(a){const b=a.returnDistinct?[...new Set(a.values)]:a.values,c=b.filter(g=>null!=g).length,e={count:c};a.supportsNullCount&&(e.nullcount=b.length-c);a.percentileParams&&(e.median=t(b,a.percentileParams));return e};m.calculateUniqueValuesCount=function(a){const b={};for(let c of a){if(null==c||"string"===typeof c&&""===c.trim())c=null;null==b[c]?b[c]={count:1,
data:c}:b[c].count++}return{count:b}};m.createClassBreaksDefinition=B;m.createUVResult=function(a,b,c){const e=a.count;a=[];c&&b&&"coded-value"===b.type&&b.codedValues.forEach(g=>{g=g.code;e.hasOwnProperty(g)||(e[g]={data:g,count:0})});for(const g in e)b=e[g],a.push({value:b.data,count:b.count,label:b.label});return{uniqueValueInfos:a}};m.getAttributeComparator=w;m.getEqualIntervalBins=C;m.getNormalizedValue=function(a,b,c,e){let g=null;switch(b){case "log":0!==a&&(g=Math.log(a)*Math.LOG10E);break;
case "percent-of-total":Number.isFinite(e)&&0!==e&&(g=a/e*100);break;case "field":Number.isFinite(c)&&0!==c&&(g=a/c);break;case "natural-log":0<a&&(g=Math.log(a));break;case "square-root":0<a&&(g=a**.5)}return g};m.isNullCountSupported=u;m.processSummaryStatisticsResult=function(a,b){let c;for(c in a)-1<D.indexOf(c)&&(Number.isFinite(a[c])||(a[c]=null));if(!b)return a;["avg","stddev","variance"].forEach(e=>{null!=a[e]&&(a[e]=Math.ceil(a[e]))});return a};m.resolveCBResult=function(a,b){let c=a.classBreaks;
const e=c[0].minValue,g=c[c.length-1].maxValue,f="standard-deviation"===b;c=c.map(d=>{const k=d.label;d={minValue:d.minValue,maxValue:d.maxValue,label:k};if(f&&k){const h=k.match(K).map(p=>+p.trim());2===h.length?(d.minStdDev=h[0],d.maxStdDev=h[1],0>h[0]&&0<h[1]&&(d.hasAvg=!0)):1===h.length&&(k.includes("\x3c")?(d.minStdDev=null,d.maxStdDev=h[0]):k.includes("\x3e")&&(d.minStdDev=h[0],d.maxStdDev=null))}return d});return{minValue:e,maxValue:g,classBreakInfos:c,normalizationTotal:a.normalizationTotal}};
m.statisticTypes=D;Object.defineProperty(m,"__esModule",{value:!0})});