// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.22/esri/copyright.txt for details.
//>>built
require({cache:{"esri/core/sql/AggregateFunctions":function(){define(["exports"],function(O){function ma(h){let r=0;for(let x=0;x<h.length;x++)r+=h[x];return r/h.length}function ba(h){const r=ma(h),x=h.length;let g=0;for(const A of h)g+=(A-r)**2;return 1<x?g/(x-1):0}const ca={min:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:Math.min.apply(Math,h[0])},max:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:Math.max.apply(Math,h[0])},avg:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:
ma(h[0])},sum:{minParams:1,maxParams:1,evaluate:h=>{if(null==h[0])h=null;else{{h=h[0];let r=0;for(let x=0;x<h.length;x++)r+=h[x];h=r}}return h}},stddev:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:Math.sqrt(ba(h[0]))},count:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:h[0].length},var:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:ba(h[0])}};O.aggregateFunction=function(h,r){const x=ca[h.toLowerCase()];if(null==x)throw Error("Function Not Recognised");if(r.length<x.minParams||
r.length>x.maxParams)throw Error(`Invalid Parameter count for call to ${h.toUpperCase()}`);return x.evaluate(r)};O.isAggregate=function(h,r){h=ca[h.toLowerCase()];return null!=h&&r>=h.minParams&&r<=h.maxParams};Object.defineProperty(O,"__esModule",{value:!0})})},"esri/core/sql/StandardizedFunctions":function(){define(["exports","../string"],function(O,ma){let ba=function(){function h(){this.op="+";this.minute=this.year=this.month=this.hour=this.second=this.day=0}h.fixDefaults=function(r){if(null!==
r.precision||null!==r.secondary)throw Error("Primary and Secondary SqlInterval qualifiers not supported");};h.createFromMilliseconds=function(r){const x=new h;x.second=r/1E3;return x};h.createFromValueAndQualifer=function(r,x,g){let A=null;const t=new h;t.op="-"===g?"-":"+";if("interval-period"===x.type){h.fixDefaults(x);if("year"===x.period||"month"===x.period)throw Error("Year-Month Intervals not supported");if(/^[0-9]{1,}$/.test(r))t[x.period]=parseFloat(r);else throw Error("Illegal Interval");
}else{h.fixDefaults(x.start);h.fixDefaults(x.end);if("year"===x.start.period||"month"===x.start.period)throw Error("Year-Month Intervals not supported");if("year"===x.end.period||"month"===x.end.period)throw Error("Year-Month Intervals not supported");switch(x.start.period){case "day":switch(x.end.period){case "hour":A=/^[0-9]{1,} [0-9]{1,}$/;if(A.test(r))t[x.start.period]=parseFloat(r.split(" ")[0]),t[x.end.period]=parseFloat(r.split(" ")[1]);else throw Error("Illegal Interval");break;case "minute":A=
/^[0-9]{1,} [0-9]{1,2}:[0-9]{1,}$/;if(A.test(r))t[x.start.period]=parseFloat(r.split(" ")[0]),r=r.split(" ")[1].split(":"),t.hour=parseFloat(r[0]),t.minute=parseFloat(r[1]);else throw Error("Illegal Interval");break;case "second":A=/^[0-9]{1,} [0-9]{1,2}:[0-9]{1,2}:[0-9]{1,}([.]{1}[0-9]{1,}){0,1}$/;if(A.test(r))t[x.start.period]=parseFloat(r.split(" ")[0]),r=r.split(" ")[1].split(":"),t.hour=parseFloat(r[0]),t.minute=parseFloat(r[1]),t.second=parseFloat(r[2]);else throw Error("Illegal Interval");
break;default:throw"Invalid Interval.";}break;case "hour":switch(x.end.period){case "minute":A=/^[0-9]{1,}:[0-9]{1,}$/;if(A.test(r))t.hour=parseFloat(r.split(":")[0]),t.minute=parseFloat(r.split(":")[1]);else throw Error("Illegal Interval");break;case "second":A=/^[0-9]{1,}:[0-9]{1,2}:[0-9]{1,}([.]{1}[0-9]{1,}){0,1}$/;if(A.test(r))r=r.split(":"),t.hour=parseFloat(r[0]),t.minute=parseFloat(r[1]),t.second=parseFloat(r[2]);else throw Error("Illegal Interval");break;default:throw"Invalid Interval.";}break;
case "minute":switch(x.end.period){case "second":A=/^[0-9]{1,}:[0-9]{1,}([.]{1}[0-9]{1,}){0,1}$/;if(A.test(r))r=r.split(":"),t.minute=parseFloat(r[0]),t.second=parseFloat(r[1]);else throw Error("Illegal Interval");break;default:throw"Invalid Interval.";}break;default:throw"Invalid Interval.";}}return t};h.prototype.valueInMilliseconds=function(){return("-"===this.op?-1:1)*(1E3*this.second+6E4*this.minute+36E5*this.hour+864E5*this.day+365/12*this.month*864E5+31536E6*this.year)};return h}();const ca=
{extract:{minParams:2,maxParams:2,evaluate:([h,r])=>{if(null==r)return null;if(r instanceof Date)switch(h.toUpperCase()){case "SECOND":return r.getSeconds();case "MINUTE":return r.getMinutes();case "HOUR":return r.getHours();case "DAY":return r.getDate();case "MONTH":return r.getMonth()+1;case "YEAR":return r.getFullYear()}throw Error("Invalid Parameter for call to EXTRACT");}},substring:{minParams:2,maxParams:3,evaluate:h=>{if(2===h.length){const [r,x]=h;return null==r||null==x?null:r.toString().substring(x-
1)}if(3===h.length){const [r,x,g]=h;return null==r||null==x||null==g?null:0>=g?"":r.toString().substring(x-1,x+g-1)}}},position:{minParams:2,maxParams:2,evaluate:([h,r])=>null==h||null==r?null:r.indexOf(h)+1},trim:{minParams:2,maxParams:3,evaluate:h=>{var r=3===h.length,x=r?h[1]:" ";r=r?h[2]:h[1];if(null==x||null==r)return null;x=`(${ma.escapeRegExpString(x)})`;switch(h[0]){case "BOTH":return r.replace(new RegExp(`^${x}*|${x}*$`,"g"),"");case "LEADING":return r.replace(new RegExp(`^${x}*`,"g"),"");
case "TRAILING":return r.replace(new RegExp(`${x}*$`,"g"),"")}throw Error("Invalid Parameter for call to TRIM");}},abs:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:Math.abs(h[0])},ceiling:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:Math.ceil(h[0])},floor:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:Math.floor(h[0])},log:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:Math.log(h[0])},log10:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:Math.log(h[0])*Math.LOG10E},
sin:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:Math.sin(h[0])},cos:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:Math.cos(h[0])},tan:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:Math.tan(h[0])},asin:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:Math.asin(h[0])},acos:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:Math.acos(h[0])},atan:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:Math.atan(h[0])},sign:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:
0<h[0]?1:0>h[1]?-1:0},power:{minParams:2,maxParams:2,evaluate:h=>null==h[0]||null==h[1]?null:h[0]**h[1]},mod:{minParams:2,maxParams:2,evaluate:h=>null==h[0]||null==h[1]?null:h[0]%h[1]},round:{minParams:1,maxParams:2,evaluate:h=>{const r=h[0];h=2===h.length?10**h[1]:1;return null==r?null:Math.round(r*h)/h}},truncate:{minParams:1,maxParams:2,evaluate:h=>null==h[0]?null:1===h.length?parseInt(h[0].toFixed(0),10):parseFloat(h[0].toFixed(h[1]))},char_length:{minParams:1,maxParams:1,evaluate:h=>"string"===
typeof h[0]||h[0]instanceof String?h[0].length:0},concat:{minParams:1,maxParams:Infinity,evaluate:h=>{let r="";for(let x=0;x<h.length;x++){if(null==h[x])return null;r+=h[x].toString()}return r}},lower:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:h[0].toString().toLowerCase()},upper:{minParams:1,maxParams:1,evaluate:h=>null==h[0]?null:h[0].toString().toUpperCase()}};O.SqlInterval=ba;O.evaluateFunction=function(h,r){const x=ca[h.toLowerCase()];if(null==x)throw Error("Function Not Recognised");
if(r.length<x.minParams||r.length>x.maxParams)throw Error(`Invalid Parameter count for call to ${h.toUpperCase()}`);return x.evaluate(r)};O.isStandardized=function(h,r){h=ca[h.toLowerCase()];return null!=h&&r>=h.minParams&&r<=h.maxParams};Object.defineProperty(O,"__esModule",{value:!0})})},"esri/core/sql/WhereGrammar":function(){define(["exports","../../chunks/_commonjsHelpers"],function(O,ma){var ba={exports:{}};(function(h){(function(r,x){h.exports&&(h.exports=x())})(ma.commonjsGlobal,function(){function r(g,
A,t,F){g=Error.call(this,g);Object.setPrototypeOf&&Object.setPrototypeOf(g,r.prototype);g.expected=A;g.found=t;g.location=F;g.name="SyntaxError";return g}function x(g,A,t){t=t||" ";if(g.length>A)return g;A-=g.length;t+=t.repeat(A);return g+t.slice(0,A)}(function(g,A){function t(){this.constructor=g}t.prototype=A.prototype;g.prototype=new t})(r,Error);r.prototype.format=function(g){var A="Error: "+this.message;if(this.location){var t=null,F;for(F=0;F<g.length;F++)if(g[F].source===this.location.source){t=
g[F].text.split(/\r\n|\n|\r/g);break}g=this.location.start;F=this.location.source+":"+g.line+":"+g.column;if(t){var N=this.location.end,da=x("",g.line.toString().length);t=t[g.line-1];N=g.line===N.line?N.column:t.length+1;A+="\n --\x3e "+F+"\n"+da+" |\n"+g.line+" | "+t+"\n"+da+" | "+x("",g.column-1)+x("",N-g.column,"^")}else A+="\n at "+F}return A};r.buildMessage=function(g,A){function t(D){return D.charCodeAt(0).toString(16).toUpperCase()}function F(D){return D.replace(/\\/g,"\\\\").replace(/"/g,
'\\"').replace(/\0/g,"\\0").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/[\x00-\x0F]/g,function(I){return"\\x0"+t(I)}).replace(/[\x10-\x1F\x7F-\x9F]/g,function(I){return"\\x"+t(I)})}function N(D){return D.replace(/\\/g,"\\\\").replace(/\]/g,"\\]").replace(/\^/g,"\\^").replace(/-/g,"\\-").replace(/\0/g,"\\0").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/[\x00-\x0F]/g,function(I){return"\\x0"+t(I)}).replace(/[\x10-\x1F\x7F-\x9F]/g,function(I){return"\\x"+
t(I)})}function da(D){return u[D.type](D)}var u={literal:function(D){return'"'+F(D.text)+'"'},class:function(D){var I=D.parts.map(function(B){return Array.isArray(B)?N(B[0])+"-"+N(B[1]):N(B)});return"["+(D.inverted?"^":"")+I+"]"},any:function(){return"any character"},end:function(){return"end of input"},other:function(D){return D.description}};return"Expected "+function(D){D=D.map(da);var I,B;D.sort();if(0<D.length){for(B=I=1;I<D.length;I++)D[I-1]!==D[I]&&(D[B]=D[I],B++);D.length=B}switch(D.length){case 1:return D[0];
case 2:return D[0]+" or "+D[1];default:return D.slice(0,-1).join(", ")+", or "+D[D.length-1]}}(g)+" but "+(A?'"'+F(A)+'"':"end of input")+" found."};return{SyntaxError:r,parse:function(g,A){function t(c,d){return{type:"literal",text:c,ignoreCase:d}}function F(c,d,e){return{type:"class",parts:c,inverted:d,ignoreCase:e}}function N(c){var d=Va[c],e;if(!d){for(e=c-1;!Va[e];)e--;d=Va[e];for(d={line:d.line,column:d.column};e<c;)10===g.charCodeAt(e)?(d.line++,d.column=1):d.column++,e++;Va[c]=d}return d}
function da(c,d){var e=N(c),l=N(d);return{source:Vc,start:{offset:c,line:e.line,column:e.column},end:{offset:d,line:l.line,column:l.column}}}function u(c){b<ea||(b>ea&&(ea=b,xb=[]),xb.push(c))}function D(){var c=b;p();var d=B();d!==a?(p(),c=d):(b=c,c=a);return c}function I(){var c=b;var d=B();if(d!==a){c=[];var e=b;var l=p();var w=Wa();if(w!==a){var C=p();var E=B();E!==a?e=l=[l,w,C,E]:(b=e,e=a)}else b=e,e=a;for(;e!==a;)c.push(e),e=b,l=p(),w=Wa(),w!==a?(C=p(),E=B(),E!==a?e=l=[l,w,C,E]:(b=e,e=a)):(b=
e,e=a);e={type:"expr_list"};d=[d];for(l=0;l<c.length;l++)d.push(c[l][3]);e.value=d;c=e}else b=c,c=a;return c}function B(){var c=b;var d=ra();if(d!==a){c=[];var e=b;var l=p();var w=Rb();if(w!==a){var C=p();var E=ra();E!==a?e=l=[l,w,C,E]:(b=e,e=a)}else b=e,e=a;for(;e!==a;)c.push(e),e=b,l=p(),w=Rb(),w!==a?(C=p(),E=ra(),E!==a?e=l=[l,w,C,E]:(b=e,e=a)):(b=e,e=a);c=Ea(d,c)}else b=c,c=a;return c}function ra(){var c=b;var d=oa();if(d!==a){c=[];var e=b;var l=p();var w=Xa();if(w!==a){var C=p();var E=oa();E!==
a?e=l=[l,w,C,E]:(b=e,e=a)}else b=e,e=a;for(;e!==a;)c.push(e),e=b,l=p(),w=Xa(),w!==a?(C=p(),E=oa(),E!==a?e=l=[l,w,C,E]:(b=e,e=a)):(b=e,e=a);c=Ea(d,c)}else b=c,c=a;return c}function oa(){var c=b;var d=Fa();if(d===a){d=b;if(33===g.charCodeAt(b)){var e=Wc;b++}else e=a,0===n&&u(Xc);if(e!==a){var l=b;n++;if(61===g.charCodeAt(b)){var w=Sb;b++}else w=a,0===n&&u(Tb);n--;w===a?l=void 0:(b=l,l=a);l!==a?d=e=[e,l]:(b=d,d=a)}else b=d,d=a}d!==a?(e=p(),l=oa(),l!==a?c={type:"unary_expr",operator:"NOT",expr:l}:(b=
c,c=a)):(b=c,c=a);if(c===a){d=b;c=X();if(c!==a){p();d=[];e=b;l=p();w=Ga();if(w!==a){var C=p();var E=X();E!==a?e=l=[l,w,C,E]:(b=e,e=a)}else b=e,e=a;if(e!==a)for(;e!==a;)d.push(e),e=b,l=p(),w=Ga(),w!==a?(C=p(),E=X(),E!==a?e=l=[l,w,C,E]:(b=e,e=a)):(b=e,e=a);else d=a;d!==a&&(d={type:"arithmetic",tail:d});d===a&&(d=b,e=Ha(),e!==a?(p(),l=P(),l!==a?(p(),l=I(),l!==a?(p(),w=Q(),w!==a?d={op:e,right:l}:(b=d,d=a)):(b=d,d=a)):(b=d,d=a)):(b=d,d=a),d===a&&(d=b,e=Ha(),e!==a?(p(),l=P(),l!==a?(p(),l=Q(),l!==a?d={op:e,
right:{type:"expr_list",value:[]}}:(b=d,d=a)):(b=d,d=a)):(b=d,d=a),d===a&&(d=b,e=Ha(),e!==a?(p(),l=f(),l!==a?d={op:e,right:l}:(b=d,d=a)):(b=d,d=a))),d===a&&(d=b,w=Fa(),w!==a?(p(),e=Ub(),e!==a?(p(),l=X(),l!==a?(p(),C=Xa(),C!==a?(p(),w=X(),w!==a?d={op:"NOT"+e,right:{type:"expr_list",value:[l,w]}}:(b=d,d=a)):(b=d,d=a)):(b=d,d=a)):(b=d,d=a)):(b=d,d=a),d===a&&(d=b,w=Ub(),w!==a?(p(),e=X(),e!==a?(p(),l=Xa(),l!==a?(p(),C=X(),C!==a?d={op:w,right:{type:"expr_list",value:[e,C]}}:(b=d,d=a)):(b=d,d=a)):(b=d,d=
a)):(b=d,d=a)),d===a&&(d=b,e=Vb(),e!==a?(p(),l=Fa(),l!==a?(p(),l=X(),l!==a?d={op:e+"NOT",right:l}:(b=d,d=a)):(b=d,d=a)):(b=d,d=a),d===a&&(d=b,e=Vb(),e!==a?(p(),l=X(),l!==a?d={op:e,right:l}:(b=d,d=a)):(b=d,d=a)),d===a&&(d=b,e=Ia(),e!==a?(p(),l=J(),l!==a?(p(),w=b,g.substr(b,6).toLowerCase()===Yc?(C=g.substr(b,6),b+=6):(C=a,0===n&&u(Zc)),C!==a?(C=b,n++,E=q(),n--,E===a?C=void 0:(b=C,C=a),C!==a?w="ESCAPE":(b=w,w=a)):(b=w,w=a),w!==a?(p(),w=S(),w!==a?d={op:e,right:l,escape:w.value}:(b=d,d=a)):(b=d,d=a)):
(b=d,d=a)):(b=d,d=a),d===a&&(d=b,e=Ia(),e!==a?(p(),l=J(),l!==a?d={op:e,right:l,escape:""}:(b=d,d=a)):(b=d,d=a))))));d===a&&(d=null);""==d||void 0==d||null==d?d=c:(e=null,d=e="arithmetic"==d.type?Ea(c,d.tail):Wb(d.op,c,d.right,d.escape))}else b=d,d=a;c=d}return c}function Ga(){if(g.substr(b,2)===Xb){var c=Xb;b+=2}else c=a,0===n&&u($c);c===a&&(62===g.charCodeAt(b)?(c=ad,b++):(c=a,0===n&&u(bd)),c===a&&(g.substr(b,2)===Yb?(c=Yb,b+=2):(c=a,0===n&&u(cd)),c===a&&(g.substr(b,2)===Zb?(c=Zb,b+=2):(c=a,0===
n&&u(dd)),c===a&&(60===g.charCodeAt(b)?(c=ed,b++):(c=a,0===n&&u(fd)),c===a&&(61===g.charCodeAt(b)?(c=Sb,b++):(c=a,0===n&&u(Tb)),c===a&&(g.substr(b,2)===$b?(c=$b,b+=2):(c=a,0===n&&u(gd))))))));return c}function Ia(){var c=c=b;var d=Fa();if(d!==a){var e=p();var l=ac();l!==a?c=d=[d,e,l]:(b=c,c=a)}else b=c,c=a;c!==a&&(c=c[0]+" "+c[2]);c===a&&(c=ac());return c}function Ha(){var c=c=b;var d=Fa();if(d!==a){var e=p();var l=yb();l!==a?c=d=[d,e,l]:(b=c,c=a)}else b=c,c=a;c!==a&&(c=c[0]+" "+c[2]);c===a&&(c=yb());
return c}function X(){var c=b;var d=Ja();if(d!==a){c=[];var e=b;var l=p();var w=Ya();if(w!==a){var C=p();var E=Ja();E!==a?e=l=[l,w,C,E]:(b=e,e=a)}else b=e,e=a;for(;e!==a;)c.push(e),e=b,l=p(),w=Ya(),w!==a?(C=p(),E=Ja(),E!==a?e=l=[l,w,C,E]:(b=e,e=a)):(b=e,e=a);c=Ea(d,c)}else b=c,c=a;return c}function Ya(){if(43===g.charCodeAt(b)){var c=zb;b++}else c=a,0===n&&u(Ab);c===a&&(45===g.charCodeAt(b)?(c=Bb,b++):(c=a,0===n&&u(Cb)));return c}function Ja(){var c=b;var d=Ka();if(d!==a){c=[];var e=b;var l=p();var w=
Za();if(w!==a){var C=p();var E=Ka();E!==a?e=l=[l,w,C,E]:(b=e,e=a)}else b=e,e=a;for(;e!==a;)c.push(e),e=b,l=p(),w=Za(),w!==a?(C=p(),E=Ka(),E!==a?e=l=[l,w,C,E]:(b=e,e=a)):(b=e,e=a);c=Ea(d,c)}else b=c,c=a;return c}function Za(){if(42===g.charCodeAt(b)){var c=hd;b++}else c=a,0===n&&u(id);c===a&&(47===g.charCodeAt(b)?(c=jd,b++):(c=a,0===n&&u(kd)));return c}function Ka(){var c=S();if(c===a){var d=b;var e=b;var l=$a();if(l!==a){var w=bc();if(w!==a){var C=cc();C!==a?e=parseFloat(l+w+C):(b=e,e=a)}else b=e,
e=a}else b=e,e=a;e===a&&(e=b,l=$a(),l!==a?(w=bc(),w!==a?e=parseFloat(l+w):(b=e,e=a)):(b=e,e=a),e===a&&(e=b,l=$a(),l!==a?(w=cc(),w!==a?e=parseFloat(l+w):(b=e,e=a)):(b=e,e=a),e===a&&(e=b,l=$a(),l!==a&&(l=parseFloat(l)),e=l)));var E=e;if(E!==a){var ab=b;n++;var ld=Y();n--;ld===a?ab=void 0:(b=ab,ab=a);ab!==a?d={type:"number",value:E}:(b=d,d=a)}else b=d,d=a;c=d;if(c===a){var La=b;var sa=b;if(g.substr(b,4).toLowerCase()===md){var bb=g.substr(b,4);b+=4}else bb=a,0===n&&u(nd);if(bb!==a){var Ma=b;n++;var od=
q();n--;od===a?Ma=void 0:(b=Ma,Ma=a);Ma!==a?sa=bb=[bb,Ma]:(b=sa,sa=a)}else b=sa,sa=a;var pa=sa;pa!==a&&(pa={type:"bool",value:!0});La=pa;if(La===a){La=b;var ta=b;if(g.substr(b,5).toLowerCase()===pd){var cb=g.substr(b,5);b+=5}else cb=a,0===n&&u(qd);if(cb!==a){var Na=b;n++;var rd=q();n--;rd===a?Na=void 0:(b=Na,Na=a);Na!==a?ta=cb=[cb,Na]:(b=ta,ta=a)}else b=ta,ta=a;pa=ta;pa!==a&&(pa={type:"bool",value:!1});La=pa}c=La;if(c===a){var ua=b;if(g.substr(b,4).toLowerCase()===sd){var db=g.substr(b,4);b+=4}else db=
a,0===n&&u(td);if(db!==a){var Oa=b;n++;var ud=q();n--;ud===a?Oa=void 0:(b=Oa,Oa=a);Oa!==a?ua=db=[db,Oa]:(b=ua,ua=a)}else b=ua,ua=a;var Db=ua;Db!==a&&(Db={type:"null",value:null});c=Db;if(c===a){var va=b;var wa=b;if(g.substr(b,4).toLowerCase()===vd){var dc=g.substr(b,4);b+=4}else dc=a,0===n&&u(wd);if(dc!==a){var eb=b;n++;var xd=q();n--;xd===a?eb=void 0:(b=eb,eb=a);eb!==a?wa="DATE":(b=wa,wa=a)}else b=wa,wa=a;if(wa!==a){p();var ec=J();ec!==a?va={type:"date",value:ec.value}:(b=va,va=a)}else b=va,va=a;
c=va;if(c===a){var xa=b;var ya=b;if(g.substr(b,9).toLowerCase()===yd){var fc=g.substr(b,9);b+=9}else fc=a,0===n&&u(zd);if(fc!==a){var fb=b;n++;var Ad=q();n--;Ad===a?fb=void 0:(b=fb,fb=a);fb!==a?ya="TIMESTAMP":(b=ya,ya=a)}else b=ya,ya=a;if(ya!==a){p();var gc=J();gc!==a?xa={type:"timestamp",value:gc.value}:(b=xa,xa=a)}else b=xa,xa=a;c=xa;if(c===a){var L=b;var Eb=hc();if(Eb!==a){p();if(45===g.charCodeAt(b)){var ia=Bb;b++}else ia=a,0===n&&u(Cb);ia===a&&(43===g.charCodeAt(b)?(ia=zb,b++):(ia=a,0===n&&u(Ab)));
if(ia!==a){p();var Pa=J();if(Pa!==a){p();var ic=v();ic!==a?L={type:"interval",value:Pa,qualifier:ic,op:ia}:(b=L,L=a)}else b=L,L=a}else b=L,L=a}else b=L,L=a;L===a&&(L=b,Eb=hc(),Eb!==a?(p(),ia=J(),ia!==a?(p(),Pa=v(),Pa!==a?L={type:"interval",value:ia,qualifier:Pa,op:""}:(b=L,L=a)):(b=L,L=a)):(b=L,L=a));c=L}}}}}}var G=c;if(G===a){var T=b;var za=b;if(g.substr(b,7).toLowerCase()===Bd){var jc=g.substr(b,7);b+=7}else jc=a,0===n&&u(Cd);if(jc!==a){var gb=b;n++;var Dd=q();n--;Dd===a?gb=void 0:(b=gb,gb=a);gb!==
a?za="EXTRACT":(b=za,za=a)}else b=za,za=a;if(za!==a){p();var Ed=P();if(Ed!==a){p();var Z=kc();Z===a&&(Z=lc(),Z===a&&(Z=mc(),Z===a&&(Z=nc(),Z===a&&(Z=oc(),Z===a&&(Z=qa())))));var pc=Z;if(pc!==a){p();var Fd=Fb();if(Fd!==a){p();var qc=B();if(qc!==a){p();var Gd=Q();Gd!==a?T={type:"function",name:"extract",args:{type:"expr_list",value:[{type:"string",value:pc},qc]}}:(b=T,T=a)}else b=T,T=a}else b=T,T=a}else b=T,T=a}else b=T,T=a}else b=T,T=a;G=T;if(G===a){var U=b;var Aa=b;if(g.substr(b,9).toLowerCase()===
Hd){var rc=g.substr(b,9);b+=9}else rc=a,0===n&&u(Id);if(rc!==a){var hb=b;n++;var Jd=q();n--;Jd===a?hb=void 0:(b=hb,hb=a);hb!==a?Aa="SUBSTRING":(b=Aa,Aa=a)}else b=Aa,Aa=a;if(Aa!==a){p();var Kd=P();if(Kd!==a){p();var Gb=B();if(Gb!==a){p();var Ld=Fb();if(Ld!==a){p();var Hb=B();if(Hb!==a){p();var ja=b;var Ba=b;if(g.substr(b,3).toLowerCase()===Md){var sc=g.substr(b,3);b+=3}else sc=a,0===n&&u(Nd);if(sc!==a){var ib=b;n++;var Od=q();n--;Od===a?ib=void 0:(b=ib,ib=a);ib!==a?Ba="FOR":(b=Ba,Ba=a)}else b=Ba,Ba=
a;var Qa=Ba;if(Qa!==a){var Pd=p();var tc=B();if(tc!==a){var Qd=p();ja=Qa=[Qa,Pd,tc,Qd]}else b=ja,ja=a}else b=ja,ja=a;ja===a&&(ja=null);Qa=Q();Qa!==a?U={type:"function",name:"substring",args:{type:"expr_list",value:ja?[Gb,Hb,ja[2]]:[Gb,Hb]}}:(b=U,U=a)}else b=U,U=a}else b=U,U=a}else b=U,U=a}else b=U,U=a}else b=U,U=a;G=U;if(G===a){var H=b;var Ib=uc();if(Ib!==a){p();var Jb=P();if(Jb!==a){p();var ka=m();ka===a&&(ka=null);p();var Ra=B();if(Ra!==a){p();var Kb=Fb();if(Kb!==a){p();var vc=B();if(vc!==a){p();
var Rd=Q();Rd!==a?H={type:"function",name:"trim",args:{type:"expr_list",value:[{type:"string",value:null==ka?"BOTH":ka},Ra,vc]}}:(b=H,H=a)}else b=H,H=a}else b=H,H=a}else b=H,H=a}else b=H,H=a}else b=H,H=a;H===a&&(H=b,Ib=uc(),Ib!==a?(p(),Jb=P(),Jb!==a?(p(),ka=m(),ka===a&&(ka=null),p(),Ra=B(),Ra!==a?(p(),Kb=Q(),Kb!==a?H={type:"function",name:"trim",args:{type:"expr_list",value:[{type:"string",value:null==ka?"BOTH":ka},Ra]}}:(b=H,H=a)):(b=H,H=a)):(b=H,H=a)):(b=H,H=a));G=H;if(G===a){var V=b;var Ca=b;if(g.substr(b,
8).toLowerCase()===Sd){var wc=g.substr(b,8);b+=8}else wc=a,0===n&&u(Td);if(wc!==a){var jb=b;n++;var Ud=q();n--;Ud===a?jb=void 0:(b=jb,jb=a);jb!==a?Ca="POSITION":(b=Ca,Ca=a)}else b=Ca,Ca=a;if(Ca!==a){p();var Vd=P();if(Vd!==a){p();var xc=B();if(xc!==a){p();var Wd=yb();if(Wd!==a){p();var yc=B();if(yc!==a){p();var Xd=Q();Xd!==a?V={type:"function",name:"position",args:{type:"expr_list",value:[xc,yc]}}:(b=V,V=a)}else b=V,V=a}else b=V,V=a}else b=V,V=a}else b=V,V=a}else b=V,V=a;G=V;if(G===a){var na=b;var kb;
var aa=b;aa=kb=lb();if(aa===a)if(aa=b,96===g.charCodeAt(b)?(kb=zc,b++):(kb=a,0===n&&u(Ac)),kb!==a){var mb=[];if(Bc.test(g.charAt(b))){var la=g.charAt(b);b++}else la=a,0===n&&u(Cc);if(la!==a)for(;la!==a;)mb.push(la),Bc.test(g.charAt(b))?(la=g.charAt(b),b++):(la=a,0===n&&u(Cc));else mb=a;mb!==a?(96===g.charCodeAt(b)?(la=zc,b++):(la=a,0===n&&u(Ac)),la!==a?aa=mb.join(""):(b=aa,aa=a)):(b=aa,aa=a)}else b=aa,aa=a;var Dc=aa;if(Dc!==a){p();var Yd=P();if(Yd!==a){p();var nb=I();nb===a&&(nb=null);p();var Zd=
Q();Zd!==a?na={type:"function",name:Dc,args:nb?nb:{type:"expr_list",value:[]}}:(b=na,na=a)}else b=na,na=a}else b=na,na=a;G=na;if(G===a){var fa;var M=b;var Lb=ob();if(Lb!==a){p();var Sa=B();if(Sa!==a){p();var Ta=[];for(fa=pb();fa!==a;)Ta.push(fa),fa=pb();fa=p();var rb=qb();rb!==a?M={type:"case_expression",format:"simple",operand:Sa,clauses:Ta,else:null}:(b=M,M=a)}else b=M,M=a}else b=M,M=a;if(M===a)if(M=b,Lb=ob(),Lb!==a)if(p(),Sa=B(),Sa!==a){p();Ta=[];for(fa=pb();fa!==a;)Ta.push(fa),fa=pb();fa=p();
rb=Ec();if(rb!==a){p();var $d=qb();$d!==a?M={type:"case_expression",format:"simple",operand:Sa,clauses:Ta,else:rb.value}:(b=M,M=a)}else b=M,M=a}else b=M,M=a;else b=M,M=a;var Mb=M;if(Mb===a){var ha;var R=b;var Nb=ob();if(Nb!==a){p();var Ua=[];for(ha=W();ha!==a;)Ua.push(ha),ha=W();ha=p();var sb=qb();sb!==a?R={type:"case_expression",format:"searched",clauses:Ua,else:null}:(b=R,R=a)}else b=R,R=a;if(R===a)if(R=b,Nb=ob(),Nb!==a){p();Ua=[];for(ha=W();ha!==a;)Ua.push(ha),ha=W();ha=p();sb=Ec();if(sb!==a){p();
var ae=qb();ae!==a?R={type:"case_expression",format:"searched",clauses:Ua,else:sb.value}:(b=R,R=a)}else b=R,R=a}else b=R,R=a;Mb=R}G=Mb;if(G===a){var tb;var ub=b;var Fc=Y();if(Fc!==a){var Gc=[];for(tb=k();tb!==a;)Gc.push(tb),tb=k();ub=Fc+Gc.join("")}else b=ub,ub=a;var vb=ub;if(vb!==a){var Ob=vb;vb=/^CURRENT_DATE$/i.test(Ob)?{type:"current_time",mode:"date"}:/^CURRENT_TIMESTAMP$/i.test(Ob)?{type:"current_time",mode:"timestamp"}:{type:"column_ref",table:"",column:Ob}}G=vb;if(G===a&&(G=f(),G===a)){G=
b;var be=P();if(be!==a){p();var Pb=B();if(Pb!==a){p();var ce=Q();ce!==a?(Pb.paren=!0,G=Pb):(b=G,G=a)}else b=G,G=a}else b=G,G=a}}}}}}}}return G}function lb(){var c;var d=b;var e=Y();if(e!==a){d=[];for(c=q();c!==a;)d.push(c),c=q();d=e+d.join("")}else b=d,d=a;return d}function Y(){if(de.test(g.charAt(b))){var c=g.charAt(b);b++}else c=a,0===n&&u(ee);return c}function q(){if(fe.test(g.charAt(b))){var c=g.charAt(b);b++}else c=a,0===n&&u(ge);return c}function k(){if(he.test(g.charAt(b))){var c=g.charAt(b);
b++}else c=a,0===n&&u(ie);return c}function f(){var c=b;if(64===g.charCodeAt(b)){var d=je;b++}else d=a,0===n&&u(ke);if(d!==a){var e=lb();e!==a?c=d=[d,e]:(b=c,c=a)}else b=c,c=a;c!==a&&(c={type:"param",value:c[1]});return c}function m(){var c=b;if(g.substr(b,7).toLowerCase()===le){var d=g.substr(b,7);b+=7}else d=a,0===n&&u(me);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="LEADING":(b=c,c=a)}else b=c,c=a;c===a&&(c=b,g.substr(b,8).toLowerCase()===ne?(d=g.substr(b,8),b+=8):(d=a,0===
n&&u(oe)),d!==a?(d=b,n++,e=q(),n--,e===a?d=void 0:(b=d,d=a),d!==a?c="TRAILING":(b=c,c=a)):(b=c,c=a),c===a&&(c=b,g.substr(b,4).toLowerCase()===pe?(d=g.substr(b,4),b+=4):(d=a,0===n&&u(qe)),d!==a?(d=b,n++,e=q(),n--,e===a?d=void 0:(b=d,d=a),d!==a?c="BOTH":(b=c,c=a)):(b=c,c=a)));return c}function v(){var c=b;var d=b;var e=y();if(e!==a){p();var l=P();if(l!==a)if(p(),l=K(),l!==a){p();var w=Q();w!==a?d={type:"interval-period",period:e.value,precision:l,secondary:null}:(b=d,d=a)}else b=d,d=a;else b=d,d=a}else b=
d,d=a;d===a&&(d=b,e=y(),e!==a&&(e=Hc(e)),d=e);if(d!==a)if(p(),e=b,g.substr(b,2).toLowerCase()===re?(l=g.substr(b,2),b+=2):(l=a,0===n&&u(se)),l!==a?(l=b,n++,w=q(),n--,w===a?l=void 0:(b=l,l=a),l!==a?e="TO":(b=e,e=a)):(b=e,e=a),e!==a){p();e=b;l=y();l!==a&&(l={type:"interval-period",period:l.value,precision:null,secondary:null});e=l;if(e===a){e=b;l=qa();if(l!==a)if(p(),l=P(),l!==a)if(p(),l=K(),l!==a)if(p(),w=Wa(),w!==a)if(p(),w=z(),w!==a){p();var C=Q();C!==a?e=Ic(l,w):(b=e,e=a)}else b=e,e=a;else b=e,
e=a;else b=e,e=a;else b=e,e=a;else b=e,e=a;e===a&&(e=b,l=qa(),l!==a?(p(),l=P(),l!==a?(p(),l=K(),l!==a?(p(),w=Q(),w!==a?e={type:"interval-period",period:"second",precision:l,secondary:null}:(b=e,e=a)):(b=e,e=a)):(b=e,e=a)):(b=e,e=a),e===a&&(e=b,l=qa(),l!==a&&(l={type:"interval-period",period:"second",precision:null,secondary:null}),e=l))}e!==a?c={type:"interval-qualifier",start:d,end:e}:(b=c,c=a)}else b=c,c=a;else b=c,c=a;c===a&&(c=b,e=y(),e!==a?(p(),d=P(),d!==a?(p(),d=z(),d!==a?(p(),l=Q(),l!==a?c=
{type:"interval-period",period:e.value,precision:d,secondary:null}:(b=c,c=a)):(b=c,c=a)):(b=c,c=a)):(b=c,c=a),c===a&&(c=b,e=y(),e!==a&&(e=Hc(e)),c=e,c===a&&(c=b,e=qa(),e!==a?(p(),d=P(),d!==a?(p(),d=K(),d!==a?(p(),l=Wa(),l!==a?(p(),e=z(),e!==a?(p(),l=Q(),l!==a?c=Ic(d,e):(b=c,c=a)):(b=c,c=a)):(b=c,c=a)):(b=c,c=a)):(b=c,c=a)):(b=c,c=a),c===a&&(c=b,e=qa(),e!==a?(p(),d=P(),d!==a?(p(),d=z(),d!==a?(p(),l=Q(),l!==a?c={type:"interval-period",period:"second",precision:d,secondary:null}:(b=c,c=a)):(b=c,c=a)):
(b=c,c=a)):(b=c,c=a),c===a&&(c=b,e=qa(),e!==a&&(e={type:"interval-period",period:"second",precision:null,secondary:null}),c=e)))));return c}function y(){var c=b;c=mc();c!==a&&(c={type:"string",value:"day"});c===a&&(c=b,c=nc(),c!==a&&(c={type:"string",value:"hour"}),c===a&&(c=b,c=oc(),c!==a&&(c={type:"string",value:"minute"}),c===a&&(c=b,c=lc(),c!==a&&(c={type:"string",value:"month"}),c===a&&(c=b,c=kc(),c!==a&&(c={type:"string",value:"year"})))));return c}function z(){var c=Da();c!==a&&(c=parseFloat(c));
return c}function K(){var c=Da();c!==a&&(c=parseFloat(c));return c}function J(){var c=S();c===a&&(c=f());return c}function S(){var c=b;if(39===g.charCodeAt(b)){var d=Jc;b++}else d=a,0===n&&u(Kc);d===a&&(g.substr(b,2)===Lc?(d=Lc,b+=2):(d=a,0===n&&u(te)));if(d!==a){d=[];var e=b;g.substr(b,2)===wb?(e=wb,b+=2):(e=a,0===n&&u(Mc));e!==a&&(e="'");e===a&&(Nc.test(g.charAt(b))?(e=g.charAt(b),b++):(e=a,0===n&&u(Oc)));for(;e!==a;)d.push(e),e=b,g.substr(b,2)===wb?(e=wb,b+=2):(e=a,0===n&&u(Mc)),e!==a&&(e="'"),
e===a&&(Nc.test(g.charAt(b))?(e=g.charAt(b),b++):(e=a,0===n&&u(Oc)));39===g.charCodeAt(b)?(e=Jc,b++):(e=a,0===n&&u(Kc));e!==a?c={type:"string",value:d.join("")}:(b=c,c=a)}else b=c,c=a;return c}function W(){var c=b;if(Pc()!==a){p();var d=B();if(d!==a){p();var e=Qc();e!==a?(p(),e=B(),e!==a?c={type:"when_clause",operand:d,value:e}:(b=c,c=a)):(b=c,c=a)}else b=c,c=a}else b=c,c=a;return c}function pb(){var c=b;if(Pc()!==a){p();var d=B();if(d!==a){p();var e=Qc();e!==a?(p(),e=B(),e!==a?c={type:"when_clause",
operand:d,value:e}:(b=c,c=a)):(b=c,c=a)}else b=c,c=a}else b=c,c=a;return c}function Ec(){var c=b;var d=b;if(g.substr(b,4).toLowerCase()===ue){var e=g.substr(b,4);b+=4}else e=a,0===n&&u(ve);if(e!==a){e=b;n++;var l=q();n--;l===a?e=void 0:(b=e,e=a);e!==a?d="ELSE":(b=d,d=a)}else b=d,d=a;d!==a?(p(),d=B(),d!==a?c={type:"else_clause",value:d}:(b=c,c=a)):(b=c,c=a);return c}function $a(){var c=Da();if(c===a){c=b;if(45===g.charCodeAt(b)){var d=Bb;b++}else d=a,0===n&&u(Cb);d===a&&(43===g.charCodeAt(b)?(d=zb,
b++):(d=a,0===n&&u(Ab)));if(d!==a){var e=Da();e!==a?c=d[0]+e:(b=c,c=a)}else b=c,c=a}return c}function bc(){var c=b;if(46===g.charCodeAt(b)){var d=we;b++}else d=a,0===n&&u(xe);d!==a?(c=Da(),c===a&&(c=null),c="."+(null!=c?c:"")):(b=c,c=a);return c}function cc(){var c;var d=c=b;if(ye.test(g.charAt(b))){var e=g.charAt(b);b++}else e=a,0===n&&u(ze);e!==a?(Ae.test(g.charAt(b))?(d=g.charAt(b),b++):(d=a,0===n&&u(Be)),d===a&&(d=null),d="e"+(null===d?"":d)):(b=d,d=a);d!==a?(e=Da(),e!==a?c=d+e:(b=c,c=a)):(b=
c,c=a);return c}function Da(){var c=[];var d=Rc();if(d!==a)for(;d!==a;)c.push(d),d=Rc();else c=a;c!==a&&(c=c.join(""));return c}function Rc(){if(Ce.test(g.charAt(b))){var c=g.charAt(b);b++}else c=a,0===n&&u(De);return c}function yb(){var c=b;if(g.substr(b,2).toLowerCase()===Ee){var d=g.substr(b,2);b+=2}else d=a,0===n&&u(Fe);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="IN":(b=c,c=a)}else b=c,c=a;return c}function Vb(){var c=b;if(g.substr(b,2).toLowerCase()===Ge){var d=g.substr(b,
2);b+=2}else d=a,0===n&&u(He);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="IS":(b=c,c=a)}else b=c,c=a;return c}function ac(){var c=b;if(g.substr(b,4).toLowerCase()===Ie){var d=g.substr(b,4);b+=4}else d=a,0===n&&u(Je);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="LIKE":(b=c,c=a)}else b=c,c=a;return c}function Fa(){var c=b;if(g.substr(b,3).toLowerCase()===Ke){var d=g.substr(b,3);b+=3}else d=a,0===n&&u(Le);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=
a);d!==a?c="NOT":(b=c,c=a)}else b=c,c=a;return c}function Xa(){var c=b;if(g.substr(b,3).toLowerCase()===Me){var d=g.substr(b,3);b+=3}else d=a,0===n&&u(Ne);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="AND":(b=c,c=a)}else b=c,c=a;return c}function Rb(){var c=b;if(g.substr(b,2).toLowerCase()===Oe){var d=g.substr(b,2);b+=2}else d=a,0===n&&u(Pe);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="OR":(b=c,c=a)}else b=c,c=a;return c}function Ub(){var c=b;if(g.substr(b,
7).toLowerCase()===Qe){var d=g.substr(b,7);b+=7}else d=a,0===n&&u(Re);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="BETWEEN":(b=c,c=a)}else b=c,c=a;return c}function Fb(){var c=b;if(g.substr(b,4).toLowerCase()===Se){var d=g.substr(b,4);b+=4}else d=a,0===n&&u(Te);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="FROM":(b=c,c=a)}else b=c,c=a;return c}function uc(){var c=b;if(g.substr(b,4).toLowerCase()===Ue){var d=g.substr(b,4);b+=4}else d=a,0===n&&u(Ve);if(d!==a){d=
b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="TRIM":(b=c,c=a)}else b=c,c=a;return c}function hc(){var c=b;if(g.substr(b,8).toLowerCase()===We){var d=g.substr(b,8);b+=8}else d=a,0===n&&u(Xe);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="INTERVAL":(b=c,c=a)}else b=c,c=a;return c}function kc(){var c=b;if(g.substr(b,4).toLowerCase()===Ye){var d=g.substr(b,4);b+=4}else d=a,0===n&&u(Ze);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="YEAR":(b=c,c=a)}else b=
c,c=a;return c}function lc(){var c=b;if(g.substr(b,5).toLowerCase()===$e){var d=g.substr(b,5);b+=5}else d=a,0===n&&u(af);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="MONTH":(b=c,c=a)}else b=c,c=a;return c}function mc(){var c=b;if(g.substr(b,3).toLowerCase()===bf){var d=g.substr(b,3);b+=3}else d=a,0===n&&u(cf);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="DAY":(b=c,c=a)}else b=c,c=a;return c}function nc(){var c=b;if(g.substr(b,4).toLowerCase()===df){var d=g.substr(b,
4);b+=4}else d=a,0===n&&u(ef);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="HOUR":(b=c,c=a)}else b=c,c=a;return c}function oc(){var c=b;if(g.substr(b,6).toLowerCase()===ff){var d=g.substr(b,6);b+=6}else d=a,0===n&&u(gf);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="MINUTE":(b=c,c=a)}else b=c,c=a;return c}function qa(){var c=b;if(g.substr(b,6).toLowerCase()===hf){var d=g.substr(b,6);b+=6}else d=a,0===n&&u(jf);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=
d,d=a);d!==a?c="SECOND":(b=c,c=a)}else b=c,c=a;return c}function ob(){var c=b;if(g.substr(b,4).toLowerCase()===kf){var d=g.substr(b,4);b+=4}else d=a,0===n&&u(lf);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="CASE":(b=c,c=a)}else b=c,c=a;return c}function qb(){var c=b;if(g.substr(b,3).toLowerCase()===mf){var d=g.substr(b,3);b+=3}else d=a,0===n&&u(nf);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="END":(b=c,c=a)}else b=c,c=a;return c}function Pc(){var c=b;if(g.substr(b,
4).toLowerCase()===of){var d=g.substr(b,4);b+=4}else d=a,0===n&&u(pf);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="WHEN":(b=c,c=a)}else b=c,c=a;return c}function Qc(){var c=b;if(g.substr(b,4).toLowerCase()===qf){var d=g.substr(b,4);b+=4}else d=a,0===n&&u(rf);if(d!==a){d=b;n++;var e=q();n--;e===a?d=void 0:(b=d,d=a);d!==a?c="THEN":(b=c,c=a)}else b=c,c=a;return c}function Wa(){if(44===g.charCodeAt(b)){var c=sf;b++}else c=a,0===n&&u(tf);return c}function P(){if(40===g.charCodeAt(b)){var c=
uf;b++}else c=a,0===n&&u(vf);return c}function Q(){if(41===g.charCodeAt(b)){var c=wf;b++}else c=a,0===n&&u(xf);return c}function p(){var c;var d=[];for(c=Sc();c!==a;)d.push(c),c=Sc();return d}function Sc(){if(yf.test(g.charAt(b))){var c=g.charAt(b);b++}else c=a,0===n&&u(zf);return c}function Wb(c,d,e,l){c={type:"binary_expr",operator:c,left:d,right:e};void 0!==l&&(c.escape=l);return c}function Ea(c,d){for(var e=0;e<d.length;e++)c=Wb(d[e][1],c,d[e][3]);return c}A=void 0!==A?A:{};var a={},Vc=A.grammarSource,
Tc={start:D},Uc=D,Wc="!",Sb="\x3d",Xb="\x3e\x3d",ad="\x3e",Yb="\x3c\x3d",Zb="\x3c\x3e",ed="\x3c",$b="!\x3d",zb="+",Bb="-",hd="*",jd="/",je="@",Jc="'",Lc="N'",wb="''",we=".",sd="null",md="true",pd="false",Ee="in",Ge="is",Ie="like",Yc="escape",Ke="not",Me="and",Oe="or",Qe="between",Se="from",Md="for",Hd="substring",Bd="extract",Ue="trim",Sd="position",yd="timestamp",vd="date",le="leading",ne="trailing",pe="both",re="to",We="interval",Ye="year",$e="month",bf="day",df="hour",ff="minute",hf="second",kf=
"case",mf="end",of="when",qf="then",ue="else",sf=",",uf="(",wf=")",zc="`",de=/^[A-Za-z_\x80-\uFFFF]/,fe=/^[A-Za-z0-9_]/,he=/^[A-Za-z0-9_.\x80-\uFFFF]/,Nc=/^[^']/,Ce=/^[0-9]/,ye=/^[eE]/,Ae=/^[+\-]/,yf=/^[ \t\n\r]/,Bc=/^[^`]/,Xc=t("!",!1),Tb=t("\x3d",!1),$c=t("\x3e\x3d",!1),bd=t("\x3e",!1),cd=t("\x3c\x3d",!1),dd=t("\x3c\x3e",!1),fd=t("\x3c",!1),gd=t("!\x3d",!1),Ab=t("+",!1),Cb=t("-",!1),id=t("*",!1),kd=t("/",!1),ee=F([["A","Z"],["a","z"],"_",["\u0080","\uffff"]],!1,!1),ge=F([["A","Z"],["a","z"],["0",
"9"],"_"],!1,!1),ie=F([["A","Z"],["a","z"],["0","9"],"_",".",["\u0080","\uffff"]],!1,!1),ke=t("@",!1),Kc=t("'",!1),te=t("N'",!1),Mc=t("''",!1),Oc=F(["'"],!0,!1),xe=t(".",!1),De=F([["0","9"]],!1,!1),ze=F(["e","E"],!1,!1),Be=F(["+","-"],!1,!1),td=t("NULL",!0),nd=t("TRUE",!0),qd=t("FALSE",!0),Fe=t("IN",!0),He=t("IS",!0),Je=t("LIKE",!0),Zc=t("ESCAPE",!0),Le=t("NOT",!0),Ne=t("AND",!0),Pe=t("OR",!0),Re=t("BETWEEN",!0),Te=t("FROM",!0),Nd=t("FOR",!0),Id=t("SUBSTRING",!0),Cd=t("EXTRACT",!0),Ve=t("TRIM",!0),
Td=t("POSITION",!0),zd=t("TIMESTAMP",!0),wd=t("DATE",!0),me=t("LEADING",!0),oe=t("TRAILING",!0),qe=t("BOTH",!0),se=t("TO",!0),Xe=t("INTERVAL",!0),Ze=t("YEAR",!0),af=t("MONTH",!0),cf=t("DAY",!0),ef=t("HOUR",!0),gf=t("MINUTE",!0),jf=t("SECOND",!0),lf=t("CASE",!0),nf=t("END",!0),pf=t("WHEN",!0),rf=t("THEN",!0),ve=t("ELSE",!0),tf=t(",",!1),vf=t("(",!1),xf=t(")",!1),zf=F([" ","\t","\n","\r"],!1,!1),Ac=t("`",!1),Cc=F(["`"],!0,!1),Hc=function(c){return{type:"interval-period",period:c.value,precision:null,
secondary:null}},Ic=function(c,d){return{type:"interval-period",period:"second",precision:c,secondary:d}},b=0,Va=[{line:1,column:1}],ea=0,xb=[],n=0;if("startRule"in A){if(!(A.startRule in Tc))throw Error("Can't start parsing from rule \""+A.startRule+'".');Uc=Tc[A.startRule]}var Qb=Uc();if(Qb!==a&&b===g.length)return Qb;Qb!==a&&b<g.length&&u({type:"end"});throw function(c,d,e){return new r(r.buildMessage(c,d),c,d,e)}(xb,ea<g.length?g.charAt(ea):null,ea<g.length?da(ea,ea+1):da(ea,ea));}}})})(ba);let ca=
function(){function h(){}h.parse=function(r){return ba.exports.parse(r)};return h}();O.WhereGrammar=ca;Object.defineProperty(O,"__esModule",{value:!0})})},"*noref":1}});
define("exports ../../chunks/_rollupPluginBabelHelpers ../has ./AggregateFunctions ./StandardizedFunctions ./WhereGrammar".split(" "),function(O,ma,ba,ca,h,r){function x(q,k){q+="";return q.length>=k?q:Array(k-q.length+1).join("0")+q}function g(q,k,f="0",m="0",v="0",y="0",z="",K="0",J="0"){return"+"===z||"-"===z?(q=`${x(parseInt(q,10),4)}-${x(parseInt(k,10),2)}-${x(parseInt(f,10),2)}`,k="",10>parseFloat(y)&&(k="0"),m=`${x(parseInt(m,10),2)}:${x(parseInt(v,10),2)}:${k+parseFloat(y).toString()}`,z=
`${z}${x(parseInt(K,10),2)}:${x(parseInt(J,10),2)}`,new Date(q+"T"+m+z)):new Date(parseInt(q,10),parseInt(k,10)-1,parseInt(f,10),parseInt(m,10),parseInt(v,10),parseFloat(y))}function A(q){let k=Ha.exec(q);if(null!==k){const [,f,m,v,y,z,K]=k;return g(f,m,v,y,z,K)}k=X.exec(q);if(null!==k){const [,f,m,v,y,z,K,J,S,W]=k;return g(f,m,v,y,z,K,J,S,W)}k=Ya.exec(q);if(null!==k){const [,f,m,v,y,z,K,J,S]=k;return g(f,m,v,y,z,"0",K,J,S)}k=Ja.exec(q);if(null!==k){const [,f,m,v,y,z]=k;return g(f,m,v,y,z)}k=Ia.exec(q);
if(null!==k){const [,f,m,v]=k;return g(f,m,v)}throw Error("SQL Invalid Timestamp");}function t(q){q=Ia.exec(q);if(null===q)throw Error("SQL Invalid Date");const [,k,f,m]=q;return new Date(parseInt(k,10),parseInt(f,10)-1,parseInt(m,10))}function F(q){return Array.isArray(q)?q:[q]}function N(q){return null!==q?!0!==q:null}function da(q,k){return null!=q&&null!=k?!0===q&&!0===k:!1===q||!1===k?!1:null}function u(q,k){return null!=q&&null!=k?!0===q||!0===k:!0===q||!0===k?!0:null}function D(q,k){if(null==
q)return null;let f=!1;for(const m of k)if(null==m)f=null;else if(q===m){f=!0;break}return f}function I(q,k,f){if(null==q)return null;let m="",v=0;for(let y=0;y<k.length;y++){const z=k.charAt(y);switch(v){case 0:z===f?v=1:m=0<="-[]/{}()*+?.\\^$|".indexOf(z)?m+("\\"+z):"%"===z?m+".*":"_"===z?m+".":m+z;break;case 1:m=0<="-[]/{}()*+?.\\^$|".indexOf(z)?m+("\\"+z):m+z,v=0}}return(new RegExp("^"+m+"$")).test(q)}function B(q){return q instanceof Date?q.valueOf():q}function ra(q,k,f){if(null==k||null==f)return null;
k=B(k);f=B(f);switch(q){case "\x3c\x3e":return k!==f;case "\x3d":return k===f;case "\x3e":return k>f;case "\x3c":return k<f;case "\x3e\x3d":return k>=f;case "\x3c\x3d":return k<=f}}function oa(q,k,f){if(k instanceof h.SqlInterval)if(f instanceof Date)switch(q){case "+":return new Date(k.valueInMilliseconds()+f.getTime());case "-":return k.valueInMilliseconds()-f.getTime();case "*":return k.valueInMilliseconds()*f.getTime();case "/":return k.valueInMilliseconds()/f.getTime()}else if(f instanceof h.SqlInterval)switch(q){case "+":return h.SqlInterval.createFromMilliseconds(k.valueInMilliseconds()+
f.valueInMilliseconds());case "-":return h.SqlInterval.createFromMilliseconds(k.valueInMilliseconds()-f.valueInMilliseconds());case "*":return k.valueInMilliseconds()*f.valueInMilliseconds();case "/":return k.valueInMilliseconds()/f.valueInMilliseconds()}else k=k.valueInMilliseconds();else if(f instanceof h.SqlInterval)if(k instanceof Date)switch(q){case "+":return new Date(f.valueInMilliseconds()+k.getTime());case "-":return new Date(k.getTime()-f.valueInMilliseconds());case "*":return k.getTime()*
f.valueInMilliseconds();case "/":return k.getTime()/f.valueInMilliseconds()}else f=f.valueInMilliseconds();else if(k instanceof Date&&"number"===typeof f)switch(f*=864E5,k=k.getTime(),q){case "+":return new Date(k+f);case "-":return new Date(k-f);case "*":return new Date(k*f);case "/":return new Date(k/f)}else if(f instanceof Date&&"number"===typeof k)switch(k*=864E5,f=f.getTime(),q){case "+":return new Date(k+f);case "-":return new Date(k-f);case "*":return new Date(k*f);case "/":return new Date(k/
f)}switch(q){case "+":return k+f;case "-":return k-f;case "*":return k*f;case "/":return k/f}}function Ga(q,k,f,m){q=m.getAttribute(q,k);return null!=q&&1===f[k]?new Date(q):q}const Ia=/^(\d{4})-(\d{1,2})-(\d{1,2})$/,Ha=/^(\d{4})-(\d{1,2})-(\d{1,2}) (\d{1,2}):(\d{1,2}):(\d{1,2}(\.[0-9]+)?)$/,X=/^(\d{4})-(\d{1,2})-(\d{1,2}) (\d{1,2}):(\d{1,2}):(\d{1,2}(\.[0-9]+)?)(\+|\-)(\d{1,2}):(\d{1,2})$/,Ya=/^(\d{4})-(\d{1,2})-(\d{1,2}) (\d{1,2}):(\d{1,2})(\+|\-)(\d{1,2}):(\d{1,2})$/,Ja=/^(\d{4})-(\d{1,2})-(\d{1,2}) (\d{1,2}):(\d{1,2})$/,
Za=new Set(["current_timestamp","current_date","current_time"]);let Ka=function(){function q(){}q.makeBool=function(k){return!0===k};q.featureValue=function(k,f,m,v){return Ga(k,f,m,v)};q.equalsNull=function(k){return null===k};q.applyLike=function(k,f,m){return I(k,f,m)};q.ensureArray=function(k){return F(k)};q.applyIn=function(k,f){return D(k,f)};q.currentDate=function(){const k=new Date;k.setHours(0,0,0,0);return k};q.makeSqlInterval=function(k,f,m){return h.SqlInterval.createFromValueAndQualifer(k,
f,m)};q.convertInterval=function(k){return k instanceof h.SqlInterval?k.valueInMilliseconds():k};q.currentTimestamp=function(){return new Date};q.compare=function(k,f,m){return ra(k,f,m)};q.calculate=function(k,f,m){return oa(k,f,m)};q.makeComparable=function(k){return B(k)};q.evaluateFunction=function(k,f){return h.evaluateFunction(k,f)};q.lookup=function(k,f){k=f[k];return void 0===k?null:k};q.between=function(k,f){return null==k||null==f[0]||null==f[1]?null:k>=f[0]&&k<=f[1]};q.notbetween=function(k,
f){return null==k||null==f[0]||null==f[1]?null:k<f[0]||k>f[1]};q.ternaryNot=function(k){return N(k)};q.ternaryAnd=function(k,f){return da(k,f)};q.ternaryOr=function(k,f){return u(k,f)};return q}(),lb=function(){function q(f,m){this.fieldsIndex=m;this.datefields={};this.parameters={};this._hasDateFunctions=void 0;this.parseTree=r.WhereGrammar.parse(f);const {isStandardized:v,isAggregate:y,referencedFieldNames:z}=this.extractExpressionInfo(m);this.referencedFieldNames=z;this.isStandardized=v;this.isAggregate=
y}q.create=function(f,m){return new q(f,m)};var k=q.prototype;k.testSet=function(f,m=Y){const v={};for(const y of this.fieldNames)v[y]=f.map(z=>m.getAttribute(z,y));return!!this.evaluateNode(this.parseTree,{attributes:v},Y)};k.calculateValue=function(f,m=Y){f=this.evaluateNode(this.parseTree,f,m);return f instanceof h.SqlInterval?f.valueInMilliseconds()/864E5:f};k.calculateValueCompiled=function(f,m=Y){if(null!=this.parseTree._compiledVersion)return this.parseTree._compiledVersion(f,this.parameters,
m,this.datefields);if(ba("esri-csp-restrictions"))return this.calculateValue(f,m);this.compileMe();return this.parseTree._compiledVersion(f,this.parameters,m,this.datefields)};k.testFeature=function(f,m=Y){return!!this.evaluateNode(this.parseTree,f,m)};k.testFeatureCompiled=function(f,m=Y){if(null!=this.parseTree._compiledVersion)return!!this.parseTree._compiledVersion(f,this.parameters,m,this.datefields);if(ba("esri-csp-restrictions"))return this.testFeature(f,m);this.compileMe();return!!this.parseTree._compiledVersion(f,
this.parameters,m,this.datefields)};k.getFunctions=function(){const f=new Set;this.visitAll(this.parseTree,m=>{"function"===m.type&&f.add(m.name.toLowerCase())});return Array.from(f)};k.getExpressions=function(){const f=new Map;this.visitAll(this.parseTree,m=>{if("function"===m.type){const v=m.name.toLowerCase();m=m.args.value[0];if("column_ref"===m.type){m=m.column;const y=`${v}-${m}`;f.has(y)||f.set(y,{aggregateType:v,field:m})}}});return[...f.values()]};k.getVariables=function(){const f=new Set;
this.visitAll(this.parseTree,m=>{"param"===m.type&&f.add(m.value.toLowerCase())});return Array.from(f)};k.compileMe=function(){const f="return this.convertInterval("+this.evaluateNodeToJavaScript(this.parseTree)+")";this.parseTree._compiledVersion=(new Function("feature","lookups","attributeAdapter","datefields",f)).bind(Ka)};k.extractExpressionInfo=function(f){const m=[],v=new Set;let y=!0,z=!0;this.visitAll(this.parseTree,K=>{switch(K.type){case "column_ref":{const J=f.get(K.column);let S,W;J?S=
W=J.name:(W=K.column,S=W.toLowerCase());!J||"date"!==J.type&&"esriFieldTypeDate"!==J.type||(this.datefields[J.name]=1);v.has(S)||(v.add(S),m.push(W));K.column=W;break}case "function":{const {name:J,args:S}=K;K=S.value.length;y&&(y=h.isStandardized(J,K));z&&(z=ca.isAggregate(J,K))}}});return{referencedFieldNames:Array.from(m),isStandardized:y,isAggregate:z}};k.visitAll=function(f,m){if(null!=f)switch(m(f),f.type){case "when_clause":this.visitAll(f.operand,m);this.visitAll(f.value,m);break;case "case_expression":for(const v of f.clauses)this.visitAll(v,
m);"simple"===f.format&&this.visitAll(f.operand,m);null!==f.else&&this.visitAll(f.else,m);break;case "expr_list":for(const v of f.value)this.visitAll(v,m);break;case "unary_expr":this.visitAll(f.expr,m);break;case "binary_expr":this.visitAll(f.left,m);this.visitAll(f.right,m);break;case "function":this.visitAll(f.args,m)}};k.evaluateNodeToJavaScript=function(f){switch(f.type){case "interval":return"this.makeSqlInterval("+this.evaluateNodeToJavaScript(f.value)+", "+JSON.stringify(f.qualifier)+","+
JSON.stringify(f.op)+")";case "case_expression":var m="";if("simple"===f.format){var v="this.makeComparable("+this.evaluateNodeToJavaScript(f.operand)+")";m="( ";for(let y=0;y<f.clauses.length;y++)m+=" ("+v+" \x3d\x3d\x3d this.makeComparable("+this.evaluateNodeToJavaScript(f.clauses[y].operand)+")) ? ("+this.evaluateNodeToJavaScript(f.clauses[y].value)+") : "}else for(m="( ",v=0;v<f.clauses.length;v++)m+=" this.makeBool("+this.evaluateNodeToJavaScript(f.clauses[v].operand)+")\x3d\x3d\x3dtrue ? ("+
this.evaluateNodeToJavaScript(f.clauses[v].value)+") : ";m=null!==f.else?m+this.evaluateNodeToJavaScript(f.else):m+"null";return m+=" )";case "param":return"this.lookup("+JSON.stringify(f.value.toLowerCase())+",lookups)";case "expr_list":m="[";for(v of f.value)"["!==m&&(m+=","),m+=this.evaluateNodeToJavaScript(v);return m+="]";case "unary_expr":return"this.ternaryNot("+this.evaluateNodeToJavaScript(f.expr)+")";case "binary_expr":switch(f.operator){case "AND":return"this.ternaryAnd("+this.evaluateNodeToJavaScript(f.left)+
","+this.evaluateNodeToJavaScript(f.right)+" )";case "OR":return"this.ternaryOr("+this.evaluateNodeToJavaScript(f.left)+","+this.evaluateNodeToJavaScript(f.right)+" )";case "IS":if("null"!==f.right.type)throw Error("Unsupported RHS for IS");return"this.equalsNull("+this.evaluateNodeToJavaScript(f.left)+")";case "ISNOT":if("null"!==f.right.type)throw Error("Unsupported RHS for IS");return"(!(this.equalsNull("+this.evaluateNodeToJavaScript(f.left)+")))";case "IN":return"this.applyIn("+this.evaluateNodeToJavaScript(f.left)+
",this.ensureArray("+this.evaluateNodeToJavaScript(f.right)+"))";case "NOT IN":return"this.ternaryNot(this.applyIn("+this.evaluateNodeToJavaScript(f.left)+",this.ensureArray("+this.evaluateNodeToJavaScript(f.right)+")))";case "BETWEEN":return"this.between("+this.evaluateNodeToJavaScript(f.left)+","+this.evaluateNodeToJavaScript(f.right)+")";case "NOTBETWEEN":return"this.notbetween("+this.evaluateNodeToJavaScript(f.left)+","+this.evaluateNodeToJavaScript(f.right)+")";case "LIKE":return"this.applyLike("+
this.evaluateNodeToJavaScript(f.left)+","+this.evaluateNodeToJavaScript(f.right)+","+JSON.stringify(f.escape)+")";case "NOT LIKE":return"this.ternaryNot(this.applyLike("+this.evaluateNodeToJavaScript(f.left)+","+this.evaluateNodeToJavaScript(f.right)+","+JSON.stringify(f.escape)+"))";case "\x3c\x3e":case "\x3c":case "\x3e":case "\x3e\x3d":case "\x3c\x3d":case "\x3d":return"this.compare("+JSON.stringify(f.operator)+","+this.evaluateNodeToJavaScript(f.left)+","+this.evaluateNodeToJavaScript(f.right)+
")";case "*":case "-":case "+":case "/":return"this.calculate("+JSON.stringify(f.operator)+","+this.evaluateNodeToJavaScript(f.left)+","+this.evaluateNodeToJavaScript(f.right)+")"}throw Error("Not Supported Operator "+f.operator);case "null":case "bool":case "string":case "number":return JSON.stringify(f.value);case "date":return"(new Date("+t(f.value).getTime().toString()+"))";case "timestamp":return"(new Date("+A(f.value).getTime().toString()+"))";case "current_time":return"date"===f.mode?"this.currentDate()":
"this.currentTimestamp()";case "column_ref":return"this.featureValue(feature,"+JSON.stringify(f.column)+",datefields,attributeAdapter)";case "function":return"this.evaluateFunction("+JSON.stringify(f.name)+","+this.evaluateNodeToJavaScript(f.args)+")"}throw Error("Unsupported sql syntax "+f.type);};k.evaluateNode=function(f,m,v){switch(f.type){case "interval":return m=this.evaluateNode(f.value,m,v),h.SqlInterval.createFromValueAndQualifer(m,f.qualifier,f.op);case "case_expression":if("simple"===f.format){var y=
B(this.evaluateNode(f.operand,m,v));for(var z=0;z<f.clauses.length;z++)if(y===B(this.evaluateNode(f.clauses[z].operand,m,v)))return this.evaluateNode(f.clauses[z].value,m,v)}else for(y=0;y<f.clauses.length;y++)if(!0===this.evaluateNode(f.clauses[y].operand,m,v))return this.evaluateNode(f.clauses[y].value,m,v);return null!==f.else?this.evaluateNode(f.else,m,v):null;case "param":return this.parameters[f.value.toLowerCase()];case "expr_list":y=[];for(z of f.value)y.push(this.evaluateNode(z,m,v));return y;
case "unary_expr":return N(this.evaluateNode(f.expr,m,v));case "binary_expr":switch(f.operator){case "AND":return da(this.evaluateNode(f.left,m,v),this.evaluateNode(f.right,m,v));case "OR":return u(this.evaluateNode(f.left,m,v),this.evaluateNode(f.right,m,v));case "IS":if("null"!==f.right.type)throw Error("Unsupported RHS for IS");return null===this.evaluateNode(f.left,m,v);case "ISNOT":if("null"!==f.right.type)throw Error("Unsupported RHS for IS");return null!==this.evaluateNode(f.left,m,v);case "IN":return y=
F(this.evaluateNode(f.right,m,v)),D(this.evaluateNode(f.left,m,v),y);case "NOT IN":return y=F(this.evaluateNode(f.right,m,v)),N(D(this.evaluateNode(f.left,m,v),y));case "BETWEEN":return y=this.evaluateNode(f.left,m,v),f=this.evaluateNode(f.right,m,v),null==y||null==f[0]||null==f[1]?null:y>=B(f[0])&&y<=B(f[1]);case "NOTBETWEEN":return y=this.evaluateNode(f.left,m,v),f=this.evaluateNode(f.right,m,v),null==y||null==f[0]||null==f[1]?null:y<B(f[0])||y>B(f[1]);case "LIKE":return I(this.evaluateNode(f.left,
m,v),this.evaluateNode(f.right,m,v),f.escape);case "NOT LIKE":return N(I(this.evaluateNode(f.left,m,v),this.evaluateNode(f.right,m,v),f.escape));case "\x3c\x3e":case "\x3c":case "\x3e":case "\x3e\x3d":case "\x3c\x3d":case "\x3d":return ra(f.operator,this.evaluateNode(f.left,m,v),this.evaluateNode(f.right,m,v));case "-":case "+":case "*":case "/":return oa(f.operator,this.evaluateNode(f.left,m,v),this.evaluateNode(f.right,m,v))}case "null":case "bool":case "string":case "number":return f.value;case "date":return t(f.value);
case "timestamp":return A(f.value);case "current_time":return m=new Date,"date"===f.mode&&m.setHours(0,0,0,0),m;case "column_ref":return Ga(m,f.column,this.datefields,v);case "function":return m=this.evaluateNode(f.args,m,v),this.isAggregate?ca.aggregateFunction(f.name,m):h.evaluateFunction(f.name,m)}throw Error("Unsupported sql syntax "+f.type);};ma._createClass(q,[{key:"fieldNames",get:function(){return this.referencedFieldNames}},{key:"hasDateFunctions",get:function(){if(null!=this._hasDateFunctions)return this._hasDateFunctions;
this._hasDateFunctions=!1;this.visitAll(this.parseTree,f=>{"current_time"===f.type?this._hasDateFunctions=!0:"function"===f.type&&(this._hasDateFunctions=this._hasDateFunctions||Za.has(f.name.toLowerCase()))});return this._hasDateFunctions}}]);return q}();const Y={getAttribute(q,k){return(q&&"object"===typeof q.attributes?q.attributes:q)[k]}};O.WhereClause=lb;O.defaultAttributeAdapter=Y;Object.defineProperty(O,"__esModule",{value:!0})});